// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package compiler

import (
	"sync"

	"tamarou.com/pvm/internal/ast"
)

// Ensure, that CompilerMock does implement Compiler.
// If this is not the case, regenerate this file with moq.
var _ Compiler = &CompilerMock{}

// CompilerMock is a mock implementation of Compiler.
//
//	func TestSomethingThatUsesCompiler(t *testing.T) {
//
//		// make and configure a mocked Compiler
//		mockedCompiler := &CompilerMock{
//			CompileFunc: func(astMoqParam *ast.AST) (string, error) {
//				panic("mock out the Compile method")
//			},
//			TargetFunc: func() Target {
//				panic("mock out the Target method")
//			},
//			ValidateFunc: func(astMoqParam *ast.AST) error {
//				panic("mock out the Validate method")
//			},
//		}
//
//		// use mockedCompiler in code that requires Compiler
//		// and then make assertions.
//
//	}
type CompilerMock struct {
	// CompileFunc mocks the Compile method.
	CompileFunc func(astMoqParam *ast.AST) (string, error)

	// TargetFunc mocks the Target method.
	TargetFunc func() Target

	// ValidateFunc mocks the Validate method.
	ValidateFunc func(astMoqParam *ast.AST) error

	// calls tracks calls to the methods.
	calls struct {
		// Compile holds details about calls to the Compile method.
		Compile []struct {
			// AstMoqParam is the astMoqParam argument value.
			AstMoqParam *ast.AST
		}
		// Target holds details about calls to the Target method.
		Target []struct {
		}
		// Validate holds details about calls to the Validate method.
		Validate []struct {
			// AstMoqParam is the astMoqParam argument value.
			AstMoqParam *ast.AST
		}
	}
	lockCompile  sync.RWMutex
	lockTarget   sync.RWMutex
	lockValidate sync.RWMutex
}

// Compile calls CompileFunc.
func (mock *CompilerMock) Compile(astMoqParam *ast.AST) (string, error) {
	if mock.CompileFunc == nil {
		panic("CompilerMock.CompileFunc: method is nil but Compiler.Compile was just called")
	}
	callInfo := struct {
		AstMoqParam *ast.AST
	}{
		AstMoqParam: astMoqParam,
	}
	mock.lockCompile.Lock()
	mock.calls.Compile = append(mock.calls.Compile, callInfo)
	mock.lockCompile.Unlock()
	return mock.CompileFunc(astMoqParam)
}

// CompileCalls gets all the calls that were made to Compile.
// Check the length with:
//
//	len(mockedCompiler.CompileCalls())
func (mock *CompilerMock) CompileCalls() []struct {
	AstMoqParam *ast.AST
} {
	var calls []struct {
		AstMoqParam *ast.AST
	}
	mock.lockCompile.RLock()
	calls = mock.calls.Compile
	mock.lockCompile.RUnlock()
	return calls
}

// Target calls TargetFunc.
func (mock *CompilerMock) Target() Target {
	if mock.TargetFunc == nil {
		panic("CompilerMock.TargetFunc: method is nil but Compiler.Target was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTarget.Lock()
	mock.calls.Target = append(mock.calls.Target, callInfo)
	mock.lockTarget.Unlock()
	return mock.TargetFunc()
}

// TargetCalls gets all the calls that were made to Target.
// Check the length with:
//
//	len(mockedCompiler.TargetCalls())
func (mock *CompilerMock) TargetCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTarget.RLock()
	calls = mock.calls.Target
	mock.lockTarget.RUnlock()
	return calls
}

// Validate calls ValidateFunc.
func (mock *CompilerMock) Validate(astMoqParam *ast.AST) error {
	if mock.ValidateFunc == nil {
		panic("CompilerMock.ValidateFunc: method is nil but Compiler.Validate was just called")
	}
	callInfo := struct {
		AstMoqParam *ast.AST
	}{
		AstMoqParam: astMoqParam,
	}
	mock.lockValidate.Lock()
	mock.calls.Validate = append(mock.calls.Validate, callInfo)
	mock.lockValidate.Unlock()
	return mock.ValidateFunc(astMoqParam)
}

// ValidateCalls gets all the calls that were made to Validate.
// Check the length with:
//
//	len(mockedCompiler.ValidateCalls())
func (mock *CompilerMock) ValidateCalls() []struct {
	AstMoqParam *ast.AST
} {
	var calls []struct {
		AstMoqParam *ast.AST
	}
	mock.lockValidate.RLock()
	calls = mock.calls.Validate
	mock.lockValidate.RUnlock()
	return calls
}
