repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: no-go-testing
      - id: golangci-lint
        exclude: ^(internal/parser/treesitter/|cmd/psc/)
      - id: go-critic
      - id: go-unit-tests
        args: [./internal/cli/..., ./internal/config/..., ./internal/cpan/..., ./internal/errors/..., ./internal/log/..., ./internal/perl/..., ./internal/pvi/..., ./internal/pvm/..., ./internal/pvx/..., ./internal/typedef/..., ./internal/version/..., ./internal/xdg/...]
      - id: go-build
        args: [./cmd/pvm, ./cmd/pvx, ./cmd/pvi]
      # - id: validate-toml
  - repo: local
    hooks:
      - id: go-vet-custom
        name: 'go vet custom'
        description: "Runs go vet on the entire module (excluding tree-sitter)"
        entry: .github/hooks/run-go-vet.sh
        language: script
        pass_filenames: false
        files: '\.go$'
        exclude: ^(internal/parser/treesitter/|cmd/psc/)
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
