// ABOUTME: Shim generation for Perl executables
// ABOUTME: Provides functionality to create and manage shim executables for Perl commands

package perl

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"text/template"

	"tamarou.com/pvm/internal/errors"
	"tamarou.com/pvm/internal/xdg"
)

// Shim-related error codes
const (
	ErrShimCreationFailed   = "401" // Failed to create shim
	ErrShimTemplateFailed   = "402" // Failed to process shim template
	ErrShimExecutableFailed = "403" // Failed to make shim executable
	ErrShimDirectoryFailed  = "404" // Failed to create shim directory
	ErrShimGenerationFailed = "405" // Failed to generate shims
)

// ShimType represents the type of a shim
type ShimType string

const (
	// ShimPerl represents the main perl executable
	ShimPerl ShimType = "perl"

	// ShimScript represents perl scripts like cpan, prove, etc.
	ShimScript ShimType = "script"
)

// ShimInfo contains information about a shim executable
type ShimInfo struct {
	// Name of the shim (e.g., "perl", "cpan", "prove")
	Name string

	// Type of the shim (perl or script)
	Type ShimType

	// Path to the original executable/script (optional, used for system scripts)
	OriginalPath string
}

// ShimTemplate contains the data for the shim template
type ShimTemplate struct {
	// Name of the shim executable
	Name string

	// Type of the shim
	Type string

	// Full path to the PVM binary
	PVMPath string

	// Whether this is a Windows shim
	IsWindows bool

	// Whether this is a script (as opposed to the perl executable)
	IsScript bool
}

// Standard Perl commands to create shims for
// NOTE: Most Perl commands (perl, cpan, prove, etc.) are now accessed directly
// via the two-tier PATH system. Only tool-specific shims are created here.
var standardShims = []ShimInfo{
	// Reserved for pvm tool install shims
}

// Shim template for Unix-like systems (Linux, macOS)
const unixShimTemplate = `#!/usr/bin/env sh
# Generated by PVM - DO NOT EDIT
# Shim for: {{ .Name }}

# Get the absolute path of this shim
SHIM_PATH="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"

# Get the PVM executable
PVM_EXEC="{{ .PVMPath }}"

# Execute the command through PVM
if [ -x "$PVM_EXEC" ]; then
  exec "$PVM_EXEC" exec -- "{{ .Name }}" "$@"
else
  echo "Error: PVM executable not found at '$PVM_EXEC'"
  echo "Please ensure PVM is installed correctly"
  exit 1
fi
`

// Shim template for Windows systems (batch file)
const windowsShimTemplate = `@echo off
:: Generated by PVM - DO NOT EDIT
:: Shim for: {{ .Name }}

set "PVM_EXEC={{ .PVMPath }}"

:: Execute the command through PVM
if exist "%PVM_EXEC%" (
  "%PVM_EXEC%" exec -- "{{ .Name }}" %*
) else (
  echo Error: PVM executable not found at '%PVM_EXEC%'
  echo Please ensure PVM is installed correctly
  exit /b 1
)
`

// executablePath is a variable that can be mocked in tests
var executablePath = os.Executable

// GenerateShims creates shims for all standard Perl commands
// This includes perl itself and standard utilities like cpan, prove, etc.
func GenerateShims() error {
	// Get XDG directories
	dirs, err := xdg.GetDirs()
	if err != nil {
		return errors.NewSystemError("001",
			"Failed to determine XDG directories", err)
	}

	// Ensure directories exist
	err = dirs.EnsureDirs()
	if err != nil {
		return errors.NewSystemError("002",
			"Failed to create required directories", err)
	}

	// Get path to PVM executable
	pvmPath, err := executablePath()
	if err != nil {
		return errors.NewVersionError(
			ErrShimGenerationFailed,
			"Failed to determine PVM executable path",
			err)
	}

	// Create shims for standard commands
	for _, shimInfo := range standardShims {
		err := createShim(dirs.BinDir, shimInfo, pvmPath)
		if err != nil {
			return err
		}
	}

	// Note: Perl binaries (perl, cpan, prove, etc.) are now accessed directly
	// via the two-tier PATH system. No shims needed for them.
	// This function is reserved for future pvm tool install shims.

	return nil
}

// shouldCreateShimFor determines whether we should create a shim for a given command
func shouldCreateShimFor(commandName string) bool {
	// Skip version-specific commands (e.g., perl5.26.0, cpan5.34.0)
	if strings.Contains(commandName, "5.") {
		return false
	}

	// Allow core Perl utilities
	coreCommands := map[string]bool{
		"perlbug":     true,
		"perldoc":     true,
		"perlivp":     true,
		"perlthanks":  true,
		"piconv":      true,
		"pl2pm":       true,
		"pod2html":    true,
		"pod2man":     true,
		"pod2text":    true,
		"pod2usage":   true,
		"podchecker":  true,
		"podselect":   true,
		"ptar":        true,
		"ptardiff":    true,
		"ptargrep":    true,
		"shasum":      true,
		"splain":      true,
		"streamzip":   true,
		"zipdetails":  true,
		"json_pp":     true,
		"libnetcfg":   true,
		"instmodsh":   true,
		"encguess":    true,
		"config_data": true,
	}

	if coreCommands[commandName] {
		return true
	}

	// Skip everything else (installed modules, etc.)
	return false
}

// CreateShim creates a shim executable for a given command
func createShim(shimDir string, shimInfo ShimInfo, pvmPath string) error {
	// Determine shim filename with extension for Windows
	shimName := shimInfo.Name
	if runtime.GOOS == "windows" {
		shimName += ".bat"
	}

	// Full path to the shim
	shimPath := filepath.Join(shimDir, shimName)

	// Prepare template data
	templateData := ShimTemplate{
		Name:      shimInfo.Name,
		Type:      string(shimInfo.Type),
		PVMPath:   pvmPath,
		IsWindows: runtime.GOOS == "windows",
		IsScript:  shimInfo.Type == ShimScript,
	}

	// Select appropriate template based on OS
	var shimTemplateText string
	if runtime.GOOS == "windows" {
		shimTemplateText = windowsShimTemplate
	} else {
		shimTemplateText = unixShimTemplate
	}

	// Parse template
	tmpl, err := template.New("shim").Parse(shimTemplateText)
	if err != nil {
		return errors.NewVersionError(
			ErrShimTemplateFailed,
			fmt.Sprintf("Failed to parse shim template for %s", shimInfo.Name),
			err)
	}

	// Process template
	var shimContent bytes.Buffer
	err = tmpl.Execute(&shimContent, templateData)
	if err != nil {
		return errors.NewVersionError(
			ErrShimTemplateFailed,
			fmt.Sprintf("Failed to process shim template for %s", shimInfo.Name),
			err)
	}

	// Create or overwrite the shim file
	err = os.WriteFile(shimPath, shimContent.Bytes(), 0755)
	if err != nil {
		return errors.NewVersionError(
			ErrShimCreationFailed,
			fmt.Sprintf("Failed to write shim file for %s", shimInfo.Name),
			err).
			WithLocation(shimPath)
	}

	// For Unix-like systems, ensure the shim is executable
	if runtime.GOOS != "windows" {
		err = os.Chmod(shimPath, 0755)
		if err != nil {
			return errors.NewVersionError(
				ErrShimExecutableFailed,
				fmt.Sprintf("Failed to make shim executable for %s", shimInfo.Name),
				err).
				WithLocation(shimPath)
		}
	}

	return nil
}

// DiscoverAvailableShims lists all commands available in installed Perl versions
// This is used to determine which shims should be created during rehash
func DiscoverAvailableShims() ([]ShimInfo, error) {
	// Start with standard shims
	shims := make([]ShimInfo, len(standardShims))
	copy(shims, standardShims)

	// Get installed versions
	installedVersions, err := GetInstalledVersions()
	if err != nil {
		// Return just standard shims if we can't get installed versions
		return shims, nil
	}

	// Create a map of existing shims to avoid duplicates
	existingShims := make(map[string]bool)
	for _, shim := range shims {
		existingShims[shim.Name] = true
	}

	// Find additional scripts in installed versions
	for _, version := range installedVersions {
		// Skip system Perl
		if version.Source == "system" {
			continue
		}

		// Check bin directory
		binDir := filepath.Join(version.InstallPath, "bin")
		files, err := os.ReadDir(binDir)
		if err != nil {
			// Skip if bin directory doesn't exist or can't be read
			continue
		}

		// Add scripts to the list
		for _, file := range files {
			// Skip directories
			if file.IsDir() {
				continue
			}

			// Skip if we already have this shim
			fileName := file.Name()
			if existingShims[fileName] {
				continue
			}

			// Add to the list
			shims = append(shims, ShimInfo{
				Name:         fileName,
				Type:         ShimScript,
				OriginalPath: filepath.Join(binDir, fileName),
			})

			// Mark as existing
			existingShims[fileName] = true
		}
	}

	return shims, nil
}

// GenerateShimsFunc is a variable pointing to GenerateShims
// for easier mocking in tests
var GenerateShimsFunc = GenerateShims

// Rehash rebuilds all shim executables
// This should be called after installing or uninstalling Perl versions
func Rehash() error {
	return GenerateShimsFunc()
}

// Provides a way to check if the PATH is properly set up to use PVM shims
func CheckPath() (bool, string, error) {
	// Get XDG directories
	dirs, err := xdg.GetDirs()
	if err != nil {
		return false, "", errors.NewSystemError("001",
			"Failed to determine XDG directories", err)
	}

	// Get the shim directory
	shimDir := dirs.BinDir

	// Get the PATH environment variable
	path := os.Getenv("PATH")
	pathParts := strings.Split(path, string(os.PathListSeparator))

	// Check if the shim directory is in PATH
	for _, part := range pathParts {
		// Normalize paths for comparison
		partAbs, err := filepath.Abs(part)
		if err != nil {
			continue
		}
		shimDirAbs, err := filepath.Abs(shimDir)
		if err != nil {
			return false, shimDir, err
		}

		if partAbs == shimDirAbs {
			return true, shimDir, nil
		}
	}

	return false, shimDir, nil
}

// GetPathConfigCommand returns a shell command to add the shim directory to PATH
func GetPathConfigCommand() (string, error) {
	// Get XDG directories
	dirs, err := xdg.GetDirs()
	if err != nil {
		return "", errors.NewSystemError("001",
			"Failed to determine XDG directories", err)
	}

	// Get the shim directory
	shimDir := dirs.BinDir

	// Create different commands based on OS
	switch runtime.GOOS {
	case "windows":
		return fmt.Sprintf("setx PATH \"%%PATH%%;%s\"", shimDir), nil
	case "darwin", "linux":
		// For bash/zsh
		return fmt.Sprintf("echo 'export PATH=\"%s:$PATH\"' >> ~/.bashrc", shimDir), nil
	default:
		return fmt.Sprintf("export PATH=\"%s:$PATH\"", shimDir), nil
	}
}

// GetShimCommand returns the actual command that should be executed
// This is used by the shim itself to execute the correct Perl version
func GetShimCommand(shimName string, args []string) (*exec.Cmd, error) {
	// Resolve which Perl version to use
	resolved, err := ResolveVersion(nil)
	if err != nil {
		return nil, err
	}

	var cmd *exec.Cmd

	// Handle differently based on shim type
	if shimName == "perl" {
		// For perl executable, run it directly (resolved.Path already points to perl executable)
		cmd = exec.Command(resolved.Path, args...)
	} else {
		// For scripts, we need to find the script in the same directory structure as perl
		// resolved.Path points to the perl executable, so we need to derive the script path
		installDir := filepath.Dir(filepath.Dir(resolved.Path)) // Remove /bin/perl to get install dir
		scriptPath := filepath.Join(installDir, "bin", shimName)

		// Check if the script exists
		_, err := os.Stat(scriptPath)
		if err != nil {
			return nil, errors.NewVersionError(
				ErrShimExecutableFailed,
				fmt.Sprintf("Script %s not found in Perl %s", shimName, resolved.Version),
				err).
				WithLocation(scriptPath)
		}

		// Check if it's executable
		info, err := os.Stat(scriptPath)
		if err == nil {
			mode := info.Mode()
			if mode&0111 != 0 {
				// Script is executable, run directly
				cmd = exec.Command(scriptPath, args...)
			} else {
				// Not executable, run through perl (resolved.Path already points to perl executable)
				cmd = exec.Command(resolved.Path, append([]string{scriptPath}, args...)...)
			}
		} else {
			// Fallback to running through perl (resolved.Path already points to perl executable)
			cmd = exec.Command(resolved.Path, append([]string{scriptPath}, args...)...)
		}
	}

	// Set environment variables
	cmd.Env = os.Environ()

	// Set up input/output
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd, nil
}

// IsShimDirectory checks if a given directory is the PVM shim directory
func IsShimDirectory(dir string) (bool, error) {
	// Get XDG directories
	dirs, err := xdg.GetDirs()
	if err != nil {
		return false, errors.NewSystemError("001",
			"Failed to determine XDG directories", err)
	}

	// Normalize paths for comparison
	dirAbs, err := filepath.Abs(dir)
	if err != nil {
		return false, err
	}
	shimDirAbs, err := filepath.Abs(dirs.BinDir)
	if err != nil {
		return false, err
	}

	return dirAbs == shimDirAbs, nil
}

// RemoveAllShims removes all shim files from the shim directory
func RemoveAllShims() error {
	// Get XDG directories
	dirs, err := xdg.GetDirs()
	if err != nil {
		return errors.NewSystemError("001",
			"Failed to determine XDG directories", err)
	}

	// Read the directory
	entries, err := os.ReadDir(dirs.BinDir)
	if err != nil {
		if os.IsNotExist(err) {
			// Directory doesn't exist, nothing to remove
			return nil
		}
		return errors.NewVersionError(
			ErrShimDirectoryFailed,
			"Failed to read shim directory",
			err).
			WithLocation(dirs.BinDir)
	}

	// Remove each file
	for _, entry := range entries {
		if entry.IsDir() {
			// Skip directories
			continue
		}

		// Remove the file
		err := os.Remove(filepath.Join(dirs.BinDir, entry.Name()))
		if err != nil {
			// Non-fatal error, continue with other files
			continue
		}
	}

	return nil
}
