// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package binder

import (
	sitter "github.com/tree-sitter/go-tree-sitter"
	"sync"
	"tamarou.com/pvm/internal/ast"
)

// Ensure, that BinderMock does implement Binder.
// If this is not the case, regenerate this file with moq.
var _ Binder = &BinderMock{}

// BinderMock is a mock implementation of Binder.
//
//	func TestSomethingThatUsesBinder(t *testing.T) {
//
//		// make and configure a mocked Binder
//		mockedBinder := &BinderMock{
//			BindCSTFunc: func(root *sitter.Node, content []byte, typeAnnotations []*ast.TypeAnnotation) (*SymbolTable, error) {
//				panic("mock out the BindCST method")
//			},
//		}
//
//		// use mockedBinder in code that requires Binder
//		// and then make assertions.
//
//	}
type BinderMock struct {
	// BindCSTFunc mocks the BindCST method.
	BindCSTFunc func(root *sitter.Node, content []byte, typeAnnotations []*ast.TypeAnnotation) (*SymbolTable, error)

	// calls tracks calls to the methods.
	calls struct {
		// BindCST holds details about calls to the BindCST method.
		BindCST []struct {
			// Root is the root argument value.
			Root *sitter.Node
			// Content is the content argument value.
			Content []byte
			// TypeAnnotations is the typeAnnotations argument value.
			TypeAnnotations []*ast.TypeAnnotation
		}
	}
	lockBindCST sync.RWMutex
}

// BindCST calls BindCSTFunc.
func (mock *BinderMock) BindCST(root *sitter.Node, content []byte, typeAnnotations []*ast.TypeAnnotation) (*SymbolTable, error) {
	if mock.BindCSTFunc == nil {
		panic("BinderMock.BindCSTFunc: method is nil but Binder.BindCST was just called")
	}
	callInfo := struct {
		Root            *sitter.Node
		Content         []byte
		TypeAnnotations []*ast.TypeAnnotation
	}{
		Root:            root,
		Content:         content,
		TypeAnnotations: typeAnnotations,
	}
	mock.lockBindCST.Lock()
	mock.calls.BindCST = append(mock.calls.BindCST, callInfo)
	mock.lockBindCST.Unlock()
	return mock.BindCSTFunc(root, content, typeAnnotations)
}

// BindCSTCalls gets all the calls that were made to BindCST.
// Check the length with:
//
//	len(mockedBinder.BindCSTCalls())
func (mock *BinderMock) BindCSTCalls() []struct {
	Root            *sitter.Node
	Content         []byte
	TypeAnnotations []*ast.TypeAnnotation
} {
	var calls []struct {
		Root            *sitter.Node
		Content         []byte
		TypeAnnotations []*ast.TypeAnnotation
	}
	mock.lockBindCST.RLock()
	calls = mock.calls.BindCST
	mock.lockBindCST.RUnlock()
	return calls
}

// Ensure, that SymbolResolverMock does implement SymbolResolver.
// If this is not the case, regenerate this file with moq.
var _ SymbolResolver = &SymbolResolverMock{}

// SymbolResolverMock is a mock implementation of SymbolResolver.
//
//	func TestSomethingThatUsesSymbolResolver(t *testing.T) {
//
//		// make and configure a mocked SymbolResolver
//		mockedSymbolResolver := &SymbolResolverMock{
//			GetVisibleSymbolsFunc: func() []*Symbol {
//				panic("mock out the GetVisibleSymbols method")
//			},
//			ResolveInScopeFunc: func(scope *Scope, name string, kind SymbolKind) *Symbol {
//				panic("mock out the ResolveInScope method")
//			},
//			ResolveSymbolFunc: func(name string, kind SymbolKind) *Symbol {
//				panic("mock out the ResolveSymbol method")
//			},
//		}
//
//		// use mockedSymbolResolver in code that requires SymbolResolver
//		// and then make assertions.
//
//	}
type SymbolResolverMock struct {
	// GetVisibleSymbolsFunc mocks the GetVisibleSymbols method.
	GetVisibleSymbolsFunc func() []*Symbol

	// ResolveInScopeFunc mocks the ResolveInScope method.
	ResolveInScopeFunc func(scope *Scope, name string, kind SymbolKind) *Symbol

	// ResolveSymbolFunc mocks the ResolveSymbol method.
	ResolveSymbolFunc func(name string, kind SymbolKind) *Symbol

	// calls tracks calls to the methods.
	calls struct {
		// GetVisibleSymbols holds details about calls to the GetVisibleSymbols method.
		GetVisibleSymbols []struct {
		}
		// ResolveInScope holds details about calls to the ResolveInScope method.
		ResolveInScope []struct {
			// Scope is the scope argument value.
			Scope *Scope
			// Name is the name argument value.
			Name string
			// Kind is the kind argument value.
			Kind SymbolKind
		}
		// ResolveSymbol holds details about calls to the ResolveSymbol method.
		ResolveSymbol []struct {
			// Name is the name argument value.
			Name string
			// Kind is the kind argument value.
			Kind SymbolKind
		}
	}
	lockGetVisibleSymbols sync.RWMutex
	lockResolveInScope    sync.RWMutex
	lockResolveSymbol     sync.RWMutex
}

// GetVisibleSymbols calls GetVisibleSymbolsFunc.
func (mock *SymbolResolverMock) GetVisibleSymbols() []*Symbol {
	if mock.GetVisibleSymbolsFunc == nil {
		panic("SymbolResolverMock.GetVisibleSymbolsFunc: method is nil but SymbolResolver.GetVisibleSymbols was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetVisibleSymbols.Lock()
	mock.calls.GetVisibleSymbols = append(mock.calls.GetVisibleSymbols, callInfo)
	mock.lockGetVisibleSymbols.Unlock()
	return mock.GetVisibleSymbolsFunc()
}

// GetVisibleSymbolsCalls gets all the calls that were made to GetVisibleSymbols.
// Check the length with:
//
//	len(mockedSymbolResolver.GetVisibleSymbolsCalls())
func (mock *SymbolResolverMock) GetVisibleSymbolsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetVisibleSymbols.RLock()
	calls = mock.calls.GetVisibleSymbols
	mock.lockGetVisibleSymbols.RUnlock()
	return calls
}

// ResolveInScope calls ResolveInScopeFunc.
func (mock *SymbolResolverMock) ResolveInScope(scope *Scope, name string, kind SymbolKind) *Symbol {
	if mock.ResolveInScopeFunc == nil {
		panic("SymbolResolverMock.ResolveInScopeFunc: method is nil but SymbolResolver.ResolveInScope was just called")
	}
	callInfo := struct {
		Scope *Scope
		Name  string
		Kind  SymbolKind
	}{
		Scope: scope,
		Name:  name,
		Kind:  kind,
	}
	mock.lockResolveInScope.Lock()
	mock.calls.ResolveInScope = append(mock.calls.ResolveInScope, callInfo)
	mock.lockResolveInScope.Unlock()
	return mock.ResolveInScopeFunc(scope, name, kind)
}

// ResolveInScopeCalls gets all the calls that were made to ResolveInScope.
// Check the length with:
//
//	len(mockedSymbolResolver.ResolveInScopeCalls())
func (mock *SymbolResolverMock) ResolveInScopeCalls() []struct {
	Scope *Scope
	Name  string
	Kind  SymbolKind
} {
	var calls []struct {
		Scope *Scope
		Name  string
		Kind  SymbolKind
	}
	mock.lockResolveInScope.RLock()
	calls = mock.calls.ResolveInScope
	mock.lockResolveInScope.RUnlock()
	return calls
}

// ResolveSymbol calls ResolveSymbolFunc.
func (mock *SymbolResolverMock) ResolveSymbol(name string, kind SymbolKind) *Symbol {
	if mock.ResolveSymbolFunc == nil {
		panic("SymbolResolverMock.ResolveSymbolFunc: method is nil but SymbolResolver.ResolveSymbol was just called")
	}
	callInfo := struct {
		Name string
		Kind SymbolKind
	}{
		Name: name,
		Kind: kind,
	}
	mock.lockResolveSymbol.Lock()
	mock.calls.ResolveSymbol = append(mock.calls.ResolveSymbol, callInfo)
	mock.lockResolveSymbol.Unlock()
	return mock.ResolveSymbolFunc(name, kind)
}

// ResolveSymbolCalls gets all the calls that were made to ResolveSymbol.
// Check the length with:
//
//	len(mockedSymbolResolver.ResolveSymbolCalls())
func (mock *SymbolResolverMock) ResolveSymbolCalls() []struct {
	Name string
	Kind SymbolKind
} {
	var calls []struct {
		Name string
		Kind SymbolKind
	}
	mock.lockResolveSymbol.RLock()
	calls = mock.calls.ResolveSymbol
	mock.lockResolveSymbol.RUnlock()
	return calls
}

// Ensure, that ScopeManagerMock does implement ScopeManager.
// If this is not the case, regenerate this file with moq.
var _ ScopeManager = &ScopeManagerMock{}

// ScopeManagerMock is a mock implementation of ScopeManager.
//
//	func TestSomethingThatUsesScopeManager(t *testing.T) {
//
//		// make and configure a mocked ScopeManager
//		mockedScopeManager := &ScopeManagerMock{
//			EnterScopeFunc: func(kind ScopeKind, node ast.Node) *Scope {
//				panic("mock out the EnterScope method")
//			},
//			ExitScopeFunc: func() *Scope {
//				panic("mock out the ExitScope method")
//			},
//			FindScopeFunc: func(node ast.Node) *Scope {
//				panic("mock out the FindScope method")
//			},
//			GetCurrentScopeFunc: func() *Scope {
//				panic("mock out the GetCurrentScope method")
//			},
//		}
//
//		// use mockedScopeManager in code that requires ScopeManager
//		// and then make assertions.
//
//	}
type ScopeManagerMock struct {
	// EnterScopeFunc mocks the EnterScope method.
	EnterScopeFunc func(kind ScopeKind, node ast.Node) *Scope

	// ExitScopeFunc mocks the ExitScope method.
	ExitScopeFunc func() *Scope

	// FindScopeFunc mocks the FindScope method.
	FindScopeFunc func(node ast.Node) *Scope

	// GetCurrentScopeFunc mocks the GetCurrentScope method.
	GetCurrentScopeFunc func() *Scope

	// calls tracks calls to the methods.
	calls struct {
		// EnterScope holds details about calls to the EnterScope method.
		EnterScope []struct {
			// Kind is the kind argument value.
			Kind ScopeKind
			// Node is the node argument value.
			Node ast.Node
		}
		// ExitScope holds details about calls to the ExitScope method.
		ExitScope []struct {
		}
		// FindScope holds details about calls to the FindScope method.
		FindScope []struct {
			// Node is the node argument value.
			Node ast.Node
		}
		// GetCurrentScope holds details about calls to the GetCurrentScope method.
		GetCurrentScope []struct {
		}
	}
	lockEnterScope      sync.RWMutex
	lockExitScope       sync.RWMutex
	lockFindScope       sync.RWMutex
	lockGetCurrentScope sync.RWMutex
}

// EnterScope calls EnterScopeFunc.
func (mock *ScopeManagerMock) EnterScope(kind ScopeKind, node ast.Node) *Scope {
	if mock.EnterScopeFunc == nil {
		panic("ScopeManagerMock.EnterScopeFunc: method is nil but ScopeManager.EnterScope was just called")
	}
	callInfo := struct {
		Kind ScopeKind
		Node ast.Node
	}{
		Kind: kind,
		Node: node,
	}
	mock.lockEnterScope.Lock()
	mock.calls.EnterScope = append(mock.calls.EnterScope, callInfo)
	mock.lockEnterScope.Unlock()
	return mock.EnterScopeFunc(kind, node)
}

// EnterScopeCalls gets all the calls that were made to EnterScope.
// Check the length with:
//
//	len(mockedScopeManager.EnterScopeCalls())
func (mock *ScopeManagerMock) EnterScopeCalls() []struct {
	Kind ScopeKind
	Node ast.Node
} {
	var calls []struct {
		Kind ScopeKind
		Node ast.Node
	}
	mock.lockEnterScope.RLock()
	calls = mock.calls.EnterScope
	mock.lockEnterScope.RUnlock()
	return calls
}

// ExitScope calls ExitScopeFunc.
func (mock *ScopeManagerMock) ExitScope() *Scope {
	if mock.ExitScopeFunc == nil {
		panic("ScopeManagerMock.ExitScopeFunc: method is nil but ScopeManager.ExitScope was just called")
	}
	callInfo := struct {
	}{}
	mock.lockExitScope.Lock()
	mock.calls.ExitScope = append(mock.calls.ExitScope, callInfo)
	mock.lockExitScope.Unlock()
	return mock.ExitScopeFunc()
}

// ExitScopeCalls gets all the calls that were made to ExitScope.
// Check the length with:
//
//	len(mockedScopeManager.ExitScopeCalls())
func (mock *ScopeManagerMock) ExitScopeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockExitScope.RLock()
	calls = mock.calls.ExitScope
	mock.lockExitScope.RUnlock()
	return calls
}

// FindScope calls FindScopeFunc.
func (mock *ScopeManagerMock) FindScope(node ast.Node) *Scope {
	if mock.FindScopeFunc == nil {
		panic("ScopeManagerMock.FindScopeFunc: method is nil but ScopeManager.FindScope was just called")
	}
	callInfo := struct {
		Node ast.Node
	}{
		Node: node,
	}
	mock.lockFindScope.Lock()
	mock.calls.FindScope = append(mock.calls.FindScope, callInfo)
	mock.lockFindScope.Unlock()
	return mock.FindScopeFunc(node)
}

// FindScopeCalls gets all the calls that were made to FindScope.
// Check the length with:
//
//	len(mockedScopeManager.FindScopeCalls())
func (mock *ScopeManagerMock) FindScopeCalls() []struct {
	Node ast.Node
} {
	var calls []struct {
		Node ast.Node
	}
	mock.lockFindScope.RLock()
	calls = mock.calls.FindScope
	mock.lockFindScope.RUnlock()
	return calls
}

// GetCurrentScope calls GetCurrentScopeFunc.
func (mock *ScopeManagerMock) GetCurrentScope() *Scope {
	if mock.GetCurrentScopeFunc == nil {
		panic("ScopeManagerMock.GetCurrentScopeFunc: method is nil but ScopeManager.GetCurrentScope was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetCurrentScope.Lock()
	mock.calls.GetCurrentScope = append(mock.calls.GetCurrentScope, callInfo)
	mock.lockGetCurrentScope.Unlock()
	return mock.GetCurrentScopeFunc()
}

// GetCurrentScopeCalls gets all the calls that were made to GetCurrentScope.
// Check the length with:
//
//	len(mockedScopeManager.GetCurrentScopeCalls())
func (mock *ScopeManagerMock) GetCurrentScopeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetCurrentScope.RLock()
	calls = mock.calls.GetCurrentScope
	mock.lockGetCurrentScope.RUnlock()
	return calls
}
