#!/usr/bin/env sh
# PVM Shell Integration for Bash/Zsh
# Template file - Generated by PVM init

# Record the shell that sourced this integration, so the pvm() function can
# tell pvm the calling shell's identity when invoking it. Do NOT export —
# sub-shells of a different family (bash -c from fish, zsh scripts, etc.)
# must not inherit a stale value; they detect their own shell via $SHELL or
# their own sourced template.
if [ -n "${ZSH_VERSION-}" ]; then
    _PVM_SHELL_TYPE=zsh
else
    _PVM_SHELL_TYPE=bash
fi

# Function to find PVM executable dynamically
_pvm_find_executable() {
    # First, try to find pvm in PATH
    if command -v pvm >/dev/null 2>&1; then
        command -v pvm
        return 0
    fi

    # Fallback to the path that was used during generation
    local fallback_path="{{.PVMPath}}"
    if [ -x "$fallback_path" ]; then
        echo "$fallback_path"
        return 0
    fi

    # If all else fails, show an error
    echo "Error: PVM executable not found. Please ensure PVM is installed and in PATH." >&2
    return 1
}

# Function to get PVM executable path
_pvm_executable() {
    if [ -z "${PVM_EXEC_CACHE-}" ]; then
        PVM_EXEC_CACHE="$(_pvm_find_executable)"
        if [ $? -ne 0 ]; then
            return 1
        fi
    fi
    echo "$PVM_EXEC_CACHE"
}

# Function to update PATH with current Perl version
_pvm_update_perl_path() {
    local xdg_bin_home="${XDG_BIN_HOME:-$HOME/.local/bin}"
    local xdg_data_home="${XDG_DATA_HOME:-$HOME/.local/share}"
    local pvm_exec="$(_pvm_executable)"
    if [ $? -ne 0 ]; then
        return 1
    fi

    # FIRST: Always clean up existing pvm perl paths from PATH
    local clean_path=""
    local found_xdg_bin_home=false

    # Split PATH manually to avoid issues with set command
    local remaining_path="$PATH"
    while [ -n "$remaining_path" ]; do
        # Extract the first path component
        if echo "$remaining_path" | grep -q ':'; then
            path_entry="${remaining_path%%:*}"
            remaining_path="${remaining_path#*:}"
        else
            path_entry="$remaining_path"
            remaining_path=""
        fi

        # Skip empty entries (can happen with double colons)
        [ -z "$path_entry" ] && continue

        # Track if we found XDG_BIN_HOME in existing PATH
        if [ "$path_entry" = "$xdg_bin_home" ]; then
            found_xdg_bin_home=true
        fi

        case "$path_entry" in
            */pvm/versions/*/bin)
                # Skip existing pvm perl paths - we'll replace them
                ;;
            *)
                # Keep all other paths (including XDG_BIN_HOME)
                if [ -z "$clean_path" ]; then
                    clean_path="$path_entry"
                else
                    clean_path="$clean_path:$path_entry"
                fi
                ;;
        esac
    done

    # SECOND: Ensure XDG_BIN_HOME is at the front of clean_path
    if [ "$found_xdg_bin_home" = false ]; then
        # XDG_BIN_HOME wasn't in PATH, add it to the front
        if [ -z "$clean_path" ]; then
            clean_path="$xdg_bin_home"
        else
            clean_path="$xdg_bin_home:$clean_path"
        fi
    fi

    # THIRD: Set clean PATH temporarily so PVM resolver doesn't see old perl
    export PATH="$clean_path"

    # FOURTH: Now ask PVM what version should be active (in clean environment)
    local current_version="$(PVM_SHELL="$_PVM_SHELL_TYPE" "$pvm_exec" current --bare 2>/dev/null)"

    # Add the current version's bin path if we have a version
    if [ -n "$current_version" ] && [ "$current_version" != "system" ]; then
        local new_perl_bin="$xdg_data_home/pvm/versions/$current_version/bin"
        if [ -d "$new_perl_bin" ]; then
            export PATH="$new_perl_bin:$clean_path"
        else
            export PATH="$clean_path"
        fi
    else
        # No current version or system version - just use cleaned path
        export PATH="$clean_path"
    fi

    # Handle library environment if PVM_PERL_LIBRARY is set
    if [ -n "${PVM_PERL_LIBRARY-}" ]; then
        local library_env_dir="$xdg_data_home/pvm/environments/$PVM_PERL_LIBRARY"
        if [ -d "$library_env_dir" ]; then
            local library_lib_dir="$library_env_dir/lib/perl5"
            if [ -d "$library_lib_dir" ]; then
                if [ -n "${PERL5LIB-}" ]; then
                    export PERL5LIB="$library_lib_dir:$PERL5LIB"
                else
                    export PERL5LIB="$library_lib_dir"
                fi
            fi
            local library_bin_dir="$library_env_dir/bin"
            if [ -d "$library_bin_dir" ]; then
                export PATH="$library_bin_dir:$PATH"
            fi
        fi
    else
        # Clear library-specific PERL5LIB when no library is active
        if [ -n "${PERL5LIB-}" ]; then
            local cleaned_perl5lib=""
            local remaining_perl5lib="$PERL5LIB"
            while [ -n "$remaining_perl5lib" ]; do
                if echo "$remaining_perl5lib" | grep -q ':'; then
                    lib_entry="${remaining_perl5lib%%:*}"
                    remaining_perl5lib="${remaining_perl5lib#*:}"
                else
                    lib_entry="$remaining_perl5lib"
                    remaining_perl5lib=""
                fi
                case "$lib_entry" in
                    */pvm/environments/*/lib/perl5)
                        ;;
                    *)
                        if [ -z "$cleaned_perl5lib" ]; then
                            cleaned_perl5lib="$lib_entry"
                        else
                            cleaned_perl5lib="$cleaned_perl5lib:$lib_entry"
                        fi
                        ;;
                esac
            done
            export PERL5LIB="$cleaned_perl5lib"
        fi
    fi
}

# Function to initialize PVM
pvm_init() {
    # Get XDG directories for the two-tier PATH system
    local xdg_bin_home="${XDG_BIN_HOME:-$HOME/.local/bin}"
    local xdg_data_home="${XDG_DATA_HOME:-$HOME/.local/share}"

    # Add XDG_BIN_HOME to PATH (for pvm tool install shims)
    case ":${PATH}:" in
        *":${xdg_bin_home}:"*) ;;
        *) export PATH="${xdg_bin_home}:${PATH}" ;;
    esac

    # Add current Perl bin directory to PATH (for perl, cpan, prove, etc.)
    _pvm_update_perl_path

    # Define main pvm function that intercepts 'use' and 'env activate' commands
    pvm() {
        local pvm_exec="$(_pvm_executable)"
        if [ $? -ne 0 ]; then
            return 1
        fi

        local command="$1"
        if [ "$command" = "use" ]; then
            # Handle 'pvm use' with shell integration
            shift
            local version="$1"
            if [ -z "$version" ]; then
                echo "Usage: pvm use <version>"
                return 1
            fi
            # Run sh-use in a subshell, capture output and exit status.
            # Pass PVM_SHELL inline so only this subprocess sees it.
            local sh_use_out
            sh_use_out=$(PVM_SHELL="$_PVM_SHELL_TYPE" "$pvm_exec" sh-use "$version")
            local sh_use_rc=$?
            if [ "$sh_use_rc" -ne 0 ]; then
                return "$sh_use_rc"
            fi
            eval "$sh_use_out"
            # sh-use exports PVM_PERL_VERSION but does not rewrite PATH.
            _pvm_update_perl_path
        elif [ "$command" = "env" ] && [ "$2" = "activate" ]; then
            # Handle 'pvm env activate' with shell integration
            shift 2 # Remove 'env' and 'activate'
            local env_name="$1"
            if [ -z "$env_name" ]; then
                echo "Usage: pvm env activate <name>"
                return 1
            fi
            local env_out
            env_out=$(PVM_SHELL="$_PVM_SHELL_TYPE" "$pvm_exec" sh-env-activate "$env_name")
            local env_rc=$?
            if [ "$env_rc" -ne 0 ]; then
                return "$env_rc"
            fi
            eval "$env_out"
        else
            # Delegate all other commands to the pvm binary.
            # Use `command` to avoid potential shell function recursion.
            PVM_SHELL="$_PVM_SHELL_TYPE" command "$pvm_exec" "$@"
        fi
    }


    # Function to run custom commands upon directory change
    pvm_cd() {
        \cd "$@" || return $?

        # Update PATH to reflect current directory's Perl version
        _pvm_update_perl_path

        # Show current Perl version after directory change (if enabled in config)
        local pvm_exec="$(_pvm_executable)"
        if [ $? -eq 0 ]; then
            # Check if alerts should be shown
            if PVM_SHELL="$_PVM_SHELL_TYPE" "$pvm_exec" show-alerts 2>/dev/null; then
                local current_info="$(PVM_SHELL="$_PVM_SHELL_TYPE" "$pvm_exec" current 2>/dev/null)"
                if [ -n "$current_info" ]; then
                    echo "Using $current_info"
                fi
            fi
        fi
    }

    # Set up cd override (if supported)
    if [ -n "${ZSH_VERSION-}" ]; then
        # For Zsh, use chpwd hook
        pvm_chpwd() {
            # Update PATH to reflect current directory's Perl version
            _pvm_update_perl_path

            # Show current Perl version after directory change (if enabled in config)
            local pvm_exec="$(_pvm_executable)"
            if [ $? -eq 0 ]; then
                # Check if alerts should be shown
                if PVM_SHELL="$_PVM_SHELL_TYPE" "$pvm_exec" show-alerts 2>/dev/null; then
                    local current_info="$(PVM_SHELL="$_PVM_SHELL_TYPE" "$pvm_exec" current 2>/dev/null)"
                    if [ -n "$current_info" ]; then
                        echo "Using $current_info"
                    fi
                fi
            fi
        }

        autoload -Uz add-zsh-hook
        add-zsh-hook chpwd pvm_chpwd
    else
        # For Bash, override cd
        alias cd="pvm_cd"
    fi
}

# Initialize PVM
pvm_init

# Set up completion (skip during tests)
if [ "${PVM_SKIP_NETWORK_CALLS-}" != "1" ]; then
    if [ -n "${ZSH_VERSION-}" ]; then
        eval "$(PVM_SHELL="$_PVM_SHELL_TYPE" "$(_pvm_executable)" completion zsh 2>/dev/null || true)"
    else
        eval "$(PVM_SHELL="$_PVM_SHELL_TYPE" "$(_pvm_executable)" completion bash 2>/dev/null || true)"
    fi
fi

# Output fortune quote
echo "{{.FortuneQuote}}"
