#!/usr/bin/env fish
# PVM Shell Integration for Fish
# Generated by PVM - DO NOT EDIT

# Record the shell that sourced this integration, so the pvm() function can
# tell pvm the calling shell's identity when invoking it. Do NOT export —
# sub-shells of a different family (bash -c from fish, etc.) must not
# inherit a stale value; they detect their own shell via $SHELL or their
# own sourced template.
set -g _pvm_shell_type fish

# Path to PVM executable (fallback)
set PVM_EXEC "{{.PVMPath}}"

# XDG directories for the two-tier PATH system
set XDG_BIN_HOME (if test -n "$XDG_BIN_HOME"; echo "$XDG_BIN_HOME"; else; echo "$HOME/.local/bin"; end)
set XDG_DATA_HOME (if test -n "$XDG_DATA_HOME"; echo "$XDG_DATA_HOME"; else; echo "$HOME/.local/share"; end)

# Function to find PVM executable dynamically
function _pvm_find_executable
    # First, try to find pvm in PATH
    if command -v pvm >/dev/null 2>&1
        command -v pvm
        return 0
    end

    # Fallback to the path that was used during generation
    if test -x "$PVM_EXEC"
        echo "$PVM_EXEC"
        return 0
    end

    # If all else fails, show an error
    echo "Error: PVM executable not found. Please ensure PVM is installed and in PATH." >&2
    return 1
end

# Function to get PVM executable path
function _pvm_executable
    if test -z "$PVM_EXEC_CACHE"
        set -g PVM_EXEC_CACHE (_pvm_find_executable)
        if test $status -ne 0
            return 1
        end
    end
    echo "$PVM_EXEC_CACHE"
end

# Function to update PATH with current Perl version
function _pvm_update_perl_path
    set pvm_exec (_pvm_executable)
    if test $status -ne 0
        return 1
    end

    # FIRST: Clean up existing pvm perl paths from PATH, preserve everything else
    set clean_path
    set found_xdg_bin_home false

    for path_entry in $PATH
        # Track if we found XDG_BIN_HOME in existing PATH
        if test "$path_entry" = "$XDG_BIN_HOME"
            set found_xdg_bin_home true
        end

        # Skip existing pvm perl paths - we'll replace them
        if string match -q "*/pvm/versions/*/bin" "$path_entry"
            continue
        end

        # Keep all other paths (including XDG_BIN_HOME)
        set clean_path $clean_path $path_entry
    end

    # SECOND: Ensure XDG_BIN_HOME is at the front of clean_path
    if test "$found_xdg_bin_home" = false
        set clean_path $XDG_BIN_HOME $clean_path
    end

    # THIRD: Set clean PATH temporarily so PVM resolver doesn't see old perl
    set -gx PATH $clean_path

    # FOURTH: Now ask PVM what version should be active (in clean environment).
    # Use a begin…end block with `set -lx` to export PVM_SHELL only for the
    # subprocess; a bare `set -gx` would leak to all future subprocesses.
    set current_version (begin; set -lx PVM_SHELL $_pvm_shell_type; "$pvm_exec" current --bare 2>/dev/null; end)

    # Add the current version's bin path if we have a version
    if test -n "$current_version" -a "$current_version" != "system"
        set new_perl_bin "$XDG_DATA_HOME/pvm/versions/$current_version/bin"
        if test -d "$new_perl_bin"
            set -gx PATH $new_perl_bin $clean_path
        else
            set -gx PATH $clean_path
        end
    else
        # No current version or system version - just use cleaned path
        set -gx PATH $clean_path
    end

    # Handle library environment if PVM_PERL_LIBRARY is set
    if test -n "$PVM_PERL_LIBRARY"
        set -l library_env_dir "$XDG_DATA_HOME/pvm/environments/$PVM_PERL_LIBRARY"
        if test -d "$library_env_dir"
            set -l library_lib_dir "$library_env_dir/lib/perl5"
            if test -d "$library_lib_dir"
                if set -q PERL5LIB
                    set -gx PERL5LIB "$library_lib_dir:$PERL5LIB"
                else
                    set -gx PERL5LIB "$library_lib_dir"
                end
            end
            set -l library_bin_dir "$library_env_dir/bin"
            if test -d "$library_bin_dir"
                set -gx PATH $library_bin_dir $PATH
            end
        end
    else
        # Clear library-specific PERL5LIB entries when no library is active.
        if set -q PERL5LIB
            set -l cleaned
            for lib_entry in (string split : -- "$PERL5LIB")
                if not string match -q "*/pvm/environments/*/lib/perl5" "$lib_entry"
                    set cleaned $cleaned $lib_entry
                end
            end
            if test (count $cleaned) -gt 0
                set -gx PERL5LIB (string join : -- $cleaned)
            else
                set -e PERL5LIB
            end
        end
    end
end

# Function to initialize PVM
function pvm_init
    # Add XDG_BIN_HOME to PATH (for pvm tool install shims) if not already there
    if not contains "$XDG_BIN_HOME" $PATH
        set -gx PATH $XDG_BIN_HOME $PATH
    end

    # Add current Perl bin directory to PATH (for perl, cpan, prove, etc.)
    _pvm_update_perl_path

    # Define main pvm function that intercepts 'use' and 'env activate' commands
    function pvm
        set pvm_exec (_pvm_executable)
        if test $status -ne 0
            return 1
        end

        set command $argv[1]
        if test "$command" = "use"
            # Handle 'pvm use' with shell integration.
            # NB: fish has a read-only $version referring to its own version,
            # so name the local differently.
            set -l requested_version $argv[2]
            if test -z "$requested_version"
                echo "Usage: pvm use <version>"
                return 1
            end
            # Run sh-use and capture output; pipe into `source` because fish's
            # "$list" expansion joins lines with spaces and collapses the
            # shell script. Scope PVM_SHELL to just this subprocess via a
            # begin…end block with `set -lx`.
            # $pipestatus[1] is the sh-use exit code; $status would be the
            # `source` exit code (always 0 for empty input on failure).
            begin
                set -lx PVM_SHELL $_pvm_shell_type
                "$pvm_exec" sh-use "$requested_version" | source
                set -l sh_use_rc $pipestatus[1]
                if test $sh_use_rc -ne 0
                    return $sh_use_rc
                end
            end
            # sh-use exports PVM_PERL_VERSION but does not rewrite PATH.
            _pvm_update_perl_path
        else if test "$command" = "env" -a "$argv[2]" = "activate"
            # Handle 'pvm env activate' with shell integration
            set env_name $argv[3]
            if test -z "$env_name"
                echo "Usage: pvm env activate <name>"
                return 1
            end
            begin
                set -lx PVM_SHELL $_pvm_shell_type
                "$pvm_exec" sh-env-activate "$env_name" | source
                set -l env_rc $pipestatus[1]
                if test $env_rc -ne 0
                    return $env_rc
                end
            end
        else
            # Delegate all other commands to the pvm binary
            begin
                set -lx PVM_SHELL $_pvm_shell_type
                command "$pvm_exec" $argv
            end
        end
    end

    # Function to run when directory changes
    function pvm_on_pwd_change --on-variable PWD
        # Update PATH to reflect current directory's Perl version
        _pvm_update_perl_path

        # Show current Perl version after directory change (if enabled in config)
        set pvm_exec (_pvm_executable)
        if test $status -eq 0
            # Check if alerts should be shown
            if begin; set -lx PVM_SHELL $_pvm_shell_type; "$pvm_exec" show-alerts 2>/dev/null; end
                set current_info (begin; set -lx PVM_SHELL $_pvm_shell_type; "$pvm_exec" current 2>/dev/null; end)
                if test -n "$current_info"
                    echo "Using $current_info"
                end
            end
        end
    end

    # Check current directory immediately
    pvm_on_pwd_change
end

# Initialize PVM
pvm_init

# Set up completion (skip during tests).
# Use `| source` rather than `eval "$var"` because fish's "$list" expansion
# joins lines with spaces, which collapses the completion script into one
# long comment (the first line is `# PVM Fish Completion`).
if test "$PVM_SKIP_NETWORK_CALLS" != "1"
    set -l _pvm_exec_path (_pvm_executable)
    if test -n "$_pvm_exec_path"
        begin
            set -lx PVM_SHELL $_pvm_shell_type
            "$_pvm_exec_path" completion fish 2>/dev/null | source
        end
    end
    set -e _pvm_exec_path
end

# Output fortune quote
echo "{{.FortuneQuote}}"
