# ABOUTME: PVM Shell Integration for PowerShell
# ABOUTME: Template file - Generated by PVM init

# Function to find PVM executable dynamically
function _pvm_find_executable {
    # First, try to find pvm in PATH
    $pvmInPath = Get-Command pvm -ErrorAction SilentlyContinue
    if ($pvmInPath) {
        return $pvmInPath.Source
    }

    # Fallback to the path that was used during generation
    $fallback = "{{.PVMPath}}"
    if (Test-Path $fallback) {
        return $fallback
    }

    # If all else fails, show an error
    Write-Error "Error: PVM executable not found. Please ensure PVM is installed and in PATH."
    return $null
}

# Function to get PVM executable path (cached)
function _pvm_executable {
    if (-not $script:PVM_EXEC_CACHE) {
        $script:PVM_EXEC_CACHE = _pvm_find_executable
        if (-not $script:PVM_EXEC_CACHE) {
            return $null
        }
    }
    return $script:PVM_EXEC_CACHE
}

# Function to update PATH with current Perl version
function _pvm_update_perl_path {
    $pvmExec = _pvm_executable
    if (-not $pvmExec) {
        return
    }

    # Determine the data directory (Windows uses LOCALAPPDATA, respects XDG_DATA_HOME if set)
    if ($env:XDG_DATA_HOME) {
        $pvmDataDir = $env:XDG_DATA_HOME
    } else {
        $pvmDataDir = Join-Path $env:LOCALAPPDATA "pvm"
    }

    # FIRST: Clean up existing pvm perl paths from PATH
    $pathSeparator = ";"
    $pathEntries = $env:PATH -split [regex]::Escape($pathSeparator)
    $cleanPath = @()
    $foundLocalBin = $false

    # Determine the local bin directory (where pvm tool shims live)
    if ($env:XDG_BIN_HOME) {
        $localBinDir = $env:XDG_BIN_HOME
    } else {
        $localBinDir = Join-Path $env:LOCALAPPDATA "pvm\bin"
    }

    foreach ($pathEntry in $pathEntries) {
        if ([string]::IsNullOrEmpty($pathEntry)) {
            continue
        }

        # Track if we found the local bin directory
        if ($pathEntry -eq $localBinDir) {
            $foundLocalBin = $true
        }

        # Skip existing pvm perl version paths - we'll replace them
        if ($pathEntry -match [regex]::Escape("pvm\versions") + ".*\\bin$") {
            continue
        }

        $cleanPath += $pathEntry
    }

    # SECOND: Ensure local bin dir is at the front of clean path
    if (-not $foundLocalBin) {
        $cleanPath = @($localBinDir) + $cleanPath
    }

    # THIRD: Set clean PATH temporarily so PVM resolver doesn't see old perl
    $env:PATH = $cleanPath -join $pathSeparator

    # FOURTH: Now ask PVM what version should be active (in clean environment)
    $currentVersion = & $pvmExec current --bare 2>$null

    # Add the current version's bin path if we have a version
    if ($currentVersion -and $currentVersion -ne "system") {
        $newPerlBin = Join-Path $pvmDataDir "versions\$currentVersion\bin"
        if (Test-Path $newPerlBin) {
            $env:PATH = $newPerlBin + $pathSeparator + $env:PATH
        }
    }

    # Handle library environment if PVM_PERL_LIBRARY is set
    if ($env:PVM_PERL_LIBRARY) {
        $libraryEnvDir = Join-Path $pvmDataDir "environments\$($env:PVM_PERL_LIBRARY)"
        if (Test-Path $libraryEnvDir) {
            # Add library environment's lib/perl5 to PERL5LIB
            $libraryLibDir = Join-Path $libraryEnvDir "lib\perl5"
            if (Test-Path $libraryLibDir) {
                if ($env:PERL5LIB) {
                    $env:PERL5LIB = $libraryLibDir + $pathSeparator + $env:PERL5LIB
                } else {
                    $env:PERL5LIB = $libraryLibDir
                }
            }

            # Add library environment's bin to PATH
            $libraryBinDir = Join-Path $libraryEnvDir "bin"
            if (Test-Path $libraryBinDir) {
                $env:PATH = $libraryBinDir + $pathSeparator + $env:PATH
            }
        }
    } else {
        # Clear library-specific PERL5LIB entries when no library is active
        if ($env:PERL5LIB) {
            $perl5libEntries = $env:PERL5LIB -split [regex]::Escape($pathSeparator)
            $cleanPerl5Lib = @()
            foreach ($libEntry in $perl5libEntries) {
                # Skip PVM environment paths
                if ($libEntry -match [regex]::Escape("pvm\environments") + ".*\\lib\\perl5$") {
                    continue
                }
                $cleanPerl5Lib += $libEntry
            }
            $env:PERL5LIB = $cleanPerl5Lib -join $pathSeparator
        }
    }
}

# Main pvm function that intercepts 'use' and 'env activate' commands
function pvm {
    $pvmExec = _pvm_executable
    if (-not $pvmExec) {
        return 1
    }

    $command = $args[0]

    if ($command -eq "use") {
        # Handle 'pvm use' with shell integration
        $version = $args[1]
        if (-not $version) {
            Write-Host "Usage: pvm use <version>"
            return 1
        }
        # Use the sh-use command to generate shell code and invoke it
        $shellCode = & $pvmExec sh-use $version 2>&1
        if ($LASTEXITCODE -eq 0) {
            Invoke-Expression $shellCode
        } else {
            Write-Error $shellCode
            return $LASTEXITCODE
        }
    } elseif ($command -eq "env" -and $args[1] -eq "activate") {
        # Handle 'pvm env activate' with shell integration
        $envName = $args[2]
        if (-not $envName) {
            Write-Host "Usage: pvm env activate <name>"
            return 1
        }
        # Use the sh-env-activate command to generate shell code and invoke it
        $shellCode = & $pvmExec sh-env-activate $envName 2>&1
        if ($LASTEXITCODE -eq 0) {
            Invoke-Expression $shellCode
        } else {
            Write-Error $shellCode
            return $LASTEXITCODE
        }
    } else {
        # Delegate all other commands to the pvm binary
        & $pvmExec @args
    }
}

# Register directory change hook to update PATH when changing directories
function _pvm_on_location_change {
    _pvm_update_perl_path

    $pvmExec = _pvm_executable
    if ($pvmExec) {
        # Check if alerts should be shown
        $showAlerts = & $pvmExec show-alerts 2>$null
        if ($LASTEXITCODE -eq 0) {
            $currentInfo = & $pvmExec current 2>$null
            if ($currentInfo) {
                Write-Host "Using $currentInfo"
            }
        }
    }
}

# Initialize PVM - update PATH for current directory
_pvm_update_perl_path

# Hook into the prompt to detect directory changes
$script:PVM_LAST_DIR = $PWD.Path
$originalPrompt = $function:prompt
function prompt {
    $currentDir = $PWD.Path
    if ($currentDir -ne $script:PVM_LAST_DIR) {
        $script:PVM_LAST_DIR = $currentDir
        _pvm_on_location_change
    }
    if ($originalPrompt) {
        & $originalPrompt
    } else {
        "PS $($PWD.Path)> "
    }
}

# Set up completion (skip during tests)
if ($env:PVM_SKIP_NETWORK_CALLS -ne "1") {
    $pvmExec = _pvm_executable
    if ($pvmExec) {
        & $pvmExec completion powershell 2>$null | Invoke-Expression
    }
}

# Output fortune quote
Write-Host "{{.FortuneQuote}}"
