#!/usr/bin/env fish
# PVM Shell Integration for Fish
# Generated by PVM - DO NOT EDIT

# Path to PVM executable (fallback)
set PVM_EXEC "{{.PVMPath}}"

# Shims directory
set PVM_SHIMS_DIR "{{.ShimsDir}}"

# Function to initialize PVM
function pvm_init
    # Add shims directory to PATH if not already there
    if not contains $PVM_SHIMS_DIR $PATH
        set -gx PATH $PVM_SHIMS_DIR $PATH
    end

    # Define shell functions for version switching
    function pvm_use
        set version $argv[1]
        if test -z "$version"
            echo "Usage: pvm use <version>"
            return 1
        end

        # Set version for current shell
        set -gx PVM_PERL_VERSION $version
        echo "Using Perl $version"
    end

    # Create shell aliases
    alias pvm-use="pvm_use"
    alias pvm-local="$PVM_EXEC local"
    alias pvm-global="$PVM_EXEC global"

    # Function to run when directory changes
    function pvm_on_pwd_change --on-variable PWD
        if test -f "$PWD/.perl-version"
            set version (cat "$PWD/.perl-version")
            if test -n "$version"
                pvm_use $version
            end
        end
    end

    # Check current directory immediately
    pvm_on_pwd_change
end

# Initialize PVM
pvm_init

# Output message
echo "PVM environment initialized"
