@echo off
REM ABOUTME: PVM Shell Integration for CMD (Windows Command Prompt)
REM ABOUTME: Template file - Generated by PVM init

REM Find PVM executable
set "PVM_EXEC="
where pvm >nul 2>&1
if not errorlevel 1 (
    for /f "delims=" %%i in ('where pvm') do set "PVM_EXEC=%%i"
)
if not defined PVM_EXEC (
    if exist "{{.PVMPath}}" set "PVM_EXEC={{.PVMPath}}"
)
if not defined PVM_EXEC (
    echo PVM executable not found. Ensure PVM is installed and in PATH.
    goto :pvm_init_done
)

REM Determine the PVM data directory
if defined XDG_DATA_HOME (
    set "PVM_DATA_DIR=%XDG_DATA_HOME%\pvm"
) else if defined LOCALAPPDATA (
    set "PVM_DATA_DIR=%LOCALAPPDATA%\pvm"
) else (
    set "PVM_DATA_DIR=%USERPROFILE%\.local\share\pvm"
)

REM Get current Perl version from PVM
set "PVM_CURRENT="
for /f "delims=" %%v in ('"%PVM_EXEC%" current --bare 2^>nul') do set "PVM_CURRENT=%%v"
if not defined PVM_CURRENT goto :pvm_show_fortune
if "%PVM_CURRENT%"=="system" goto :pvm_show_fortune

REM Add version bin directory to PATH
set "PVM_PERL_BIN=%PVM_DATA_DIR%\versions\%PVM_CURRENT%\bin"
if exist "%PVM_PERL_BIN%" set "PATH=%PVM_PERL_BIN%;%PATH%"

REM Add Strawberry Perl toolchain to PATH if present (for gcc/gmake)
set "PVM_TOOL_BIN=%PVM_DATA_DIR%\versions\%PVM_CURRENT%\c\bin"
if exist "%PVM_TOOL_BIN%" set "PATH=%PVM_TOOL_BIN%;%PATH%"

:pvm_show_fortune
echo {{.FortuneQuote}}

REM Clean up temporary variables
set "PVM_EXEC="
set "PVM_DATA_DIR="
set "PVM_CURRENT="
set "PVM_PERL_BIN="
set "PVM_TOOL_BIN="

:pvm_init_done
