// ABOUTME: Integration tests for PM snapshot installation functionality
// ABOUTME: Tests cpanfile.snapshot installation workflow and error handling

package pm

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"tamarou.com/pvm/internal/project"
)

// mockTestSnapshot creates a test snapshot in Carton format
func createTestSnapshot(t *testing.T, dir string) {
	snapshotContent := `# carton snapshot format v1.0
# Generated by PVM for testing
DISTRIBUTIONS
  Test-Simple-1.302195
    pathname: E/EX/EXODIST/Test-Simple-1.302195.tar.gz
    provides:
      Test::More 1.302195
      Test::Simple 1.302195
    requirements:
      Scalar::Util 0

  Moose-2.2206
    pathname: E/ET/ETHER/Moose-2.2206.tar.gz
    provides:
      Moose 2.2206
      Moose::Role 2.2206
    requirements:
      Class::MOP 2.2206
      Data::OptList 0.110

  Class-MOP-2.2206
    pathname: E/ET/ETHER/Class-MOP-2.2206.tar.gz
    provides:
      Class::MOP 2.2206
    requirements:
`

	snapshotPath := filepath.Join(dir, "cpanfile.snapshot")
	err := os.WriteFile(snapshotPath, []byte(snapshotContent), 0644)
	if err != nil {
		t.Fatalf("Failed to create test snapshot: %v", err)
	}
}

// TestInstallFromSnapshot_NoSnapshot tests error handling when snapshot is missing
func TestInstallFromSnapshot_NoSnapshot(t *testing.T) {
	tempDir := t.TempDir()

	projectCtx := &project.ProjectContext{
		IsProject: true,
		RootDir:   tempDir,
	}

	cmd := &cobra.Command{}
	err := installFromSnapshot(cmd, projectCtx, false)

	if err == nil {
		t.Error("Expected error when snapshot is missing")
	}

	if !strings.Contains(err.Error(), "cpanfile.snapshot not found") {
		t.Errorf("Expected error about missing snapshot, got: %v", err)
	}
}

// TestInstallFromSnapshot_ParseSnapshot tests snapshot parsing
func TestInstallFromSnapshot_ParseSnapshot(t *testing.T) {
	tempDir := t.TempDir()
	createTestSnapshot(t, tempDir)

	// Create a mock cpanfile for the manager
	cpanfilePath := filepath.Join(tempDir, "cpanfile")
	err := os.WriteFile(cpanfilePath, []byte("# test cpanfile\n"), 0644)
	if err != nil {
		t.Fatalf("Failed to create test cpanfile: %v", err)
	}

	// Test that we can read and parse the snapshot
	manager := NewCpanfileManager(cpanfilePath)
	snapshot, err := manager.ReadSnapshot()
	if err != nil {
		t.Fatalf("Failed to read test snapshot: %v", err)
	}

	// Verify snapshot content
	if len(snapshot.Distributions) != 3 {
		t.Errorf("Expected 3 distributions, got %d", len(snapshot.Distributions))
	}

	// Check specific distributions
	testSimple, exists := snapshot.Distributions["Test-Simple-1.302195"]
	if !exists {
		t.Error("Expected Test-Simple-1.302195 distribution")
	} else {
		if len(testSimple.Provides) != 2 {
			t.Errorf("Expected Test-Simple to provide 2 modules, got %d", len(testSimple.Provides))
		}
		if testSimple.Provides["Test::More"] != "1.302195" {
			t.Errorf("Expected Test::More version 1.302195, got %s", testSimple.Provides["Test::More"])
		}
	}
}

// TestTopologicalSort tests the dependency ordering algorithm
func TestTopologicalSort(t *testing.T) {
	tests := []struct {
		name         string
		modules      []string
		dependencies map[string][]string
		expected     []string
	}{
		{
			name:    "no dependencies",
			modules: []string{"A", "B", "C"},
			dependencies: map[string][]string{
				"A": {},
				"B": {},
				"C": {},
			},
			expected: []string{"A", "B", "C"}, // order doesn't matter, just check length
		},
		{
			name:    "simple chain",
			modules: []string{"A", "B", "C"},
			dependencies: map[string][]string{
				"A": {},
				"B": {"A"},
				"C": {"B"},
			},
			// A should come before B, B should come before C
		},
		{
			name:    "multiple dependencies",
			modules: []string{"A", "B", "C", "D"},
			dependencies: map[string][]string{
				"A": {},
				"B": {},
				"C": {"A", "B"},
				"D": {"C"},
			},
			// A and B can come in any order, but both before C, and C before D
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := topologicalSort(tt.modules, tt.dependencies)

			// Check that all modules are present
			if len(result) != len(tt.modules) {
				t.Errorf("Expected %d modules, got %d", len(tt.modules), len(result))
			}

			// Check that dependencies are respected
			positions := make(map[string]int)
			for i, module := range result {
				positions[module] = i
			}

			for module, deps := range tt.dependencies {
				modulePos, exists := positions[module]
				if !exists {
					t.Errorf("Module %s not found in result", module)
					continue
				}

				for _, dep := range deps {
					depPos, exists := positions[dep]
					if !exists {
						t.Errorf("Dependency %s not found in result", dep)
						continue
					}

					if depPos >= modulePos {
						t.Errorf("Dependency %s (pos %d) should come before %s (pos %d)",
							dep, depPos, module, modulePos)
					}
				}
			}
		})
	}
}

// TestTopologicalSort_Circular tests handling of circular dependencies
func TestTopologicalSort_Circular(t *testing.T) {
	modules := []string{"A", "B", "C"}
	dependencies := map[string][]string{
		"A": {"C"},
		"B": {"A"},
		"C": {"B"},
	}

	result := topologicalSort(modules, dependencies)

	// With circular dependencies, the result should be shorter than input
	// (indicating that not all nodes could be processed)
	if len(result) == len(modules) {
		t.Error("Expected circular dependency detection to result in incomplete sort")
	}
}

// TestInstallFromSnapshot_ModuleExtraction tests module extraction from snapshot
func TestInstallFromSnapshot_ModuleExtraction(t *testing.T) {
	tempDir := t.TempDir()
	createTestSnapshot(t, tempDir)

	// Create cpanfile
	cpanfilePath := filepath.Join(tempDir, "cpanfile")
	err := os.WriteFile(cpanfilePath, []byte("# test cpanfile\n"), 0644)
	if err != nil {
		t.Fatalf("Failed to create test cpanfile: %v", err)
	}

	manager := NewCpanfileManager(cpanfilePath)
	snapshot, err := manager.ReadSnapshot()
	if err != nil {
		t.Fatalf("Failed to read snapshot: %v", err)
	}

	// Extract modules as the code would do
	var moduleSpecs []string
	moduleVersionMap := make(map[string]string)

	for _, entry := range snapshot.Distributions {
		for module, version := range entry.Provides {
			moduleSpecs = append(moduleSpecs, module)
			moduleVersionMap[module] = version
		}
	}

	// Verify expected modules were extracted
	expectedModules := map[string]string{
		"Test::More":   "1.302195",
		"Test::Simple": "1.302195",
		"Moose":        "2.2206",
		"Moose::Role":  "2.2206",
		"Class::MOP":   "2.2206",
	}

	if len(moduleSpecs) != len(expectedModules) {
		t.Errorf("Expected %d modules, got %d", len(expectedModules), len(moduleSpecs))
	}

	for expectedModule, expectedVersion := range expectedModules {
		actualVersion, exists := moduleVersionMap[expectedModule]
		if !exists {
			t.Errorf("Expected module %s not found", expectedModule)
		} else if actualVersion != expectedVersion {
			t.Errorf("Expected %s version %s, got %s", expectedModule, expectedVersion, actualVersion)
		}
	}
}

// TestInstallFromSnapshot_DependencyMapping tests dependency extraction
func TestInstallFromSnapshot_DependencyMapping(t *testing.T) {
	tempDir := t.TempDir()
	createTestSnapshot(t, tempDir)

	cpanfilePath := filepath.Join(tempDir, "cpanfile")
	err := os.WriteFile(cpanfilePath, []byte("# test cpanfile\n"), 0644)
	if err != nil {
		t.Fatalf("Failed to create test cpanfile: %v", err)
	}

	manager := NewCpanfileManager(cpanfilePath)
	snapshot, err := manager.ReadSnapshot()
	if err != nil {
		t.Fatalf("Failed to read snapshot: %v", err)
	}

	// Build dependency map as the code would do
	moduleVersionMap := make(map[string]string)
	for _, entry := range snapshot.Distributions {
		for module, version := range entry.Provides {
			moduleVersionMap[module] = version
		}
	}

	moduleDependencies := make(map[string][]string)
	for _, entry := range snapshot.Distributions {
		for module := range entry.Provides {
			var deps []string
			for dep := range entry.Requirements {
				if _, exists := moduleVersionMap[dep]; exists {
					deps = append(deps, dep)
				}
			}
			moduleDependencies[module] = deps
		}
	}

	// Verify some expected dependencies
	// Moose should depend on Class::MOP
	mooseDeps, exists := moduleDependencies["Moose"]
	if !exists {
		t.Error("Expected to find dependencies for Moose")
	} else {
		hasClassMOP := false
		for _, dep := range mooseDeps {
			if dep == "Class::MOP" {
				hasClassMOP = true
				break
			}
		}
		if !hasClassMOP {
			t.Error("Expected Moose to depend on Class::MOP")
		}
	}
}

// TestInstallFromSnapshot_ErrorRecovery tests error handling during installation
func TestInstallFromSnapshot_ErrorRecovery(t *testing.T) {
	// This test would require mocking the module installer
	// For now, just test that the function handles missing snapshot gracefully
	tempDir := t.TempDir()

	projectCtx := &project.ProjectContext{
		IsProject: true,
		RootDir:   tempDir,
	}

	cmd := &cobra.Command{}
	err := installFromSnapshot(cmd, projectCtx, true) // verbose mode

	if err == nil {
		t.Error("Expected error when no snapshot exists")
	}

	// Error message should contain helpful recovery information
	if !strings.Contains(err.Error(), "cpanfile.snapshot not found") {
		t.Errorf("Expected helpful error message, got: %v", err)
	}
}

// BenchmarkTopologicalSort benchmarks the dependency sorting algorithm
func BenchmarkTopologicalSort(b *testing.B) {
	// Create a moderate-sized dependency graph
	modules := make([]string, 100)
	dependencies := make(map[string][]string)

	for i := 0; i < 100; i++ {
		modules[i] = string(rune('A'+i%26)) + string(rune('0'+i/26))
		// Each module depends on the previous 3 modules (if they exist)
		var deps []string
		for j := max(0, i-3); j < i; j++ {
			deps = append(deps, modules[j])
		}
		dependencies[modules[i]] = deps
	}

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		topologicalSort(modules, dependencies)
	}
}

// TestInstallCommand_WithSnapshot tests that pvm module install uses snapshot by default
func TestInstallCommand_WithSnapshot(t *testing.T) {
	tempDir := t.TempDir()
	createTestSnapshot(t, tempDir)

	// Create cpanfile to make it a valid project
	cpanfilePath := filepath.Join(tempDir, "cpanfile")
	err := os.WriteFile(cpanfilePath, []byte("requires 'Test::More';\n"), 0644)
	if err != nil {
		t.Fatalf("Failed to create test cpanfile: %v", err)
	}

	// Change to test directory to simulate being in a project
	originalDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("Failed to get current directory: %v", err)
	}
	defer os.Chdir(originalDir)

	err = os.Chdir(tempDir)
	if err != nil {
		t.Fatalf("Failed to change to test directory: %v", err)
	}

	// Create install command
	cmd := newInstallCommand()

	// Set up command args to simulate `pvm module install` (no specific modules)
	cmd.SetArgs([]string{})

	// This test will fail during actual installation since we don't have real modules
	// But we can test that the snapshot detection logic runs by checking the error message
	err = cmd.Execute()

	// The error should be from the snapshot installation process, not from missing cpanfile
	if err != nil && !strings.Contains(err.Error(), "snapshot") {
		// If error doesn't mention snapshot, the detection logic might not be working
		t.Logf("Command error (expected during test): %v", err)
	}
}

// TestInstallCommand_IgnoreSnapshot tests the --ignore-snapshot flag
func TestInstallCommand_IgnoreSnapshot(t *testing.T) {
	tempDir := t.TempDir()
	createTestSnapshot(t, tempDir)

	// Create cpanfile
	cpanfilePath := filepath.Join(tempDir, "cpanfile")
	err := os.WriteFile(cpanfilePath, []byte("requires 'Test::More';\n"), 0644)
	if err != nil {
		t.Fatalf("Failed to create test cpanfile: %v", err)
	}

	// Change to test directory
	originalDir, err := os.Getwd()
	if err != nil {
		t.Fatalf("Failed to get current directory: %v", err)
	}
	defer os.Chdir(originalDir)

	err = os.Chdir(tempDir)
	if err != nil {
		t.Fatalf("Failed to change to test directory: %v", err)
	}

	// Create install command with --ignore-snapshot flag
	cmd := newInstallCommand()
	cmd.SetArgs([]string{"--ignore-snapshot"})

	// Execute command - it should bypass snapshot and use regular cpanfile installation
	err = cmd.Execute()

	// The error should be from regular installation process, not snapshot-related
	if err != nil {
		t.Logf("Command error (expected during test): %v", err)
		// Should not mention snapshot in error since we're ignoring it
		if strings.Contains(err.Error(), "Found cpanfile.snapshot") {
			t.Error("Command should not use snapshot when --ignore-snapshot is specified")
		}
	}
}

// TestSyncCommand_SmartDefaults tests the smart default behavior of sync command
func TestSyncCommand_SmartDefaults(t *testing.T) {
	t.Run("InstallFromSnapshot_WhenExists", func(t *testing.T) {
		tempDir := t.TempDir()
		createTestSnapshot(t, tempDir)
		
		// Create cpanfile
		cpanfilePath := filepath.Join(tempDir, "cpanfile")
		err := os.WriteFile(cpanfilePath, []byte("requires 'Test::More';\n"), 0644)
		if err != nil {
			t.Fatalf("Failed to create test cpanfile: %v", err)
		}
		
		// Change to test directory
		originalDir, err := os.Getwd()
		if err != nil {
			t.Fatalf("Failed to get current directory: %v", err)
		}
		defer os.Chdir(originalDir)
		
		err = os.Chdir(tempDir)
		if err != nil {
			t.Fatalf("Failed to change to test directory: %v", err)
		}
		
		// Create sync command with no flags - should detect snapshot and install from it
		cmd := newSyncCommand()
		cmd.SetArgs([]string{})
		
		err = cmd.Execute()
		// Expected to fail during actual installation but should attempt to install from snapshot
		if err != nil && !strings.Contains(err.Error(), "snapshot") {
			t.Logf("Command error (expected during test): %v", err)
		}
	})
	
	t.Run("GenerateSnapshot_WhenNotExists", func(t *testing.T) {
		tempDir := t.TempDir()
		
		// Create only cpanfile, no snapshot
		cpanfilePath := filepath.Join(tempDir, "cpanfile")
		err := os.WriteFile(cpanfilePath, []byte("requires 'Test::More';\n"), 0644)
		if err != nil {
			t.Fatalf("Failed to create test cpanfile: %v", err)
		}
		
		// Change to test directory
		originalDir, err := os.Getwd()
		if err != nil {
			t.Fatalf("Failed to get current directory: %v", err)
		}
		defer os.Chdir(originalDir)
		
		err = os.Chdir(tempDir)
		if err != nil {
			t.Fatalf("Failed to change to test directory: %v", err)
		}
		
		// Create sync command - should attempt to install then generate snapshot
		cmd := newSyncCommand()
		cmd.SetArgs([]string{})
		
		err = cmd.Execute()
		// Expected to fail during module installation but should attempt the workflow
		if err != nil {
			t.Logf("Command error (expected during test): %v", err)
		}
	})
	
	t.Run("ExplicitFlags", func(t *testing.T) {
		tempDir := t.TempDir()
		createTestSnapshot(t, tempDir)
		
		// Create cpanfile
		cpanfilePath := filepath.Join(tempDir, "cpanfile")
		err := os.WriteFile(cpanfilePath, []byte("requires 'Test::More';\n"), 0644)
		if err != nil {
			t.Fatalf("Failed to create test cpanfile: %v", err)
		}
		
		// Change to test directory
		originalDir, err := os.Getwd()
		if err != nil {
			t.Fatalf("Failed to get current directory: %v", err)
		}
		defer os.Chdir(originalDir)
		
		err = os.Chdir(tempDir)
		if err != nil {
			t.Fatalf("Failed to change to test directory: %v", err)
		}
		
		// Test --generate-only flag
		cmd := newSyncCommand()
		cmd.SetArgs([]string{"--generate-only"})
		
		err = cmd.Execute()
		// Should attempt to generate snapshot
		if err != nil {
			t.Logf("Command error with --generate-only (expected during test): %v", err)
		}
		
		// Test --install-only flag
		cmd = newSyncCommand()
		cmd.SetArgs([]string{"--install-only"})
		
		err = cmd.Execute()
		// Should attempt to install from snapshot
		if err != nil {
			t.Logf("Command error with --install-only (expected during test): %v", err)
		}
	})
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
