// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package scanner

import (
	"io"
	"sync"
)

// Ensure, that ScannerMock does implement Scanner.
// If this is not the case, regenerate this file with moq.
var _ Scanner = &ScannerMock{}

// ScannerMock is a mock implementation of Scanner.
//
//	func TestSomethingThatUsesScanner(t *testing.T) {
//
//		// make and configure a mocked Scanner
//		mockedScanner := &ScannerMock{
//			ScanFileFunc: func(path string) (TokenIterator, error) {
//				panic("mock out the ScanFile method")
//			},
//			ScanReaderFunc: func(reader io.Reader) (TokenIterator, error) {
//				panic("mock out the ScanReader method")
//			},
//			ScanStringFunc: func(content string) (TokenIterator, error) {
//				panic("mock out the ScanString method")
//			},
//		}
//
//		// use mockedScanner in code that requires Scanner
//		// and then make assertions.
//
//	}
type ScannerMock struct {
	// ScanFileFunc mocks the ScanFile method.
	ScanFileFunc func(path string) (TokenIterator, error)

	// ScanReaderFunc mocks the ScanReader method.
	ScanReaderFunc func(reader io.Reader) (TokenIterator, error)

	// ScanStringFunc mocks the ScanString method.
	ScanStringFunc func(content string) (TokenIterator, error)

	// calls tracks calls to the methods.
	calls struct {
		// ScanFile holds details about calls to the ScanFile method.
		ScanFile []struct {
			// Path is the path argument value.
			Path string
		}
		// ScanReader holds details about calls to the ScanReader method.
		ScanReader []struct {
			// Reader is the reader argument value.
			Reader io.Reader
		}
		// ScanString holds details about calls to the ScanString method.
		ScanString []struct {
			// Content is the content argument value.
			Content string
		}
	}
	lockScanFile   sync.RWMutex
	lockScanReader sync.RWMutex
	lockScanString sync.RWMutex
}

// ScanFile calls ScanFileFunc.
func (mock *ScannerMock) ScanFile(path string) (TokenIterator, error) {
	if mock.ScanFileFunc == nil {
		panic("ScannerMock.ScanFileFunc: method is nil but Scanner.ScanFile was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockScanFile.Lock()
	mock.calls.ScanFile = append(mock.calls.ScanFile, callInfo)
	mock.lockScanFile.Unlock()
	return mock.ScanFileFunc(path)
}

// ScanFileCalls gets all the calls that were made to ScanFile.
// Check the length with:
//
//	len(mockedScanner.ScanFileCalls())
func (mock *ScannerMock) ScanFileCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockScanFile.RLock()
	calls = mock.calls.ScanFile
	mock.lockScanFile.RUnlock()
	return calls
}

// ScanReader calls ScanReaderFunc.
func (mock *ScannerMock) ScanReader(reader io.Reader) (TokenIterator, error) {
	if mock.ScanReaderFunc == nil {
		panic("ScannerMock.ScanReaderFunc: method is nil but Scanner.ScanReader was just called")
	}
	callInfo := struct {
		Reader io.Reader
	}{
		Reader: reader,
	}
	mock.lockScanReader.Lock()
	mock.calls.ScanReader = append(mock.calls.ScanReader, callInfo)
	mock.lockScanReader.Unlock()
	return mock.ScanReaderFunc(reader)
}

// ScanReaderCalls gets all the calls that were made to ScanReader.
// Check the length with:
//
//	len(mockedScanner.ScanReaderCalls())
func (mock *ScannerMock) ScanReaderCalls() []struct {
	Reader io.Reader
} {
	var calls []struct {
		Reader io.Reader
	}
	mock.lockScanReader.RLock()
	calls = mock.calls.ScanReader
	mock.lockScanReader.RUnlock()
	return calls
}

// ScanString calls ScanStringFunc.
func (mock *ScannerMock) ScanString(content string) (TokenIterator, error) {
	if mock.ScanStringFunc == nil {
		panic("ScannerMock.ScanStringFunc: method is nil but Scanner.ScanString was just called")
	}
	callInfo := struct {
		Content string
	}{
		Content: content,
	}
	mock.lockScanString.Lock()
	mock.calls.ScanString = append(mock.calls.ScanString, callInfo)
	mock.lockScanString.Unlock()
	return mock.ScanStringFunc(content)
}

// ScanStringCalls gets all the calls that were made to ScanString.
// Check the length with:
//
//	len(mockedScanner.ScanStringCalls())
func (mock *ScannerMock) ScanStringCalls() []struct {
	Content string
} {
	var calls []struct {
		Content string
	}
	mock.lockScanString.RLock()
	calls = mock.calls.ScanString
	mock.lockScanString.RUnlock()
	return calls
}

// Ensure, that TokenMock does implement Token.
// If this is not the case, regenerate this file with moq.
var _ Token = &TokenMock{}

// TokenMock is a mock implementation of Token.
//
//	func TestSomethingThatUsesToken(t *testing.T) {
//
//		// make and configure a mocked Token
//		mockedToken := &TokenMock{
//			LengthFunc: func() int {
//				panic("mock out the Length method")
//			},
//			PositionFunc: func() Position {
//				panic("mock out the Position method")
//			},
//			TypeFunc: func() TokenType {
//				panic("mock out the Type method")
//			},
//			ValueFunc: func() string {
//				panic("mock out the Value method")
//			},
//		}
//
//		// use mockedToken in code that requires Token
//		// and then make assertions.
//
//	}
type TokenMock struct {
	// LengthFunc mocks the Length method.
	LengthFunc func() int

	// PositionFunc mocks the Position method.
	PositionFunc func() Position

	// TypeFunc mocks the Type method.
	TypeFunc func() TokenType

	// ValueFunc mocks the Value method.
	ValueFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Length holds details about calls to the Length method.
		Length []struct {
		}
		// Position holds details about calls to the Position method.
		Position []struct {
		}
		// Type holds details about calls to the Type method.
		Type []struct {
		}
		// Value holds details about calls to the Value method.
		Value []struct {
		}
	}
	lockLength   sync.RWMutex
	lockPosition sync.RWMutex
	lockType     sync.RWMutex
	lockValue    sync.RWMutex
}

// Length calls LengthFunc.
func (mock *TokenMock) Length() int {
	if mock.LengthFunc == nil {
		panic("TokenMock.LengthFunc: method is nil but Token.Length was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLength.Lock()
	mock.calls.Length = append(mock.calls.Length, callInfo)
	mock.lockLength.Unlock()
	return mock.LengthFunc()
}

// LengthCalls gets all the calls that were made to Length.
// Check the length with:
//
//	len(mockedToken.LengthCalls())
func (mock *TokenMock) LengthCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLength.RLock()
	calls = mock.calls.Length
	mock.lockLength.RUnlock()
	return calls
}

// Position calls PositionFunc.
func (mock *TokenMock) Position() Position {
	if mock.PositionFunc == nil {
		panic("TokenMock.PositionFunc: method is nil but Token.Position was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPosition.Lock()
	mock.calls.Position = append(mock.calls.Position, callInfo)
	mock.lockPosition.Unlock()
	return mock.PositionFunc()
}

// PositionCalls gets all the calls that were made to Position.
// Check the length with:
//
//	len(mockedToken.PositionCalls())
func (mock *TokenMock) PositionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPosition.RLock()
	calls = mock.calls.Position
	mock.lockPosition.RUnlock()
	return calls
}

// Type calls TypeFunc.
func (mock *TokenMock) Type() TokenType {
	if mock.TypeFunc == nil {
		panic("TokenMock.TypeFunc: method is nil but Token.Type was just called")
	}
	callInfo := struct {
	}{}
	mock.lockType.Lock()
	mock.calls.Type = append(mock.calls.Type, callInfo)
	mock.lockType.Unlock()
	return mock.TypeFunc()
}

// TypeCalls gets all the calls that were made to Type.
// Check the length with:
//
//	len(mockedToken.TypeCalls())
func (mock *TokenMock) TypeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockType.RLock()
	calls = mock.calls.Type
	mock.lockType.RUnlock()
	return calls
}

// Value calls ValueFunc.
func (mock *TokenMock) Value() string {
	if mock.ValueFunc == nil {
		panic("TokenMock.ValueFunc: method is nil but Token.Value was just called")
	}
	callInfo := struct {
	}{}
	mock.lockValue.Lock()
	mock.calls.Value = append(mock.calls.Value, callInfo)
	mock.lockValue.Unlock()
	return mock.ValueFunc()
}

// ValueCalls gets all the calls that were made to Value.
// Check the length with:
//
//	len(mockedToken.ValueCalls())
func (mock *TokenMock) ValueCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockValue.RLock()
	calls = mock.calls.Value
	mock.lockValue.RUnlock()
	return calls
}

// Ensure, that TokenIteratorMock does implement TokenIterator.
// If this is not the case, regenerate this file with moq.
var _ TokenIterator = &TokenIteratorMock{}

// TokenIteratorMock is a mock implementation of TokenIterator.
//
//	func TestSomethingThatUsesTokenIterator(t *testing.T) {
//
//		// make and configure a mocked TokenIterator
//		mockedTokenIterator := &TokenIteratorMock{
//			HasNextFunc: func() bool {
//				panic("mock out the HasNext method")
//			},
//			NextFunc: func() Token {
//				panic("mock out the Next method")
//			},
//			PeekFunc: func() Token {
//				panic("mock out the Peek method")
//			},
//			PositionFunc: func() int {
//				panic("mock out the Position method")
//			},
//			ResetFunc: func()  {
//				panic("mock out the Reset method")
//			},
//		}
//
//		// use mockedTokenIterator in code that requires TokenIterator
//		// and then make assertions.
//
//	}
type TokenIteratorMock struct {
	// HasNextFunc mocks the HasNext method.
	HasNextFunc func() bool

	// NextFunc mocks the Next method.
	NextFunc func() Token

	// PeekFunc mocks the Peek method.
	PeekFunc func() Token

	// PositionFunc mocks the Position method.
	PositionFunc func() int

	// ResetFunc mocks the Reset method.
	ResetFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// HasNext holds details about calls to the HasNext method.
		HasNext []struct {
		}
		// Next holds details about calls to the Next method.
		Next []struct {
		}
		// Peek holds details about calls to the Peek method.
		Peek []struct {
		}
		// Position holds details about calls to the Position method.
		Position []struct {
		}
		// Reset holds details about calls to the Reset method.
		Reset []struct {
		}
	}
	lockHasNext  sync.RWMutex
	lockNext     sync.RWMutex
	lockPeek     sync.RWMutex
	lockPosition sync.RWMutex
	lockReset    sync.RWMutex
}

// HasNext calls HasNextFunc.
func (mock *TokenIteratorMock) HasNext() bool {
	if mock.HasNextFunc == nil {
		panic("TokenIteratorMock.HasNextFunc: method is nil but TokenIterator.HasNext was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHasNext.Lock()
	mock.calls.HasNext = append(mock.calls.HasNext, callInfo)
	mock.lockHasNext.Unlock()
	return mock.HasNextFunc()
}

// HasNextCalls gets all the calls that were made to HasNext.
// Check the length with:
//
//	len(mockedTokenIterator.HasNextCalls())
func (mock *TokenIteratorMock) HasNextCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHasNext.RLock()
	calls = mock.calls.HasNext
	mock.lockHasNext.RUnlock()
	return calls
}

// Next calls NextFunc.
func (mock *TokenIteratorMock) Next() Token {
	if mock.NextFunc == nil {
		panic("TokenIteratorMock.NextFunc: method is nil but TokenIterator.Next was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc()
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedTokenIterator.NextCalls())
func (mock *TokenIteratorMock) NextCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}

// Peek calls PeekFunc.
func (mock *TokenIteratorMock) Peek() Token {
	if mock.PeekFunc == nil {
		panic("TokenIteratorMock.PeekFunc: method is nil but TokenIterator.Peek was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPeek.Lock()
	mock.calls.Peek = append(mock.calls.Peek, callInfo)
	mock.lockPeek.Unlock()
	return mock.PeekFunc()
}

// PeekCalls gets all the calls that were made to Peek.
// Check the length with:
//
//	len(mockedTokenIterator.PeekCalls())
func (mock *TokenIteratorMock) PeekCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPeek.RLock()
	calls = mock.calls.Peek
	mock.lockPeek.RUnlock()
	return calls
}

// Position calls PositionFunc.
func (mock *TokenIteratorMock) Position() int {
	if mock.PositionFunc == nil {
		panic("TokenIteratorMock.PositionFunc: method is nil but TokenIterator.Position was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPosition.Lock()
	mock.calls.Position = append(mock.calls.Position, callInfo)
	mock.lockPosition.Unlock()
	return mock.PositionFunc()
}

// PositionCalls gets all the calls that were made to Position.
// Check the length with:
//
//	len(mockedTokenIterator.PositionCalls())
func (mock *TokenIteratorMock) PositionCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPosition.RLock()
	calls = mock.calls.Position
	mock.lockPosition.RUnlock()
	return calls
}

// Reset calls ResetFunc.
func (mock *TokenIteratorMock) Reset() {
	if mock.ResetFunc == nil {
		panic("TokenIteratorMock.ResetFunc: method is nil but TokenIterator.Reset was just called")
	}
	callInfo := struct {
	}{}
	mock.lockReset.Lock()
	mock.calls.Reset = append(mock.calls.Reset, callInfo)
	mock.lockReset.Unlock()
	mock.ResetFunc()
}

// ResetCalls gets all the calls that were made to Reset.
// Check the length with:
//
//	len(mockedTokenIterator.ResetCalls())
func (mock *TokenIteratorMock) ResetCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockReset.RLock()
	calls = mock.calls.Reset
	mock.lockReset.RUnlock()
	return calls
}
