// Code generated by "stringer -type=TokenType -output=token_type_string.go"; DO NOT EDIT.

package scanner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-0]
	_ = x[TokenError-1]
	_ = x[TokenWhitespace-2]
	_ = x[TokenComment-3]
	_ = x[TokenNewline-4]
	_ = x[TokenString-5]
	_ = x[TokenNumber-6]
	_ = x[TokenIdentifier-7]
	_ = x[TokenVariable-8]
	_ = x[TokenArrayVariable-9]
	_ = x[TokenHashVariable-10]
	_ = x[TokenMy-11]
	_ = x[TokenOur-12]
	_ = x[TokenState-13]
	_ = x[TokenSub-14]
	_ = x[TokenMethod-15]
	_ = x[TokenField-16]
	_ = x[TokenTypeKeyword-17]
	_ = x[TokenUse-18]
	_ = x[TokenPackage-19]
	_ = x[TokenClass-20]
	_ = x[TokenAs-21]
	_ = x[TokenWhere-22]
	_ = x[TokenAssign-23]
	_ = x[TokenComma-24]
	_ = x[TokenSemicolon-25]
	_ = x[TokenLParen-26]
	_ = x[TokenRParen-27]
	_ = x[TokenLBrace-28]
	_ = x[TokenRBrace-29]
	_ = x[TokenLBracket-30]
	_ = x[TokenRBracket-31]
	_ = x[TokenArrow-32]
	_ = x[TokenPipe-33]
	_ = x[TokenAmpersand-34]
	_ = x[TokenExclamation-35]
	_ = x[TokenTypeAnnotation-36]
	_ = x[TokenTypeExpression-37]
	_ = x[TokenUnionOperator-38]
	_ = x[TokenIntersectionOperator-39]
	_ = x[TokenNegationOperator-40]
}

const _TokenType_name = "TokenEOFTokenErrorTokenWhitespaceTokenCommentTokenNewlineTokenStringTokenNumberTokenIdentifierTokenVariableTokenArrayVariableTokenHashVariableTokenMyTokenOurTokenStateTokenSubTokenMethodTokenFieldTokenTypeKeywordTokenUseTokenPackageTokenClassTokenAsTokenWhereTokenAssignTokenCommaTokenSemicolonTokenLParenTokenRParenTokenLBraceTokenRBraceTokenLBracketTokenRBracketTokenArrowTokenPipeTokenAmpersandTokenExclamationTokenTypeAnnotationTokenTypeExpressionTokenUnionOperatorTokenIntersectionOperatorTokenNegationOperator"

var _TokenType_index = [...]uint16{0, 8, 18, 33, 45, 57, 68, 79, 94, 107, 125, 142, 149, 157, 167, 175, 186, 196, 212, 220, 232, 242, 249, 259, 270, 280, 294, 305, 316, 327, 338, 351, 364, 374, 383, 397, 413, 432, 451, 469, 494, 515}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
