// Code generated by "stringer -type=TokenType -output=token_type_string.go"; DO NOT EDIT.

package scanner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-0]
	_ = x[TokenError-1]
	_ = x[TokenWhitespace-2]
	_ = x[TokenComment-3]
	_ = x[TokenNewline-4]
	_ = x[TokenString-5]
	_ = x[TokenNumber-6]
	_ = x[TokenIdentifier-7]
	_ = x[TokenVariable-8]
	_ = x[TokenArrayVariable-9]
	_ = x[TokenHashVariable-10]
	_ = x[TokenMy-11]
	_ = x[TokenOur-12]
	_ = x[TokenState-13]
	_ = x[TokenSub-14]
	_ = x[TokenMethod-15]
	_ = x[TokenField-16]
	_ = x[TokenTypeKeyword-17]
	_ = x[TokenUse-18]
	_ = x[TokenPackage-19]
	_ = x[TokenClass-20]
	_ = x[TokenAs-21]
	_ = x[TokenWhere-22]
	_ = x[TokenDoes-23]
	_ = x[TokenCan-24]
	_ = x[TokenRole-25]
	_ = x[TokenAssign-26]
	_ = x[TokenComma-27]
	_ = x[TokenSemicolon-28]
	_ = x[TokenLParen-29]
	_ = x[TokenRParen-30]
	_ = x[TokenLBrace-31]
	_ = x[TokenRBrace-32]
	_ = x[TokenLBracket-33]
	_ = x[TokenRBracket-34]
	_ = x[TokenArrow-35]
	_ = x[TokenPipe-36]
	_ = x[TokenAmpersand-37]
	_ = x[TokenExclamation-38]
	_ = x[TokenTypeAnnotation-39]
	_ = x[TokenTypeExpression-40]
	_ = x[TokenUnionOperator-41]
	_ = x[TokenIntersectionOperator-42]
	_ = x[TokenNegationOperator-43]
}

const _TokenType_name = "TokenEOFTokenErrorTokenWhitespaceTokenCommentTokenNewlineTokenStringTokenNumberTokenIdentifierTokenVariableTokenArrayVariableTokenHashVariableTokenMyTokenOurTokenStateTokenSubTokenMethodTokenFieldTokenTypeKeywordTokenUseTokenPackageTokenClassTokenAsTokenWhereTokenDoesTokenCanTokenRoleTokenAssignTokenCommaTokenSemicolonTokenLParenTokenRParenTokenLBraceTokenRBraceTokenLBracketTokenRBracketTokenArrowTokenPipeTokenAmpersandTokenExclamationTokenTypeAnnotationTokenTypeExpressionTokenUnionOperatorTokenIntersectionOperatorTokenNegationOperator"

var _TokenType_index = [...]uint16{0, 8, 18, 33, 45, 57, 68, 79, 94, 107, 125, 142, 149, 157, 167, 175, 186, 196, 212, 220, 232, 242, 249, 259, 268, 276, 285, 296, 306, 320, 331, 342, 353, 364, 377, 390, 400, 409, 423, 439, 458, 477, 495, 520, 541}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
