// Code generated by "stringer -type=TokenType -output=token_type_string.go"; DO NOT EDIT.

package scanner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-0]
	_ = x[TokenError-1]
	_ = x[TokenWhitespace-2]
	_ = x[TokenComment-3]
	_ = x[TokenNewline-4]
	_ = x[TokenString-5]
	_ = x[TokenNumber-6]
	_ = x[TokenIdentifier-7]
	_ = x[TokenVariable-8]
	_ = x[TokenArrayVariable-9]
	_ = x[TokenHashVariable-10]
	_ = x[TokenMy-11]
	_ = x[TokenOur-12]
	_ = x[TokenState-13]
	_ = x[TokenSub-14]
	_ = x[TokenMethod-15]
	_ = x[TokenField-16]
	_ = x[TokenTypeKeyword-17]
	_ = x[TokenUse-18]
	_ = x[TokenPackage-19]
	_ = x[TokenClass-20]
	_ = x[TokenAssign-21]
	_ = x[TokenComma-22]
	_ = x[TokenSemicolon-23]
	_ = x[TokenLParen-24]
	_ = x[TokenRParen-25]
	_ = x[TokenLBrace-26]
	_ = x[TokenRBrace-27]
	_ = x[TokenLBracket-28]
	_ = x[TokenRBracket-29]
	_ = x[TokenArrow-30]
	_ = x[TokenPipe-31]
	_ = x[TokenAmpersand-32]
	_ = x[TokenExclamation-33]
	_ = x[TokenTypeAnnotation-34]
	_ = x[TokenTypeExpression-35]
	_ = x[TokenUnionOperator-36]
	_ = x[TokenIntersectionOperator-37]
	_ = x[TokenNegationOperator-38]
}

const _TokenType_name = "TokenEOFTokenErrorTokenWhitespaceTokenCommentTokenNewlineTokenStringTokenNumberTokenIdentifierTokenVariableTokenArrayVariableTokenHashVariableTokenMyTokenOurTokenStateTokenSubTokenMethodTokenFieldTokenTypeKeywordTokenUseTokenPackageTokenClassTokenAssignTokenCommaTokenSemicolonTokenLParenTokenRParenTokenLBraceTokenRBraceTokenLBracketTokenRBracketTokenArrowTokenPipeTokenAmpersandTokenExclamationTokenTypeAnnotationTokenTypeExpressionTokenUnionOperatorTokenIntersectionOperatorTokenNegationOperator"

var _TokenType_index = [...]uint16{0, 8, 18, 33, 45, 57, 68, 79, 94, 107, 125, 142, 149, 157, 167, 175, 186, 196, 212, 220, 232, 242, 253, 263, 277, 288, 299, 310, 321, 334, 347, 357, 366, 380, 396, 415, 434, 452, 477, 498}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
