// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cpan

import (
	"context"
	"sync"
)

// Ensure, that ProviderMock does implement Provider.
// If this is not the case, regenerate this file with moq.
var _ Provider = &ProviderMock{}

// ProviderMock is a mock implementation of Provider.
//
//	func TestSomethingThatUsesProvider(t *testing.T) {
//
//		// make and configure a mocked Provider
//		mockedProvider := &ProviderMock{
//			BaseURLFunc: func() string {
//				panic("mock out the BaseURL method")
//			},
//			GetAuthorInfoFunc: func(ctx context.Context, authorID string) (map[string]interface{}, error) {
//				panic("mock out the GetAuthorInfo method")
//			},
//			GetDependenciesFunc: func(ctx context.Context, moduleName string) ([]*Dependency, error) {
//				panic("mock out the GetDependencies method")
//			},
//			GetModuleInfoFunc: func(ctx context.Context, moduleName string) (*ModuleInfo, error) {
//				panic("mock out the GetModuleInfo method")
//			},
//			GetModuleVersionsFunc: func(ctx context.Context, moduleName string) ([]string, error) {
//				panic("mock out the GetModuleVersions method")
//			},
//			IsCoreModuleFunc: func(ctx context.Context, moduleName string, perlVersion string) (bool, error) {
//				panic("mock out the IsCoreModule method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			SearchModulesFunc: func(ctx context.Context, query string, limit int) (*SearchResults, error) {
//				panic("mock out the SearchModules method")
//			},
//		}
//
//		// use mockedProvider in code that requires Provider
//		// and then make assertions.
//
//	}
type ProviderMock struct {
	// BaseURLFunc mocks the BaseURL method.
	BaseURLFunc func() string

	// GetAuthorInfoFunc mocks the GetAuthorInfo method.
	GetAuthorInfoFunc func(ctx context.Context, authorID string) (map[string]interface{}, error)

	// GetDependenciesFunc mocks the GetDependencies method.
	GetDependenciesFunc func(ctx context.Context, moduleName string) ([]*Dependency, error)

	// GetModuleInfoFunc mocks the GetModuleInfo method.
	GetModuleInfoFunc func(ctx context.Context, moduleName string) (*ModuleInfo, error)

	// GetModuleVersionsFunc mocks the GetModuleVersions method.
	GetModuleVersionsFunc func(ctx context.Context, moduleName string) ([]string, error)

	// IsCoreModuleFunc mocks the IsCoreModule method.
	IsCoreModuleFunc func(ctx context.Context, moduleName string, perlVersion string) (bool, error)

	// NameFunc mocks the Name method.
	NameFunc func() string

	// SearchModulesFunc mocks the SearchModules method.
	SearchModulesFunc func(ctx context.Context, query string, limit int) (*SearchResults, error)

	// calls tracks calls to the methods.
	calls struct {
		// BaseURL holds details about calls to the BaseURL method.
		BaseURL []struct {
		}
		// GetAuthorInfo holds details about calls to the GetAuthorInfo method.
		GetAuthorInfo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AuthorID is the authorID argument value.
			AuthorID string
		}
		// GetDependencies holds details about calls to the GetDependencies method.
		GetDependencies []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ModuleName is the moduleName argument value.
			ModuleName string
		}
		// GetModuleInfo holds details about calls to the GetModuleInfo method.
		GetModuleInfo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ModuleName is the moduleName argument value.
			ModuleName string
		}
		// GetModuleVersions holds details about calls to the GetModuleVersions method.
		GetModuleVersions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ModuleName is the moduleName argument value.
			ModuleName string
		}
		// IsCoreModule holds details about calls to the IsCoreModule method.
		IsCoreModule []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ModuleName is the moduleName argument value.
			ModuleName string
			// PerlVersion is the perlVersion argument value.
			PerlVersion string
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// SearchModules holds details about calls to the SearchModules method.
		SearchModules []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockBaseURL           sync.RWMutex
	lockGetAuthorInfo     sync.RWMutex
	lockGetDependencies   sync.RWMutex
	lockGetModuleInfo     sync.RWMutex
	lockGetModuleVersions sync.RWMutex
	lockIsCoreModule      sync.RWMutex
	lockName              sync.RWMutex
	lockSearchModules     sync.RWMutex
}

// BaseURL calls BaseURLFunc.
func (mock *ProviderMock) BaseURL() string {
	if mock.BaseURLFunc == nil {
		panic("ProviderMock.BaseURLFunc: method is nil but Provider.BaseURL was just called")
	}
	callInfo := struct {
	}{}
	mock.lockBaseURL.Lock()
	mock.calls.BaseURL = append(mock.calls.BaseURL, callInfo)
	mock.lockBaseURL.Unlock()
	return mock.BaseURLFunc()
}

// BaseURLCalls gets all the calls that were made to BaseURL.
// Check the length with:
//
//	len(mockedProvider.BaseURLCalls())
func (mock *ProviderMock) BaseURLCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockBaseURL.RLock()
	calls = mock.calls.BaseURL
	mock.lockBaseURL.RUnlock()
	return calls
}

// GetAuthorInfo calls GetAuthorInfoFunc.
func (mock *ProviderMock) GetAuthorInfo(ctx context.Context, authorID string) (map[string]interface{}, error) {
	if mock.GetAuthorInfoFunc == nil {
		panic("ProviderMock.GetAuthorInfoFunc: method is nil but Provider.GetAuthorInfo was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		AuthorID string
	}{
		Ctx:      ctx,
		AuthorID: authorID,
	}
	mock.lockGetAuthorInfo.Lock()
	mock.calls.GetAuthorInfo = append(mock.calls.GetAuthorInfo, callInfo)
	mock.lockGetAuthorInfo.Unlock()
	return mock.GetAuthorInfoFunc(ctx, authorID)
}

// GetAuthorInfoCalls gets all the calls that were made to GetAuthorInfo.
// Check the length with:
//
//	len(mockedProvider.GetAuthorInfoCalls())
func (mock *ProviderMock) GetAuthorInfoCalls() []struct {
	Ctx      context.Context
	AuthorID string
} {
	var calls []struct {
		Ctx      context.Context
		AuthorID string
	}
	mock.lockGetAuthorInfo.RLock()
	calls = mock.calls.GetAuthorInfo
	mock.lockGetAuthorInfo.RUnlock()
	return calls
}

// GetDependencies calls GetDependenciesFunc.
func (mock *ProviderMock) GetDependencies(ctx context.Context, moduleName string) ([]*Dependency, error) {
	if mock.GetDependenciesFunc == nil {
		panic("ProviderMock.GetDependenciesFunc: method is nil but Provider.GetDependencies was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ModuleName string
	}{
		Ctx:        ctx,
		ModuleName: moduleName,
	}
	mock.lockGetDependencies.Lock()
	mock.calls.GetDependencies = append(mock.calls.GetDependencies, callInfo)
	mock.lockGetDependencies.Unlock()
	return mock.GetDependenciesFunc(ctx, moduleName)
}

// GetDependenciesCalls gets all the calls that were made to GetDependencies.
// Check the length with:
//
//	len(mockedProvider.GetDependenciesCalls())
func (mock *ProviderMock) GetDependenciesCalls() []struct {
	Ctx        context.Context
	ModuleName string
} {
	var calls []struct {
		Ctx        context.Context
		ModuleName string
	}
	mock.lockGetDependencies.RLock()
	calls = mock.calls.GetDependencies
	mock.lockGetDependencies.RUnlock()
	return calls
}

// GetModuleInfo calls GetModuleInfoFunc.
func (mock *ProviderMock) GetModuleInfo(ctx context.Context, moduleName string) (*ModuleInfo, error) {
	if mock.GetModuleInfoFunc == nil {
		panic("ProviderMock.GetModuleInfoFunc: method is nil but Provider.GetModuleInfo was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ModuleName string
	}{
		Ctx:        ctx,
		ModuleName: moduleName,
	}
	mock.lockGetModuleInfo.Lock()
	mock.calls.GetModuleInfo = append(mock.calls.GetModuleInfo, callInfo)
	mock.lockGetModuleInfo.Unlock()
	return mock.GetModuleInfoFunc(ctx, moduleName)
}

// GetModuleInfoCalls gets all the calls that were made to GetModuleInfo.
// Check the length with:
//
//	len(mockedProvider.GetModuleInfoCalls())
func (mock *ProviderMock) GetModuleInfoCalls() []struct {
	Ctx        context.Context
	ModuleName string
} {
	var calls []struct {
		Ctx        context.Context
		ModuleName string
	}
	mock.lockGetModuleInfo.RLock()
	calls = mock.calls.GetModuleInfo
	mock.lockGetModuleInfo.RUnlock()
	return calls
}

// GetModuleVersions calls GetModuleVersionsFunc.
func (mock *ProviderMock) GetModuleVersions(ctx context.Context, moduleName string) ([]string, error) {
	if mock.GetModuleVersionsFunc == nil {
		panic("ProviderMock.GetModuleVersionsFunc: method is nil but Provider.GetModuleVersions was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		ModuleName string
	}{
		Ctx:        ctx,
		ModuleName: moduleName,
	}
	mock.lockGetModuleVersions.Lock()
	mock.calls.GetModuleVersions = append(mock.calls.GetModuleVersions, callInfo)
	mock.lockGetModuleVersions.Unlock()
	return mock.GetModuleVersionsFunc(ctx, moduleName)
}

// GetModuleVersionsCalls gets all the calls that were made to GetModuleVersions.
// Check the length with:
//
//	len(mockedProvider.GetModuleVersionsCalls())
func (mock *ProviderMock) GetModuleVersionsCalls() []struct {
	Ctx        context.Context
	ModuleName string
} {
	var calls []struct {
		Ctx        context.Context
		ModuleName string
	}
	mock.lockGetModuleVersions.RLock()
	calls = mock.calls.GetModuleVersions
	mock.lockGetModuleVersions.RUnlock()
	return calls
}

// IsCoreModule calls IsCoreModuleFunc.
func (mock *ProviderMock) IsCoreModule(ctx context.Context, moduleName string, perlVersion string) (bool, error) {
	if mock.IsCoreModuleFunc == nil {
		panic("ProviderMock.IsCoreModuleFunc: method is nil but Provider.IsCoreModule was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		ModuleName  string
		PerlVersion string
	}{
		Ctx:         ctx,
		ModuleName:  moduleName,
		PerlVersion: perlVersion,
	}
	mock.lockIsCoreModule.Lock()
	mock.calls.IsCoreModule = append(mock.calls.IsCoreModule, callInfo)
	mock.lockIsCoreModule.Unlock()
	return mock.IsCoreModuleFunc(ctx, moduleName, perlVersion)
}

// IsCoreModuleCalls gets all the calls that were made to IsCoreModule.
// Check the length with:
//
//	len(mockedProvider.IsCoreModuleCalls())
func (mock *ProviderMock) IsCoreModuleCalls() []struct {
	Ctx         context.Context
	ModuleName  string
	PerlVersion string
} {
	var calls []struct {
		Ctx         context.Context
		ModuleName  string
		PerlVersion string
	}
	mock.lockIsCoreModule.RLock()
	calls = mock.calls.IsCoreModule
	mock.lockIsCoreModule.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *ProviderMock) Name() string {
	if mock.NameFunc == nil {
		panic("ProviderMock.NameFunc: method is nil but Provider.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedProvider.NameCalls())
func (mock *ProviderMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// SearchModules calls SearchModulesFunc.
func (mock *ProviderMock) SearchModules(ctx context.Context, query string, limit int) (*SearchResults, error) {
	if mock.SearchModulesFunc == nil {
		panic("ProviderMock.SearchModulesFunc: method is nil but Provider.SearchModules was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
		Limit int
	}{
		Ctx:   ctx,
		Query: query,
		Limit: limit,
	}
	mock.lockSearchModules.Lock()
	mock.calls.SearchModules = append(mock.calls.SearchModules, callInfo)
	mock.lockSearchModules.Unlock()
	return mock.SearchModulesFunc(ctx, query, limit)
}

// SearchModulesCalls gets all the calls that were made to SearchModules.
// Check the length with:
//
//	len(mockedProvider.SearchModulesCalls())
func (mock *ProviderMock) SearchModulesCalls() []struct {
	Ctx   context.Context
	Query string
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Query string
		Limit int
	}
	mock.lockSearchModules.RLock()
	calls = mock.calls.SearchModules
	mock.lockSearchModules.RUnlock()
	return calls
}
