// Code generated by "stringer -type=AnnotationKind -output=annotation_kind_string.go"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VarAnnotation-0]
	_ = x[SubParamAnnotation-1]
	_ = x[SubReturnAnnotation-2]
	_ = x[MethodParamAnnotation-3]
	_ = x[MethodReturnAnnotation-4]
	_ = x[FieldAnnotation-5]
	_ = x[TypeDeclAnnotation-6]
	_ = x[TypeAssertionAnnotation-7]
}

const _AnnotationKind_name = "VarAnnotationSubParamAnnotationSubReturnAnnotationMethodParamAnnotationMethodReturnAnnotationFieldAnnotationTypeDeclAnnotationTypeAssertionAnnotation"

var _AnnotationKind_index = [...]uint8{0, 13, 31, 50, 71, 93, 108, 126, 149}

func (i AnnotationKind) String() string {
	if i < 0 || i >= AnnotationKind(len(_AnnotationKind_index)-1) {
		return "AnnotationKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AnnotationKind_name[_AnnotationKind_index[i]:_AnnotationKind_index[i+1]]
}
