#!/usr/bin/env sh
# PVM Shell Integration for Bash/Zsh
# Generated by PVM - DO NOT EDIT

# Path to PVM executable
PVM_EXEC="/Users/perigrin/dev/pvm/build/pvm"

# Shims directory
PVM_SHIMS_DIR="/Users/perigrin/dev/pvm/data/pvm/shims"

# Function to initialize PVM
pvm_init() {
    # Add shims directory to PATH if not already there
    case ":${PATH}:" in
        *":${PVM_SHIMS_DIR}:"*) ;;
        *) export PATH="${PVM_SHIMS_DIR}:${PATH}" ;;
    esac

    # Define shell functions for version switching
    pvm_use() {
        local version="$1"
        if [ -z "$version" ]; then
            echo "Usage: pvm use <version>"
            return 1
        fi

        # Set version for current shell
        export PVM_PERL_VERSION="$version"
        echo "Using Perl $version"
    }

    pvm_local() {
        "$PVM_EXEC" local "$@"
    }

    pvm_global() {
        "$PVM_EXEC" global "$@"
    }

    # Create shell aliases
    if [ -n "$ZSH_VERSION" ]; then
        # Zsh aliases
        alias pvm-use="pvm_use"
        alias pvm-local="pvm_local"
        alias pvm-global="pvm_global"
    else
        # Bash aliases
        alias pvm-use="pvm_use"
        alias pvm-local="pvm_local"
        alias pvm-global="pvm_global"
    fi

    # Function to run custom commands upon directory change
    pvm_cd() {
        \cd "$@" || return $?

        # Check for .perl-version file in current directory
        if [ -f .perl-version ]; then
            local version=$(cat .perl-version)
            [ -n "$version" ] && pvm_use "$version"
        fi
    }

    # Set up cd override (if supported)
    if [ -n "$ZSH_VERSION" ]; then
        # For Zsh, use chpwd hook
        pvm_chpwd() {
            if [ -f .perl-version ]; then
                local version=$(cat .perl-version)
                [ -n "$version" ] && pvm_use "$version"
            fi
        }

        autoload -Uz add-zsh-hook
        add-zsh-hook chpwd pvm_chpwd
    else
        # For Bash, override cd
        alias cd="pvm_cd"
    fi
}

# Initialize PVM
pvm_init

# Output message
echo "PVM environment initialized"
