// Code generated by generate_errors.go; DO NOT EDIT.
// This file is generated from error definitions - edit the source config instead.

package errors

// Generated error codes for PM
const (
	PM201 = "201" // Module not found
	PM202 = "202" // Dependency conflict
)

// Generated error constructors

// NewPM201Error creates a new 201 error
func NewPM201Error(detail string, location string) *Error {
	return &Error{
		prefix:   "PM",
		category: "Module Error",
		code:     "201",
		message:  "Module not found",
		detail:   detail,
		location: location,
		hint:     "Check the module name spelling or try a different CPAN mirror",
	}
}

// NewPM202Error creates a new 202 error
func NewPM202Error(detail string, location string) *Error {
	return &Error{
		prefix:   "PM",
		category: "Module Error",
		code:     "202",
		message:  "Dependency conflict",
		detail:   detail,
		location: location,
		hint:     "Update conflicting modules or use a compatible version",
	}
}
