// Code generated by generate_errors.go; DO NOT EDIT.
// This file is generated from error definitions - edit the source config instead.

package errors

// Generated error codes for PSC
const (
	PSC101 = "101" // Type mismatch
	PSC102 = "102" // Undefined variable
	PSC103 = "103" // Invalid type expression
)

// Generated error constructors

// NewPSC101Error creates a new 101 error
func NewPSC101Error(detail string, location string) *Error {
	return &Error{
		prefix:   "PSC",
		category: "Type Error",
		code:     "101",
		message:  "Type mismatch",
		detail:   detail,
		location: location,
		hint:     "Ensure the assigned value matches the variable's declared type",
	}
}

// NewPSC102Error creates a new 102 error
func NewPSC102Error(detail string, location string) *Error {
	return &Error{
		prefix:   "PSC",
		category: "Type Error",
		code:     "102",
		message:  "Undefined variable",
		detail:   detail,
		location: location,
		hint:     "Declare the variable with 'my', 'our', or 'state' before use",
	}
}

// NewPSC103Error creates a new 103 error
func NewPSC103Error(detail string, location string) *Error {
	return &Error{
		prefix:   "PSC",
		category: "Type Error",
		code:     "103",
		message:  "Invalid type expression",
		detail:   detail,
		location: location,
		hint:     "Check the type syntax and ensure all referenced types are defined",
	}
}
