// Code generated by generate_errors.go; DO NOT EDIT.
// This file is generated from error definitions - edit the source config instead.

package errors

// Generated error codes for PVI
const (
	PVI201 = "201" // Module not found
	PVI202 = "202" // Dependency conflict
)

// Generated error constructors

// NewPVI201Error creates a new 201 error
func NewPVI201Error(detail string, location string) *Error {
	return &Error{
		prefix:   "PVI",
		category: "Module Error",
		code:     "201",
		message:  "Module not found",
		detail:   detail,
		location: location,
		hint:     "Check the module name spelling or try a different CPAN mirror",
	}
}

// NewPVI202Error creates a new 202 error
func NewPVI202Error(detail string, location string) *Error {
	return &Error{
		prefix:   "PVI",
		category: "Module Error",
		code:     "202",
		message:  "Dependency conflict",
		detail:   detail,
		location: location,
		hint:     "Update conflicting modules or use a compatible version",
	}
}
