// ABOUTME: Generated error constructors and constants for the PVM (Perl version manager) subsystem
// ABOUTME: Produced by generate_errors.go from error definitions; edit the source config to change these values

// Code generated by generate_errors.go; DO NOT EDIT.
// This file is generated from error definitions - edit the source config instead.

package errors

// Generated error codes for PVM
const (
	PVM001 = "001" // Invalid configuration file
	PVM002 = "002" // Perl version not found
	PVM003 = "003" // Permission denied
)

// Generated error constructors

// NewPVM001Error creates a new 001 error
func NewPVM001Error(detail string, location string) *Error {
	return &Error{
		prefix:   "PVM",
		category: "Configuration Error",
		code:     "001",
		message:  "Invalid configuration file",
		detail:   detail,
		location: location,
		hint:     "Check the configuration file syntax and ensure all required fields are present",
	}
}

// NewPVM002Error creates a new 002 error
func NewPVM002Error(detail string, location string) *Error {
	return &Error{
		prefix:   "PVM",
		category: "Version Error",
		code:     "002",
		message:  "Perl version not found",
		detail:   detail,
		location: location,
		hint:     "Use 'pvm list' to see available versions or install with 'pvm install <version>'",
	}
}

// NewPVM003Error creates a new 003 error
func NewPVM003Error(detail string, location string) *Error {
	return &Error{
		prefix:   "PVM",
		category: "System Error",
		code:     "003",
		message:  "Permission denied",
		detail:   detail,
		location: location,
		hint:     "Try running with elevated privileges or check file permissions",
	}
}
