// Code generated by generate_errors.go; DO NOT EDIT.
// This file is generated from error definitions - edit the source config instead.

package errors

// Generated error codes for PVX
const (
	PVX301 = "301" // Script execution failed
	PVX302 = "302" // Execution timeout
)

// Generated error constructors

// NewPVX301Error creates a new 301 error
func NewPVX301Error(detail string, location string) *Error {
	return &Error{
		prefix:   "PVX",
		category: "Execution Error",
		code:     "301",
		message:  "Script execution failed",
		detail:   detail,
		location: location,
		hint:     "Check the script for runtime errors or syntax issues",
	}
}

// NewPVX302Error creates a new 302 error
func NewPVX302Error(detail string, location string) *Error {
	return &Error{
		prefix:   "PVX",
		category: "Execution Error",
		code:     "302",
		message:  "Execution timeout",
		detail:   detail,
		location: location,
		hint:     "Increase the timeout limit or optimize the script performance",
	}
}
