// ABOUTME: Deep module introspection for Perl code analysis
// ABOUTME: Provides symbol table analysis and dynamic method detection

package parser

import (
	"fmt"
	"regexp"
	"strings"
)

// ModuleIntrospector provides deep introspection capabilities for Perl modules
type ModuleIntrospector struct {
	// Parser is the underlying parser for AST generation
	Parser Parser

	// SymbolTable tracks all symbols (functions, variables, packages) in the module
	SymbolTable *SymbolTable

	// MethodDetector identifies methods including dynamically generated ones
	MethodDetector *DynamicMethodDetector

	// OOPPatternDetector recognizes common OOP frameworks (Moose, Moo, etc.)
	OOPPatternDetector *OOPPatternDetector

	// DataStructureAnalyzer analyzes complex data structures
	DataStructureAnalyzer *DataStructureAnalyzer
}

// SymbolTable represents all symbols found in a module
type SymbolTable struct {
	// Packages maps package names to their symbols
	Packages map[string]*PackageSymbols

	// GlobalVariables tracks module-level variables
	GlobalVariables map[string]*VariableInfo

	// Imports tracks imported modules and their symbols
	Imports map[string]*ImportInfo
}

// PackageSymbols represents symbols within a package
type PackageSymbols struct {
	// Name is the package name
	Name string

	// Methods maps method names to their signatures
	Methods map[string]*MethodSignature

	// Attributes maps attribute names to their types
	Attributes map[string]*AttributeInfo

	// Constants maps constant names to their values
	Constants map[string]interface{}

	// ParentClasses lists parent classes for inheritance
	ParentClasses []string

	// Roles lists consumed roles (for Moose/Moo)
	Roles []string
}

// MethodSignature represents a method's signature with parameters and return type
type MethodSignature struct {
	// Name is the method name
	Name string

	// Parameters lists the method parameters
	Parameters []*ParameterInfo

	// ReturnType is the inferred or documented return type
	ReturnType string

	// IsAutoloaded indicates if this method is handled by AUTOLOAD
	IsAutoloaded bool

	// IsDynamic indicates if this method is dynamically generated
	IsDynamic bool

	// Source indicates how the method was detected (explicit, AUTOLOAD, generated, etc.)
	Source MethodSource

	// Documentation extracted from POD or comments
	Documentation string
}

// ParameterInfo represents information about a method parameter
type ParameterInfo struct {
	// Name is the parameter name
	Name string

	// Type is the inferred or documented type
	Type string

	// IsOptional indicates if the parameter is optional
	IsOptional bool

	// DefaultValue is the default value if any
	DefaultValue string

	// Documentation for the parameter
	Documentation string
}

// AttributeInfo represents information about a class attribute
type AttributeInfo struct {
	// Name is the attribute name
	Name string

	// Type is the attribute type
	Type string

	// IsRequired indicates if the attribute is required
	IsRequired bool

	// HasDefault indicates if the attribute has a default value
	HasDefault bool

	// DefaultValue is the default value if any
	DefaultValue string

	// Traits lists any attribute traits (for Moose/Moo)
	Traits []string

	// Documentation for the attribute
	Documentation string
}

// VariableInfo represents information about a variable
type VariableInfo struct {
	// Name is the variable name
	Name string

	// Type is the inferred type
	Type string

	// Scope is the variable scope (my, our, state)
	Scope string

	// InitialValue is the initial value if any
	InitialValue string
}

// ImportInfo represents information about an imported module
type ImportInfo struct {
	// ModuleName is the imported module name
	ModuleName string

	// ImportedSymbols lists explicitly imported symbols
	ImportedSymbols []string

	// ImportAll indicates if all symbols were imported
	ImportAll bool

	// Version is the required version if specified
	Version string
}

// MethodSource indicates how a method was detected
type MethodSource int

const (
	// MethodSourceExplicit for explicitly defined methods
	MethodSourceExplicit MethodSource = iota
	// MethodSourceAutoload for AUTOLOAD-handled methods
	MethodSourceAutoload
	// MethodSourceGenerated for methods generated by frameworks
	MethodSourceGenerated
	// MethodSourceInherited for inherited methods
	MethodSourceInherited
	// MethodSourceRole for methods from consumed roles
	MethodSourceRole
)

// DynamicMethodDetector detects dynamically generated methods
type DynamicMethodDetector struct {
	// Patterns for recognizing method generators
	GeneratorPatterns []*regexp.Regexp

	// KnownGenerators maps generator function names to their patterns
	KnownGenerators map[string]MethodGeneratorInfo
}

// MethodGeneratorInfo describes a method generator pattern
type MethodGeneratorInfo struct {
	// Pattern matches the generator usage
	Pattern *regexp.Regexp

	// ExtractMethodName extracts the generated method name
	ExtractMethodName func(match []string) string

	// InferSignature infers the method signature
	InferSignature func(match []string) *MethodSignature
}

// OOPPatternDetector recognizes OOP framework patterns
type OOPPatternDetector struct {
	// FrameworkPatterns maps framework names to their detection patterns
	FrameworkPatterns map[string]*FrameworkPattern

	// DetectedFrameworks lists detected OOP frameworks in the module
	DetectedFrameworks []string
}

// FrameworkPattern describes patterns for detecting an OOP framework
type FrameworkPattern struct {
	// Name is the framework name (Moose, Moo, Class::Tiny, etc.)
	Name string

	// UsePattern matches the use statement
	UsePattern *regexp.Regexp

	// AttributePattern matches attribute declarations
	AttributePattern *regexp.Regexp

	// MethodModifierPattern matches method modifiers (before, after, around)
	MethodModifierPattern *regexp.Regexp

	// ExtractAttribute extracts attribute info from a match
	ExtractAttribute func(node Node) *AttributeInfo

	// ExtractMethodModifier extracts method modifier info
	ExtractMethodModifier func(node Node) *MethodModifierInfo
}

// MethodModifierInfo represents a method modifier (before/after/around)
type MethodModifierInfo struct {
	// Type is the modifier type
	Type string

	// TargetMethod is the method being modified
	TargetMethod string

	// Implementation is the modifier implementation
	Implementation Node
}

// DataStructureAnalyzer analyzes complex data structures
type DataStructureAnalyzer struct {
	// TypeInferenceRules for inferring types from data structures
	TypeInferenceRules []TypeInferenceRule
}

// TypeInferenceRule represents a rule for inferring types from code patterns
type TypeInferenceRule struct {
	// Name is the rule name
	Name string

	// Pattern matches the code pattern
	Pattern *regexp.Regexp

	// InferType infers the type from the match
	InferType func(match []string) string
}

// NewModuleIntrospector creates a new module introspector
func NewModuleIntrospector() (*ModuleIntrospector, error) {
	parser, err := NewParser()
	if err != nil {
		return nil, fmt.Errorf("failed to create parser: %w", err)
	}

	introspector := &ModuleIntrospector{
		Parser:                parser,
		SymbolTable:           NewSymbolTable(),
		MethodDetector:        NewDynamicMethodDetector(),
		OOPPatternDetector:    NewOOPPatternDetector(),
		DataStructureAnalyzer: NewDataStructureAnalyzer(),
	}

	return introspector, nil
}

// NewSymbolTable creates a new symbol table
func NewSymbolTable() *SymbolTable {
	return &SymbolTable{
		Packages:        make(map[string]*PackageSymbols),
		GlobalVariables: make(map[string]*VariableInfo),
		Imports:         make(map[string]*ImportInfo),
	}
}

// NewDynamicMethodDetector creates a new dynamic method detector
func NewDynamicMethodDetector() *DynamicMethodDetector {
	detector := &DynamicMethodDetector{
		GeneratorPatterns: []*regexp.Regexp{},
		KnownGenerators:   make(map[string]MethodGeneratorInfo),
	}

	// Add common method generator patterns
	detector.addCommonGenerators()

	return detector
}

// addCommonGenerators adds patterns for common method generators
func (d *DynamicMethodDetector) addCommonGenerators() {
	// Class::Accessor pattern
	d.KnownGenerators["mk_accessors"] = MethodGeneratorInfo{
		Pattern: regexp.MustCompile(`__PACKAGE__->mk_accessors\s*\(\s*(?:qw\s*\()?\s*([^)]+)\s*\)?`),
		ExtractMethodName: func(match []string) string {
			if len(match) > 1 {
				// Extract accessor names from qw() or quoted list
				accessors := strings.Fields(match[1])
				return strings.Join(accessors, ", ")
			}
			return ""
		},
		InferSignature: func(match []string) *MethodSignature {
			return &MethodSignature{
				Parameters: []*ParameterInfo{
					{Name: "$self", Type: "Object"},
					{Name: "$value", Type: "Any", IsOptional: true},
				},
				ReturnType: "Any",
				IsDynamic:  true,
				Source:     MethodSourceGenerated,
			}
		},
	}

	// Moose/Moo 'has' attribute pattern (creates accessors)
	d.KnownGenerators["has"] = MethodGeneratorInfo{
		Pattern: regexp.MustCompile(`has\s+['"]?(\w+)['"]?\s*=>`),
		ExtractMethodName: func(match []string) string {
			if len(match) > 1 {
				return match[1]
			}
			return ""
		},
		InferSignature: func(match []string) *MethodSignature {
			return &MethodSignature{
				Parameters: []*ParameterInfo{
					{Name: "$self", Type: "Object"},
					{Name: "$value", Type: "Any", IsOptional: true},
				},
				ReturnType: "Any",
				IsDynamic:  true,
				Source:     MethodSourceGenerated,
			}
		},
	}
}

// NewOOPPatternDetector creates a new OOP pattern detector
func NewOOPPatternDetector() *OOPPatternDetector {
	detector := &OOPPatternDetector{
		FrameworkPatterns:  make(map[string]*FrameworkPattern),
		DetectedFrameworks: []string{},
	}

	// Add patterns for common OOP frameworks
	detector.addFrameworkPatterns()

	return detector
}

// addFrameworkPatterns adds patterns for common OOP frameworks
func (d *OOPPatternDetector) addFrameworkPatterns() {
	// Moose pattern
	d.FrameworkPatterns["Moose"] = &FrameworkPattern{
		Name:                  "Moose",
		UsePattern:            regexp.MustCompile(`use\s+Moose\s*;`),
		AttributePattern:      regexp.MustCompile(`has\s+['"]?(\w+)['"]?\s*=>\s*\(`),
		MethodModifierPattern: regexp.MustCompile(`(before|after|around)\s+['"]?(\w+)['"]?\s*=>`),
		ExtractAttribute: func(node Node) *AttributeInfo {
			// This would be implemented to extract Moose attribute info from AST
			return nil
		},
	}

	// Moo pattern
	d.FrameworkPatterns["Moo"] = &FrameworkPattern{
		Name:                  "Moo",
		UsePattern:            regexp.MustCompile(`use\s+Moo\s*;`),
		AttributePattern:      regexp.MustCompile(`has\s+['"]?(\w+)['"]?\s*=>\s*\(`),
		MethodModifierPattern: regexp.MustCompile(`(before|after|around)\s+['"]?(\w+)['"]?\s*=>`),
		ExtractAttribute: func(node Node) *AttributeInfo {
			// This would be implemented to extract Moo attribute info from AST
			return nil
		},
	}

	// Class::Tiny pattern
	d.FrameworkPatterns["Class::Tiny"] = &FrameworkPattern{
		Name:             "Class::Tiny",
		UsePattern:       regexp.MustCompile(`use\s+Class::Tiny\s+(?:qw\s*\()?\s*([^;)]+)`),
		AttributePattern: nil, // Class::Tiny declares attributes in the use statement
		ExtractAttribute: func(node Node) *AttributeInfo {
			// This would be implemented to extract Class::Tiny attribute info
			return nil
		},
	}
}

// NewDataStructureAnalyzer creates a new data structure analyzer
func NewDataStructureAnalyzer() *DataStructureAnalyzer {
	analyzer := &DataStructureAnalyzer{
		TypeInferenceRules: []TypeInferenceRule{},
	}

	// Add common type inference rules
	analyzer.addTypeInferenceRules()

	return analyzer
}

// addTypeInferenceRules adds common type inference rules
func (a *DataStructureAnalyzer) addTypeInferenceRules() {
	// Array reference pattern
	a.TypeInferenceRules = append(a.TypeInferenceRules, TypeInferenceRule{
		Name:    "array_ref",
		Pattern: regexp.MustCompile(`\$\w+\s*=\s*\[\s*`),
		InferType: func(match []string) string {
			return "ArrayRef"
		},
	})

	// Hash reference pattern
	a.TypeInferenceRules = append(a.TypeInferenceRules, TypeInferenceRule{
		Name:    "hash_ref",
		Pattern: regexp.MustCompile(`\$\w+\s*=\s*\{\s*`),
		InferType: func(match []string) string {
			return "HashRef"
		},
	})

	// DBI database handle pattern
	a.TypeInferenceRules = append(a.TypeInferenceRules, TypeInferenceRule{
		Name:    "dbi_handle",
		Pattern: regexp.MustCompile(`DBI->connect\s*\(`),
		InferType: func(match []string) string {
			return "DBI::db"
		},
	})
}

// IntrospectModule performs deep introspection on a Perl module
func (mi *ModuleIntrospector) IntrospectModule(path string) (*ModuleIntrospectionResult, error) {
	// Parse the module
	ast, err := mi.Parser.ParseFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to parse module: %w", err)
	}

	// Check for parse errors
	if len(ast.Errors) > 0 {
		return nil, fmt.Errorf("parse errors: %v", ast.Errors)
	}

	result := &ModuleIntrospectionResult{
		Path:        path,
		SymbolTable: mi.SymbolTable,
		Packages:    make(map[string]*PackageInfo),
		Errors:      []error{},
	}

	// Analyze the AST
	if ast.Root != nil {
		mi.analyzeNode(ast.Root, result)
	}

	// Detect OOP frameworks
	mi.detectOOPFrameworks(ast, result)

	// Analyze dynamic methods
	mi.analyzeDynamicMethods(ast, result)

	// Analyze data structures
	mi.analyzeDataStructures(ast, result)

	return result, nil
}

// analyzeNode recursively analyzes AST nodes
func (mi *ModuleIntrospector) analyzeNode(node Node, result *ModuleIntrospectionResult) {
	nodeType := node.Type()

	// For debugging - common node types in tree-sitter-perl
	switch nodeType {
	case "package_declaration", "package_statement":
		mi.analyzePackageDeclaration(node, result)
	case "sub_declaration", "method_declaration", "subroutine_declaration_statement":
		mi.analyzeSubroutineDeclaration(node, result)
	case "variable_declaration", "variable_declaration_statement":
		mi.analyzeVariableDeclaration(node, result)
	case "use_statement", "use_no_statement":
		mi.analyzeUseStatement(node, result)
	case "class_definition":
		mi.analyzeClassDefinition(node, result)
	}

	// Recursively analyze children
	for _, child := range node.Children() {
		mi.analyzeNode(child, result)
	}
}

// analyzePackageDeclaration analyzes a package declaration
func (mi *ModuleIntrospector) analyzePackageDeclaration(node Node, result *ModuleIntrospectionResult) {
	// Extract package name from the node
	packageName := mi.extractPackageName(node)
	if packageName == "" {
		return
	}

	// Create or get package symbols
	if _, exists := mi.SymbolTable.Packages[packageName]; !exists {
		mi.SymbolTable.Packages[packageName] = &PackageSymbols{
			Name:       packageName,
			Methods:    make(map[string]*MethodSignature),
			Attributes: make(map[string]*AttributeInfo),
			Constants:  make(map[string]interface{}),
		}
	}

	// Create package info for result
	result.Packages[packageName] = &PackageInfo{
		Name:       packageName,
		Methods:    make(map[string]*MethodSignature),
		Attributes: make(map[string]*AttributeInfo),
	}

	// Store current package for context
	result.currentPackage = packageName
}

// analyzeSubroutineDeclaration analyzes a subroutine declaration
func (mi *ModuleIntrospector) analyzeSubroutineDeclaration(node Node, result *ModuleIntrospectionResult) {
	// Extract method signature from the node
	signature := mi.extractMethodSignature(node)
	if signature == nil {
		return
	}

	// Determine the current package
	currentPackage := mi.getCurrentPackage(node)

	// Ensure package exists in symbol table
	if _, exists := mi.SymbolTable.Packages[currentPackage]; !exists {
		mi.SymbolTable.Packages[currentPackage] = &PackageSymbols{
			Name:       currentPackage,
			Methods:    make(map[string]*MethodSignature),
			Attributes: make(map[string]*AttributeInfo),
			Constants:  make(map[string]interface{}),
		}
	}

	// Ensure package exists in result
	if _, exists := result.Packages[currentPackage]; !exists {
		result.Packages[currentPackage] = &PackageInfo{
			Name:       currentPackage,
			Methods:    make(map[string]*MethodSignature),
			Attributes: make(map[string]*AttributeInfo),
		}
	}

	// Add to symbol table
	if pkg, exists := mi.SymbolTable.Packages[currentPackage]; exists {
		pkg.Methods[signature.Name] = signature
	}

	// Add to result
	if pkgInfo, exists := result.Packages[currentPackage]; exists {
		pkgInfo.Methods[signature.Name] = signature
	}
}

// Helper methods for extraction
func (mi *ModuleIntrospector) extractPackageName(node Node) string {
	// This would extract the package name from the AST node
	// For now, return a simple extraction based on node text
	text := node.Text()
	if strings.HasPrefix(text, "package ") {
		parts := strings.Fields(text)
		if len(parts) >= 2 {
			return strings.TrimSuffix(parts[1], ";")
		}
	}
	return ""
}

func (mi *ModuleIntrospector) extractMethodSignature(node Node) *MethodSignature {
	// This would extract method signature from the AST node
	// For now, return a basic signature
	text := node.Text()
	if strings.HasPrefix(text, "sub ") {
		parts := strings.Fields(text)
		if len(parts) >= 2 {
			methodName := parts[1]
			// Remove any opening parenthesis
			if idx := strings.Index(methodName, "("); idx > 0 {
				methodName = methodName[:idx]
			}

			return &MethodSignature{
				Name:       methodName,
				Parameters: []*ParameterInfo{},
				ReturnType: "Any",
				Source:     MethodSourceExplicit,
			}
		}
	}
	return nil
}

func (mi *ModuleIntrospector) getCurrentPackage(node Node) string {
	// For now, return "main" as default
	// In a full implementation, this would track package context through the AST
	return "main"
}

// Stub methods for analysis
func (mi *ModuleIntrospector) analyzeVariableDeclaration(node Node, result *ModuleIntrospectionResult) {
	// TODO: Implement variable declaration analysis
}

func (mi *ModuleIntrospector) analyzeUseStatement(node Node, result *ModuleIntrospectionResult) {
	// TODO: Implement use statement analysis
}

func (mi *ModuleIntrospector) analyzeClassDefinition(node Node, result *ModuleIntrospectionResult) {
	// TODO: Implement class definition analysis
}

func (mi *ModuleIntrospector) detectOOPFrameworks(ast *AST, result *ModuleIntrospectionResult) {
	// TODO: Implement OOP framework detection
}

func (mi *ModuleIntrospector) analyzeDynamicMethods(ast *AST, result *ModuleIntrospectionResult) {
	// TODO: Implement dynamic method analysis
}

func (mi *ModuleIntrospector) analyzeDataStructures(ast *AST, result *ModuleIntrospectionResult) {
	// TODO: Implement data structure analysis
}

// ModuleIntrospectionResult represents the result of module introspection
type ModuleIntrospectionResult struct {
	// Path is the module file path
	Path string

	// SymbolTable contains all discovered symbols
	SymbolTable *SymbolTable

	// Packages maps package names to their information
	Packages map[string]*PackageInfo

	// DetectedFrameworks lists detected OOP frameworks
	DetectedFrameworks []string

	// DataStructures contains analyzed data structure information
	DataStructures map[string]*DataStructureInfo

	// Errors contains any errors encountered during introspection
	Errors []error

	// currentPackage tracks the current package context during analysis
	currentPackage string
}

// PackageInfo contains information about a package
type PackageInfo struct {
	// Name is the package name
	Name string

	// Methods contains all methods in the package
	Methods map[string]*MethodSignature

	// Attributes contains all attributes
	Attributes map[string]*AttributeInfo

	// ParentClasses lists parent classes
	ParentClasses []string

	// Roles lists consumed roles
	Roles []string
}

// DataStructureInfo represents analyzed data structure information
type DataStructureInfo struct {
	// Name is the variable name
	Name string

	// Type is the inferred type
	Type string

	// Structure describes the data structure
	Structure interface{}
}
