// ABOUTME: Deep module introspection for Perl code analysis
// ABOUTME: Provides symbol table analysis and dynamic method detection

package parser

import (
	"fmt"
	"regexp"
	"strings"
)

// ModuleIntrospector provides deep introspection capabilities for Perl modules
type ModuleIntrospector struct {
	// Parser is the underlying parser for AST generation
	Parser Parser

	// SymbolTable tracks all symbols (functions, variables, packages) in the module
	SymbolTable *SymbolTable

	// MethodDetector identifies methods including dynamically generated ones
	MethodDetector *DynamicMethodDetector

	// OOPPatternDetector recognizes common OOP frameworks (Moose, Moo, etc.)
	OOPPatternDetector *OOPPatternDetector

	// DataStructureAnalyzer analyzes complex data structures
	DataStructureAnalyzer *DataStructureAnalyzer
}

// SymbolTable represents all symbols found in a module
type SymbolTable struct {
	// Packages maps package names to their symbols
	Packages map[string]*PackageSymbols

	// GlobalVariables tracks module-level variables
	GlobalVariables map[string]*VariableInfo

	// Imports tracks imported modules and their symbols
	Imports map[string]*ImportInfo
}

// PackageSymbols represents symbols within a package
type PackageSymbols struct {
	// Name is the package name
	Name string

	// Methods maps method names to their signatures
	Methods map[string]*MethodSignature

	// Attributes maps attribute names to their types
	Attributes map[string]*AttributeInfo

	// Constants maps constant names to their values
	Constants map[string]interface{}

	// ParentClasses lists parent classes for inheritance
	ParentClasses []string

	// Roles lists consumed roles (for Moose/Moo)
	Roles []string
}

// MethodSignature represents a method's signature with parameters and return type
type MethodSignature struct {
	// Name is the method name
	Name string

	// Parameters lists the method parameters
	Parameters []*ParameterInfo

	// ReturnType is the inferred or documented return type
	ReturnType string

	// IsAutoloaded indicates if this method is handled by AUTOLOAD
	IsAutoloaded bool

	// IsDynamic indicates if this method is dynamically generated
	IsDynamic bool

	// Source indicates how the method was detected (explicit, AUTOLOAD, generated, etc.)
	Source MethodSource

	// Documentation extracted from POD or comments
	Documentation string
}

// ParameterInfo represents information about a method parameter
type ParameterInfo struct {
	// Name is the parameter name
	Name string

	// Type is the inferred or documented type
	Type string

	// IsOptional indicates if the parameter is optional
	IsOptional bool

	// DefaultValue is the default value if any
	DefaultValue string

	// Documentation for the parameter
	Documentation string
}

// AttributeInfo represents information about a class attribute
type AttributeInfo struct {
	// Name is the attribute name
	Name string

	// Type is the attribute type
	Type string

	// IsRequired indicates if the attribute is required
	IsRequired bool

	// HasDefault indicates if the attribute has a default value
	HasDefault bool

	// DefaultValue is the default value if any
	DefaultValue string

	// Traits lists any attribute traits (for Moose/Moo)
	Traits []string

	// Documentation for the attribute
	Documentation string
}

// VariableInfo represents information about a variable
type VariableInfo struct {
	// Name is the variable name
	Name string

	// Type is the inferred type
	Type string

	// Scope is the variable scope (my, our, state)
	Scope string

	// InitialValue is the initial value if any
	InitialValue string
}

// ImportInfo represents information about an imported module
type ImportInfo struct {
	// ModuleName is the imported module name
	ModuleName string

	// ImportedSymbols lists explicitly imported symbols
	ImportedSymbols []string

	// ImportAll indicates if all symbols were imported
	ImportAll bool

	// Version is the required version if specified
	Version string
}

// MethodSource indicates how a method was detected
type MethodSource int

const (
	// MethodSourceExplicit for explicitly defined methods
	MethodSourceExplicit MethodSource = iota
	// MethodSourceAutoload for AUTOLOAD-handled methods
	MethodSourceAutoload
	// MethodSourceGenerated for methods generated by frameworks
	MethodSourceGenerated
	// MethodSourceInherited for inherited methods
	MethodSourceInherited
	// MethodSourceRole for methods from consumed roles
	MethodSourceRole
)

// DynamicMethodDetector detects dynamically generated methods
type DynamicMethodDetector struct {
	// Patterns for recognizing method generators
	GeneratorPatterns []*regexp.Regexp

	// KnownGenerators maps generator function names to their patterns
	KnownGenerators map[string]MethodGeneratorInfo
}

// MethodGeneratorInfo describes a method generator pattern
type MethodGeneratorInfo struct {
	// Pattern matches the generator usage
	Pattern *regexp.Regexp

	// ExtractMethodName extracts the generated method name
	ExtractMethodName func(match []string) string

	// InferSignature infers the method signature
	InferSignature func(match []string) *MethodSignature
}

// OOPPatternDetector recognizes OOP framework patterns
type OOPPatternDetector struct {
	// FrameworkPatterns maps framework names to their detection patterns
	FrameworkPatterns map[string]*FrameworkPattern

	// DetectedFrameworks lists detected OOP frameworks in the module
	DetectedFrameworks []string
}

// FrameworkPattern describes patterns for detecting an OOP framework
type FrameworkPattern struct {
	// Name is the framework name (Moose, Moo, Class::Tiny, etc.)
	Name string

	// UsePattern matches the use statement
	UsePattern *regexp.Regexp

	// AttributePattern matches attribute declarations
	AttributePattern *regexp.Regexp

	// MethodModifierPattern matches method modifiers (before, after, around)
	MethodModifierPattern *regexp.Regexp

	// ExtractAttribute extracts attribute info from a match
	ExtractAttribute func(node Node) *AttributeInfo

	// ExtractMethodModifier extracts method modifier info
	ExtractMethodModifier func(node Node) *MethodModifierInfo
}

// MethodModifierInfo represents a method modifier (before/after/around)
type MethodModifierInfo struct {
	// Type is the modifier type
	Type string

	// TargetMethod is the method being modified
	TargetMethod string

	// Implementation is the modifier implementation
	Implementation Node
}

// DataStructureAnalyzer analyzes complex data structures
type DataStructureAnalyzer struct {
	// TypeInferenceRules for inferring types from data structures
	TypeInferenceRules []TypeInferenceRule
}

// TypeInferenceRule represents a rule for inferring types from code patterns
type TypeInferenceRule struct {
	// Name is the rule name
	Name string

	// Pattern matches the code pattern
	Pattern *regexp.Regexp

	// InferType infers the type from the match
	InferType func(match []string) string
}

// NewModuleIntrospector creates a new module introspector
func NewModuleIntrospector() (*ModuleIntrospector, error) {
	parser, err := NewParser()
	if err != nil {
		return nil, fmt.Errorf("failed to create parser: %w", err)
	}

	introspector := &ModuleIntrospector{
		Parser:                parser,
		SymbolTable:           NewSymbolTable(),
		MethodDetector:        NewDynamicMethodDetector(),
		OOPPatternDetector:    NewOOPPatternDetector(),
		DataStructureAnalyzer: NewDataStructureAnalyzer(),
	}

	return introspector, nil
}

// NewSymbolTable creates a new symbol table
func NewSymbolTable() *SymbolTable {
	return &SymbolTable{
		Packages:        make(map[string]*PackageSymbols),
		GlobalVariables: make(map[string]*VariableInfo),
		Imports:         make(map[string]*ImportInfo),
	}
}

// NewDynamicMethodDetector creates a new dynamic method detector
func NewDynamicMethodDetector() *DynamicMethodDetector {
	detector := &DynamicMethodDetector{
		GeneratorPatterns: []*regexp.Regexp{},
		KnownGenerators:   make(map[string]MethodGeneratorInfo),
	}

	// Add common method generator patterns
	detector.addCommonGenerators()

	return detector
}

// addCommonGenerators adds patterns for common method generators
func (d *DynamicMethodDetector) addCommonGenerators() {
	// Class::Accessor pattern
	d.KnownGenerators["mk_accessors"] = MethodGeneratorInfo{
		Pattern: regexp.MustCompile(`__PACKAGE__->mk_accessors\s*\(\s*(?:qw\s*\()?\s*([^)]+)\s*\)?`),
		ExtractMethodName: func(match []string) string {
			if len(match) > 1 {
				// Extract accessor names from qw() or quoted list
				accessors := strings.Fields(match[1])
				return strings.Join(accessors, ", ")
			}
			return ""
		},
		InferSignature: func(match []string) *MethodSignature {
			return &MethodSignature{
				Parameters: []*ParameterInfo{
					{Name: "$self", Type: "Object"},
					{Name: "$value", Type: "Any", IsOptional: true},
				},
				ReturnType: "Any",
				IsDynamic:  true,
				Source:     MethodSourceGenerated,
			}
		},
	}

	// Moose/Moo 'has' attribute pattern (creates accessors)
	d.KnownGenerators["has"] = MethodGeneratorInfo{
		Pattern: regexp.MustCompile(`has\s+['"]?(\w+)['"]?\s*=>`),
		ExtractMethodName: func(match []string) string {
			if len(match) > 1 {
				return match[1]
			}
			return ""
		},
		InferSignature: func(match []string) *MethodSignature {
			return &MethodSignature{
				Parameters: []*ParameterInfo{
					{Name: "$self", Type: "Object"},
					{Name: "$value", Type: "Any", IsOptional: true},
				},
				ReturnType: "Any",
				IsDynamic:  true,
				Source:     MethodSourceGenerated,
			}
		},
	}
}

// NewOOPPatternDetector creates a new OOP pattern detector
func NewOOPPatternDetector() *OOPPatternDetector {
	detector := &OOPPatternDetector{
		FrameworkPatterns:  make(map[string]*FrameworkPattern),
		DetectedFrameworks: []string{},
	}

	// Add patterns for common OOP frameworks
	detector.addFrameworkPatterns()

	return detector
}

// addFrameworkPatterns adds patterns for common OOP frameworks
func (d *OOPPatternDetector) addFrameworkPatterns() {
	// Moose pattern
	d.FrameworkPatterns["Moose"] = &FrameworkPattern{
		Name:                  "Moose",
		UsePattern:            regexp.MustCompile(`use\s+Moose\s*;`),
		AttributePattern:      regexp.MustCompile(`has\s+['"]?(\w+)['"]?\s*=>\s*\(`),
		MethodModifierPattern: regexp.MustCompile(`(before|after|around)\s+['"]?(\w+)['"]?\s*=>`),
		ExtractAttribute: func(node Node) *AttributeInfo {
			// This would be implemented to extract Moose attribute info from AST
			return nil
		},
	}

	// Moo pattern
	d.FrameworkPatterns["Moo"] = &FrameworkPattern{
		Name:                  "Moo",
		UsePattern:            regexp.MustCompile(`use\s+Moo\s*;`),
		AttributePattern:      regexp.MustCompile(`has\s+['"]?(\w+)['"]?\s*=>\s*\(`),
		MethodModifierPattern: regexp.MustCompile(`(before|after|around)\s+['"]?(\w+)['"]?\s*=>`),
		ExtractAttribute: func(node Node) *AttributeInfo {
			// This would be implemented to extract Moo attribute info from AST
			return nil
		},
	}

	// Class::Tiny pattern
	d.FrameworkPatterns["Class::Tiny"] = &FrameworkPattern{
		Name:             "Class::Tiny",
		UsePattern:       regexp.MustCompile(`use\s+Class::Tiny\s+(?:qw\s*\()?\s*([^;)]+)`),
		AttributePattern: nil, // Class::Tiny declares attributes in the use statement
		ExtractAttribute: func(node Node) *AttributeInfo {
			// This would be implemented to extract Class::Tiny attribute info
			return nil
		},
	}
}

// NewDataStructureAnalyzer creates a new data structure analyzer
func NewDataStructureAnalyzer() *DataStructureAnalyzer {
	analyzer := &DataStructureAnalyzer{
		TypeInferenceRules: []TypeInferenceRule{},
	}

	// Add common type inference rules
	analyzer.addTypeInferenceRules()

	return analyzer
}

// addTypeInferenceRules adds common type inference rules
func (a *DataStructureAnalyzer) addTypeInferenceRules() {
	// Array reference pattern
	a.TypeInferenceRules = append(a.TypeInferenceRules, TypeInferenceRule{
		Name:    "array_ref",
		Pattern: regexp.MustCompile(`\$\w+\s*=\s*\[\s*`),
		InferType: func(match []string) string {
			return "ArrayRef"
		},
	})

	// Hash reference pattern
	a.TypeInferenceRules = append(a.TypeInferenceRules, TypeInferenceRule{
		Name:    "hash_ref",
		Pattern: regexp.MustCompile(`\$\w+\s*=\s*\{\s*`),
		InferType: func(match []string) string {
			return "HashRef"
		},
	})

	// DBI database handle pattern
	a.TypeInferenceRules = append(a.TypeInferenceRules, TypeInferenceRule{
		Name:    "dbi_handle",
		Pattern: regexp.MustCompile(`DBI->connect\s*\(`),
		InferType: func(match []string) string {
			return "DBI::db"
		},
	})
}

// IntrospectModule performs deep introspection on a Perl module
func (mi *ModuleIntrospector) IntrospectModule(path string) (*ModuleIntrospectionResult, error) {
	// Parse the module
	ast, err := mi.Parser.ParseFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to parse module: %w", err)
	}

	// Check for parse errors
	if len(ast.Errors) > 0 {
		return nil, fmt.Errorf("parse errors: %v", ast.Errors)
	}

	result := &ModuleIntrospectionResult{
		Path:        path,
		SymbolTable: mi.SymbolTable,
		Packages:    make(map[string]*PackageInfo),
		Errors:      []error{},
	}

	// Analyze the AST
	if ast.Root != nil {
		mi.analyzeNode(ast.Root, result)
	}

	// Detect OOP frameworks
	mi.detectOOPFrameworks(ast, result)

	// Analyze dynamic methods
	mi.analyzeDynamicMethods(ast, result)

	// Analyze data structures
	mi.analyzeDataStructures(ast, result)

	return result, nil
}

// analyzeNode recursively analyzes AST nodes
func (mi *ModuleIntrospector) analyzeNode(node Node, result *ModuleIntrospectionResult) {
	nodeType := node.Type()

	// For debugging - common node types in tree-sitter-perl
	switch nodeType {
	case "package_declaration", "package_statement":
		mi.analyzePackageDeclaration(node, result)
	case "sub_declaration", "method_declaration", "subroutine_declaration_statement":
		mi.analyzeSubroutineDeclaration(node, result)
	case "variable_declaration", "variable_declaration_statement":
		mi.analyzeVariableDeclaration(node, result)
	case "use_statement", "use_no_statement":
		mi.analyzeUseStatement(node, result)
	case "class_definition":
		mi.analyzeClassDefinition(node, result)
	}

	// Recursively analyze children
	for _, child := range node.Children() {
		mi.analyzeNode(child, result)
	}
}

// analyzePackageDeclaration analyzes a package declaration
func (mi *ModuleIntrospector) analyzePackageDeclaration(node Node, result *ModuleIntrospectionResult) {
	// Extract package name from the node
	packageName := mi.extractPackageName(node)
	if packageName == "" {
		return
	}

	// Create or get package symbols
	if _, exists := mi.SymbolTable.Packages[packageName]; !exists {
		mi.SymbolTable.Packages[packageName] = &PackageSymbols{
			Name:       packageName,
			Methods:    make(map[string]*MethodSignature),
			Attributes: make(map[string]*AttributeInfo),
			Constants:  make(map[string]interface{}),
		}
	}

	// Create package info for result
	result.Packages[packageName] = &PackageInfo{
		Name:       packageName,
		Methods:    make(map[string]*MethodSignature),
		Attributes: make(map[string]*AttributeInfo),
	}

	// Store current package for context
	result.currentPackage = packageName
}

// analyzeSubroutineDeclaration analyzes a subroutine declaration
func (mi *ModuleIntrospector) analyzeSubroutineDeclaration(node Node, result *ModuleIntrospectionResult) {
	// Extract method signature from the node
	signature := mi.extractMethodSignature(node)
	if signature == nil {
		return
	}

	// Determine the current package
	currentPackage := mi.getCurrentPackage(node)

	// Ensure package exists in symbol table
	if _, exists := mi.SymbolTable.Packages[currentPackage]; !exists {
		mi.SymbolTable.Packages[currentPackage] = &PackageSymbols{
			Name:       currentPackage,
			Methods:    make(map[string]*MethodSignature),
			Attributes: make(map[string]*AttributeInfo),
			Constants:  make(map[string]interface{}),
		}
	}

	// Ensure package exists in result
	if _, exists := result.Packages[currentPackage]; !exists {
		result.Packages[currentPackage] = &PackageInfo{
			Name:       currentPackage,
			Methods:    make(map[string]*MethodSignature),
			Attributes: make(map[string]*AttributeInfo),
		}
	}

	// Add to symbol table
	if pkg, exists := mi.SymbolTable.Packages[currentPackage]; exists {
		pkg.Methods[signature.Name] = signature
	}

	// Add to result
	if pkgInfo, exists := result.Packages[currentPackage]; exists {
		pkgInfo.Methods[signature.Name] = signature
	}
}

// Helper methods for extraction
func (mi *ModuleIntrospector) extractPackageName(node Node) string {
	// This would extract the package name from the AST node
	// For now, return a simple extraction based on node text
	text := node.Text()
	if strings.HasPrefix(text, "package ") {
		parts := strings.Fields(text)
		if len(parts) >= 2 {
			return strings.TrimSuffix(parts[1], ";")
		}
	}
	return ""
}

func (mi *ModuleIntrospector) extractMethodSignature(node Node) *MethodSignature {
	// This would extract method signature from the AST node
	// For now, return a basic signature
	text := node.Text()
	if strings.HasPrefix(text, "sub ") {
		parts := strings.Fields(text)
		if len(parts) >= 2 {
			methodName := parts[1]
			// Remove any opening parenthesis
			if idx := strings.Index(methodName, "("); idx > 0 {
				methodName = methodName[:idx]
			}

			return &MethodSignature{
				Name:       methodName,
				Parameters: []*ParameterInfo{},
				ReturnType: "Any",
				Source:     MethodSourceExplicit,
			}
		}
	}
	return nil
}

func (mi *ModuleIntrospector) getCurrentPackage(node Node) string {
	// For now, return "main" as default
	// In a full implementation, this would track package context through the AST
	return "main"
}

// analyzeVariableDeclaration analyzes variable declarations for type inference
func (mi *ModuleIntrospector) analyzeVariableDeclaration(node Node, result *ModuleIntrospectionResult) {
	text := node.Text()

	// Extract variable information
	if varInfo := mi.extractVariableInfo(node); varInfo != nil {
		// Add to symbol table
		mi.SymbolTable.GlobalVariables[varInfo.Name] = varInfo

		// Apply type inference rules
		for _, rule := range mi.DataStructureAnalyzer.TypeInferenceRules {
			if rule.Pattern.MatchString(text) {
				inferredType := rule.InferType(rule.Pattern.FindStringSubmatch(text))
				if inferredType != "" && varInfo.Type == "" {
					varInfo.Type = inferredType
				}
			}
		}
	}
}

func (mi *ModuleIntrospector) analyzeUseStatement(node Node, result *ModuleIntrospectionResult) {
	text := node.Text()

	// Extract use statement information
	if importInfo := mi.extractImportInfo(node); importInfo != nil {
		mi.SymbolTable.Imports[importInfo.ModuleName] = importInfo

		// Detect OOP frameworks from use statements
		if framework := mi.detectFrameworkFromUse(text); framework != "" {
			if !contains(mi.OOPPatternDetector.DetectedFrameworks, framework) {
				mi.OOPPatternDetector.DetectedFrameworks = append(mi.OOPPatternDetector.DetectedFrameworks, framework)
			}
			result.DetectedFrameworks = mi.OOPPatternDetector.DetectedFrameworks
		}
	}
}

func (mi *ModuleIntrospector) analyzeClassDefinition(node Node, result *ModuleIntrospectionResult) {
	// This handles explicit class definitions (for modern Perl OOP)
	if classInfo := mi.extractClassInfo(node); classInfo != nil {
		// Create or update package symbols
		_ = mi.getOrCreatePackage(classInfo.Name)

		// Add to result
		if result.Packages[classInfo.Name] == nil {
			result.Packages[classInfo.Name] = &PackageInfo{
				Name:       classInfo.Name,
				Methods:    make(map[string]*MethodSignature),
				Attributes: make(map[string]*AttributeInfo),
			}
		}

		// Copy class information
		pkgInfo := result.Packages[classInfo.Name]
		pkgInfo.ParentClasses = classInfo.ParentClasses
		pkgInfo.Roles = classInfo.Roles
	}
}

func (mi *ModuleIntrospector) detectOOPFrameworks(ast *AST, result *ModuleIntrospectionResult) {
	if ast.Root == nil {
		return
	}

	// Traverse AST to detect framework patterns
	mi.detectFrameworkPatternsInNode(ast.Root, result)

	// Add detected frameworks to result
	result.DetectedFrameworks = mi.OOPPatternDetector.DetectedFrameworks
}

func (mi *ModuleIntrospector) analyzeDynamicMethods(ast *AST, result *ModuleIntrospectionResult) {
	if ast.Root == nil {
		return
	}

	// Search for dynamic method generation patterns
	mi.findDynamicMethodsInNode(ast.Root, result)
}

func (mi *ModuleIntrospector) analyzeDataStructures(ast *AST, result *ModuleIntrospectionResult) {
	if ast.Root == nil {
		return
	}

	// Initialize data structures map if not present
	if result.DataStructures == nil {
		result.DataStructures = make(map[string]*DataStructureInfo)
	}

	// Analyze data structure patterns in the AST
	mi.analyzeDataStructuresInNode(ast.Root, result)
}

// ClassInfo represents extracted class information
type ClassInfo struct {
	Name          string
	ParentClasses []string
	Roles         []string
}

// Helper functions for extraction and analysis

// extractVariableInfo extracts variable information from AST node
func (mi *ModuleIntrospector) extractVariableInfo(node Node) *VariableInfo {
	text := node.Text()

	// Basic variable declaration patterns
	patterns := []struct {
		regex *regexp.Regexp
		scope string
	}{
		{regexp.MustCompile(`my\s+(\$\w+)`), "my"},
		{regexp.MustCompile(`our\s+(\$\w+)`), "our"},
		{regexp.MustCompile(`state\s+(\$\w+)`), "state"},
	}

	for _, pattern := range patterns {
		if matches := pattern.regex.FindStringSubmatch(text); len(matches) > 1 {
			varName := matches[1]

			// Extract initial value if present
			initialValue := ""
			if idx := strings.Index(text, "="); idx > 0 {
				remaining := strings.TrimSpace(text[idx+1:])
				if endIdx := strings.Index(remaining, ";"); endIdx > 0 {
					initialValue = strings.TrimSpace(remaining[:endIdx])
				} else {
					initialValue = remaining
				}
			}

			return &VariableInfo{
				Name:         varName,
				Type:         "", // Will be inferred
				Scope:        pattern.scope,
				InitialValue: initialValue,
			}
		}
	}

	return nil
}

// extractImportInfo extracts import information from use statement
func (mi *ModuleIntrospector) extractImportInfo(node Node) *ImportInfo {
	text := node.Text()

	// Pattern: use Module::Name qw(symbol1 symbol2);
	// Pattern: use Module::Name 'version';
	// Pattern: use Module::Name;
	usePattern := regexp.MustCompile(`use\s+([A-Za-z0-9:_]+)(?:\s+([^;]+))?`)

	if matches := usePattern.FindStringSubmatch(text); len(matches) > 1 {
		moduleName := matches[1]
		importInfo := &ImportInfo{
			ModuleName:      moduleName,
			ImportedSymbols: []string{},
			ImportAll:       false,
		}

		if len(matches) > 2 && matches[2] != "" {
			params := strings.TrimSpace(matches[2])

			// Check for version number
			if matched, _ := regexp.MatchString(`^['"]?[\d.]+['"]?$`, params); matched {
				importInfo.Version = strings.Trim(params, `'"`)
			} else if strings.Contains(params, "qw") {
				// Extract symbols from qw()
				qwPattern := regexp.MustCompile(`qw\s*\(\s*([^)]+)\s*\)`)
				if qwMatches := qwPattern.FindStringSubmatch(params); len(qwMatches) > 1 {
					symbols := strings.Fields(qwMatches[1])
					importInfo.ImportedSymbols = symbols
				}
			} else if params == ":all" {
				importInfo.ImportAll = true
			}
		}

		return importInfo
	}

	return nil
}

// extractClassInfo extracts class information for modern Perl OOP
func (mi *ModuleIntrospector) extractClassInfo(node Node) *ClassInfo {
	text := node.Text()

	// Modern class syntax (if supported by the parser)
	classPattern := regexp.MustCompile(`class\s+(\w+(?:::\w+)*)\s*(?:extends\s+([^{]+))?`)

	if matches := classPattern.FindStringSubmatch(text); len(matches) > 1 {
		className := matches[1]
		classInfo := &ClassInfo{
			Name:          className,
			ParentClasses: []string{},
			Roles:         []string{},
		}

		// Extract parent classes
		if len(matches) > 2 && matches[2] != "" {
			parents := strings.Split(strings.TrimSpace(matches[2]), ",")
			for _, parent := range parents {
				classInfo.ParentClasses = append(classInfo.ParentClasses, strings.TrimSpace(parent))
			}
		}

		return classInfo
	}

	return nil
}

// detectFrameworkFromUse detects OOP framework from use statement
func (mi *ModuleIntrospector) detectFrameworkFromUse(useText string) string {
	for frameworkName, pattern := range mi.OOPPatternDetector.FrameworkPatterns {
		if pattern.UsePattern.MatchString(useText) {
			return frameworkName
		}
	}
	return ""
}

// getOrCreatePackage gets or creates a package in the symbol table
func (mi *ModuleIntrospector) getOrCreatePackage(packageName string) *PackageSymbols {
	if pkg, exists := mi.SymbolTable.Packages[packageName]; exists {
		return pkg
	}

	pkg := &PackageSymbols{
		Name:       packageName,
		Methods:    make(map[string]*MethodSignature),
		Attributes: make(map[string]*AttributeInfo),
		Constants:  make(map[string]interface{}),
	}
	mi.SymbolTable.Packages[packageName] = pkg
	return pkg
}

// detectFrameworkPatternsInNode recursively detects framework patterns
func (mi *ModuleIntrospector) detectFrameworkPatternsInNode(node Node, result *ModuleIntrospectionResult) {
	text := node.Text()

	// Check for framework-specific patterns in this node
	for frameworkName, pattern := range mi.OOPPatternDetector.FrameworkPatterns {
		// Check use pattern
		if pattern.UsePattern != nil && pattern.UsePattern.MatchString(text) {
			if !contains(mi.OOPPatternDetector.DetectedFrameworks, frameworkName) {
				mi.OOPPatternDetector.DetectedFrameworks = append(mi.OOPPatternDetector.DetectedFrameworks, frameworkName)
			}
		}

		// Check attribute pattern (Moose/Moo 'has' declarations)
		if pattern.AttributePattern != nil && pattern.AttributePattern.MatchString(text) {
			if !contains(mi.OOPPatternDetector.DetectedFrameworks, frameworkName) {
				mi.OOPPatternDetector.DetectedFrameworks = append(mi.OOPPatternDetector.DetectedFrameworks, frameworkName)
			}

			// Extract attribute information
			mi.extractFrameworkAttribute(node, pattern, result)
		}

		// Check method modifier pattern
		if pattern.MethodModifierPattern != nil && pattern.MethodModifierPattern.MatchString(text) {
			if !contains(mi.OOPPatternDetector.DetectedFrameworks, frameworkName) {
				mi.OOPPatternDetector.DetectedFrameworks = append(mi.OOPPatternDetector.DetectedFrameworks, frameworkName)
			}
		}
	}

	// Recursively check children
	for _, child := range node.Children() {
		mi.detectFrameworkPatternsInNode(child, result)
	}
}

// findDynamicMethodsInNode finds dynamic method generation patterns
func (mi *ModuleIntrospector) findDynamicMethodsInNode(node Node, result *ModuleIntrospectionResult) {
	text := node.Text()

	// Check for method generator patterns
	for _, generator := range mi.MethodDetector.KnownGenerators {
		if generator.Pattern.MatchString(text) {
			matches := generator.Pattern.FindStringSubmatch(text)
			methodName := generator.ExtractMethodName(matches)

			if methodName != "" {
				// Create method signature
				signature := generator.InferSignature(matches)
				if signature != nil {
					// Determine current package
					currentPackage := mi.getCurrentPackageFromContext(node)

					// Add to result
					if result.Packages[currentPackage] == nil {
						result.Packages[currentPackage] = &PackageInfo{
							Name:       currentPackage,
							Methods:    make(map[string]*MethodSignature),
							Attributes: make(map[string]*AttributeInfo),
						}
					}

					signature.Name = methodName
					result.Packages[currentPackage].Methods[methodName] = signature
				}
			}
		}
	}

	// Recursively check children
	for _, child := range node.Children() {
		mi.findDynamicMethodsInNode(child, result)
	}
}

// analyzeDataStructuresInNode analyzes data structures in AST node
func (mi *ModuleIntrospector) analyzeDataStructuresInNode(node Node, result *ModuleIntrospectionResult) {
	text := node.Text()

	// Apply type inference rules to detect data structures
	for _, rule := range mi.DataStructureAnalyzer.TypeInferenceRules {
		if rule.Pattern.MatchString(text) {
			matches := rule.Pattern.FindStringSubmatch(text)
			inferredType := rule.InferType(matches)

			if inferredType != "" {
				// Try to extract variable name
				varName := mi.extractVariableNameFromText(text)
				if varName != "" {
					result.DataStructures[varName] = &DataStructureInfo{
						Name:      varName,
						Type:      inferredType,
						Structure: text, // Store the actual structure for analysis
					}
				}
			}
		}
	}

	// Recursively check children
	for _, child := range node.Children() {
		mi.analyzeDataStructuresInNode(child, result)
	}
}

// extractFrameworkAttribute extracts attribute information from framework patterns
func (mi *ModuleIntrospector) extractFrameworkAttribute(node Node, pattern *FrameworkPattern, result *ModuleIntrospectionResult) {
	text := node.Text()

	// Moose/Moo attribute pattern: has 'attr_name' => (...)
	attrPattern := regexp.MustCompile(`has\s+['"]?(\w+)['"]?\s*=>`)
	if matches := attrPattern.FindStringSubmatch(text); len(matches) > 1 {
		attrName := matches[1]

		// Determine current package
		currentPackage := mi.getCurrentPackageFromContext(node)

		// Ensure package exists in result
		if result.Packages[currentPackage] == nil {
			result.Packages[currentPackage] = &PackageInfo{
				Name:       currentPackage,
				Methods:    make(map[string]*MethodSignature),
				Attributes: make(map[string]*AttributeInfo),
			}
		}

		// Create attribute info
		attrInfo := &AttributeInfo{
			Name:          attrName,
			Type:          "Any", // Default, could be enhanced by parsing the attribute definition
			Documentation: "",
		}

		// Try to extract type information from the attribute definition
		if typeMatch := regexp.MustCompile(`isa\s*=>\s*['"]?([^'",\s]+)['"]?`).FindStringSubmatch(text); len(typeMatch) > 1 {
			attrInfo.Type = typeMatch[1]
		}

		// Check for required/optional
		if strings.Contains(text, "required") && strings.Contains(text, "1") {
			attrInfo.IsRequired = true
		}

		// Check for default value
		if defaultMatch := regexp.MustCompile(`default\s*=>\s*(.+?)(?:,|\))`).FindStringSubmatch(text); len(defaultMatch) > 1 {
			attrInfo.HasDefault = true
			attrInfo.DefaultValue = strings.TrimSpace(defaultMatch[1])
		}

		result.Packages[currentPackage].Attributes[attrName] = attrInfo
	}
}

// getCurrentPackageFromContext determines current package from AST context
func (mi *ModuleIntrospector) getCurrentPackageFromContext(node Node) string {
	// In a full implementation, this would traverse up the AST to find the current package
	// For now, return "main" as default
	return "main"
}

// extractVariableNameFromText extracts variable name from text
func (mi *ModuleIntrospector) extractVariableNameFromText(text string) string {
	// Look for variable patterns
	patterns := []*regexp.Regexp{
		regexp.MustCompile(`my\s+(\$\w+)`),
		regexp.MustCompile(`our\s+(\$\w+)`),
		regexp.MustCompile(`(\$\w+)\s*=`),
	}

	for _, pattern := range patterns {
		if matches := pattern.FindStringSubmatch(text); len(matches) > 1 {
			return matches[1]
		}
	}

	return ""
}

// contains checks if a slice contains a string
func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}

// ModuleIntrospectionResult represents the result of module introspection
type ModuleIntrospectionResult struct {
	// Path is the module file path
	Path string

	// SymbolTable contains all discovered symbols
	SymbolTable *SymbolTable

	// Packages maps package names to their information
	Packages map[string]*PackageInfo

	// DetectedFrameworks lists detected OOP frameworks
	DetectedFrameworks []string

	// DataStructures contains analyzed data structure information
	DataStructures map[string]*DataStructureInfo

	// Errors contains any errors encountered during introspection
	Errors []error

	// currentPackage tracks the current package context during analysis
	currentPackage string
}

// PackageInfo contains information about a package
type PackageInfo struct {
	// Name is the package name
	Name string

	// Methods contains all methods in the package
	Methods map[string]*MethodSignature

	// Attributes contains all attributes
	Attributes map[string]*AttributeInfo

	// ParentClasses lists parent classes
	ParentClasses []string

	// Roles lists consumed roles
	Roles []string
}

// DataStructureInfo represents analyzed data structure information
type DataStructureInfo struct {
	// Name is the variable name
	Name string

	// Type is the inferred type
	Type string

	// Structure describes the data structure
	Structure interface{}
}
