// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package parser

import (
	"io"
	"sync"

	"tamarou.com/pvm/internal/ast"
)

// Ensure, that ParserMock does implement Parser.
// If this is not the case, regenerate this file with moq.
var _ Parser = &ParserMock{}

// ParserMock is a mock implementation of Parser.
//
//	func TestSomethingThatUsesParser(t *testing.T) {
//
//		// make and configure a mocked Parser
//		mockedParser := &ParserMock{
//			ParseFileFunc: func(path string) (*ast.AST, error) {
//				panic("mock out the ParseFile method")
//			},
//			ParseReaderFunc: func(reader io.Reader) (*ast.AST, error) {
//				panic("mock out the ParseReader method")
//			},
//			ParseStringFunc: func(content string) (*ast.AST, error) {
//				panic("mock out the ParseString method")
//			},
//		}
//
//		// use mockedParser in code that requires Parser
//		// and then make assertions.
//
//	}
type ParserMock struct {
	// ParseFileFunc mocks the ParseFile method.
	ParseFileFunc func(path string) (*ast.AST, error)

	// ParseReaderFunc mocks the ParseReader method.
	ParseReaderFunc func(reader io.Reader) (*ast.AST, error)

	// ParseStringFunc mocks the ParseString method.
	ParseStringFunc func(content string) (*ast.AST, error)

	// calls tracks calls to the methods.
	calls struct {
		// ParseFile holds details about calls to the ParseFile method.
		ParseFile []struct {
			// Path is the path argument value.
			Path string
		}
		// ParseReader holds details about calls to the ParseReader method.
		ParseReader []struct {
			// Reader is the reader argument value.
			Reader io.Reader
		}
		// ParseString holds details about calls to the ParseString method.
		ParseString []struct {
			// Content is the content argument value.
			Content string
		}
	}
	lockParseFile   sync.RWMutex
	lockParseReader sync.RWMutex
	lockParseString sync.RWMutex
}

// ParseFile calls ParseFileFunc.
func (mock *ParserMock) ParseFile(path string) (*ast.AST, error) {
	if mock.ParseFileFunc == nil {
		panic("ParserMock.ParseFileFunc: method is nil but Parser.ParseFile was just called")
	}
	callInfo := struct {
		Path string
	}{
		Path: path,
	}
	mock.lockParseFile.Lock()
	mock.calls.ParseFile = append(mock.calls.ParseFile, callInfo)
	mock.lockParseFile.Unlock()
	return mock.ParseFileFunc(path)
}

// ParseFileCalls gets all the calls that were made to ParseFile.
// Check the length with:
//
//	len(mockedParser.ParseFileCalls())
func (mock *ParserMock) ParseFileCalls() []struct {
	Path string
} {
	var calls []struct {
		Path string
	}
	mock.lockParseFile.RLock()
	calls = mock.calls.ParseFile
	mock.lockParseFile.RUnlock()
	return calls
}

// ParseReader calls ParseReaderFunc.
func (mock *ParserMock) ParseReader(reader io.Reader) (*ast.AST, error) {
	if mock.ParseReaderFunc == nil {
		panic("ParserMock.ParseReaderFunc: method is nil but Parser.ParseReader was just called")
	}
	callInfo := struct {
		Reader io.Reader
	}{
		Reader: reader,
	}
	mock.lockParseReader.Lock()
	mock.calls.ParseReader = append(mock.calls.ParseReader, callInfo)
	mock.lockParseReader.Unlock()
	return mock.ParseReaderFunc(reader)
}

// ParseReaderCalls gets all the calls that were made to ParseReader.
// Check the length with:
//
//	len(mockedParser.ParseReaderCalls())
func (mock *ParserMock) ParseReaderCalls() []struct {
	Reader io.Reader
} {
	var calls []struct {
		Reader io.Reader
	}
	mock.lockParseReader.RLock()
	calls = mock.calls.ParseReader
	mock.lockParseReader.RUnlock()
	return calls
}

// ParseString calls ParseStringFunc.
func (mock *ParserMock) ParseString(content string) (*ast.AST, error) {
	if mock.ParseStringFunc == nil {
		panic("ParserMock.ParseStringFunc: method is nil but Parser.ParseString was just called")
	}
	callInfo := struct {
		Content string
	}{
		Content: content,
	}
	mock.lockParseString.Lock()
	mock.calls.ParseString = append(mock.calls.ParseString, callInfo)
	mock.lockParseString.Unlock()
	return mock.ParseStringFunc(content)
}

// ParseStringCalls gets all the calls that were made to ParseString.
// Check the length with:
//
//	len(mockedParser.ParseStringCalls())
func (mock *ParserMock) ParseStringCalls() []struct {
	Content string
} {
	var calls []struct {
		Content string
	}
	mock.lockParseString.RLock()
	calls = mock.calls.ParseString
	mock.lockParseString.RUnlock()
	return calls
}
