// Code generated by generate_diagnostics.go; DO NOT EDIT.
// This file is generated from diagnostic definitions - edit the source config instead.

package diagnostics

import (
	"fmt"
)

// Generated diagnostic IDs for PSC
const (
	PSCTYPE_MISMATCH       = "TYPE_MISMATCH"       // Type mismatch in assignment
	PSCUNDEFINED_VARIABLE  = "UNDEFINED_VARIABLE"  // Undefined variable
	PSCUNUSED_VARIABLE     = "UNUSED_VARIABLE"     // Unused variable
	PSCVARIABLE_SHADOWING  = "VARIABLE_SHADOWING"  // Variable shadowing
	PSCINVALID_TYPE_SYNTAX = "INVALID_TYPE_SYNTAX" // Invalid type syntax
	PSCDEPRECATED_SYNTAX   = "DEPRECATED_SYNTAX"   // Deprecated syntax
	PSCPERFORMANCE_HINT    = "PERFORMANCE_HINT"    // Performance optimization available
)

// DiagnosticSeverity represents the severity of a diagnostic
type DiagnosticSeverity string

const (
	SeverityError   DiagnosticSeverity = "error"
	SeverityWarning DiagnosticSeverity = "warning"
	SeverityInfo    DiagnosticSeverity = "info"
	SeverityHint    DiagnosticSeverity = "hint"
)

// GeneratedDiagnostic represents a diagnostic message
type GeneratedDiagnostic struct {
	ID       string
	Severity DiagnosticSeverity
	Category string
	Message  string
	Location string
	Range    *Range
}

// Range represents a location range in source code
type Range struct {
	Start Position
	End   Position
}

// Position represents a position in source code
type Position struct {
	Line   int
	Column int
}

// Generated diagnostic constructors

// NewPSCTYPE_MISMATCHDiagnostic creates a new TYPE_MISMATCH diagnostic
func NewPSCTYPE_MISMATCHDiagnostic(location string, args ...interface{}) *GeneratedDiagnostic {
	template := "Variable '%s' declared as %s but assigned %s at line %d"
	message := "Type mismatch in assignment"
	if len(args) > 0 {
		message = fmt.Sprintf(template, args...)
	}

	return &GeneratedDiagnostic{
		ID:       "TYPE_MISMATCH",
		Severity: SeverityError,
		Category: "Type Checking",
		Message:  message,
		Location: location,
	}
}

// NewPSCUNDEFINED_VARIABLEDiagnostic creates a new UNDEFINED_VARIABLE diagnostic
func NewPSCUNDEFINED_VARIABLEDiagnostic(location string, args ...interface{}) *GeneratedDiagnostic {
	template := "Variable '%s' used before declaration at line %d"
	message := "Undefined variable"
	if len(args) > 0 {
		message = fmt.Sprintf(template, args...)
	}

	return &GeneratedDiagnostic{
		ID:       "UNDEFINED_VARIABLE",
		Severity: SeverityError,
		Category: "Symbol Resolution",
		Message:  message,
		Location: location,
	}
}

// NewPSCUNUSED_VARIABLEDiagnostic creates a new UNUSED_VARIABLE diagnostic
func NewPSCUNUSED_VARIABLEDiagnostic(location string, args ...interface{}) *GeneratedDiagnostic {
	template := "Variable '%s' declared but never used at line %d"
	message := "Unused variable"
	if len(args) > 0 {
		message = fmt.Sprintf(template, args...)
	}

	return &GeneratedDiagnostic{
		ID:       "UNUSED_VARIABLE",
		Severity: SeverityWarning,
		Category: "Code Quality",
		Message:  message,
		Location: location,
	}
}

// NewPSCVARIABLE_SHADOWINGDiagnostic creates a new VARIABLE_SHADOWING diagnostic
func NewPSCVARIABLE_SHADOWINGDiagnostic(location string, args ...interface{}) *GeneratedDiagnostic {
	template := "Variable '%s' shadows outer scope variable declared at line %d"
	message := "Variable shadowing"
	if len(args) > 0 {
		message = fmt.Sprintf(template, args...)
	}

	return &GeneratedDiagnostic{
		ID:       "VARIABLE_SHADOWING",
		Severity: SeverityWarning,
		Category: "Code Quality",
		Message:  message,
		Location: location,
	}
}

// NewPSCINVALID_TYPE_SYNTAXDiagnostic creates a new INVALID_TYPE_SYNTAX diagnostic
func NewPSCINVALID_TYPE_SYNTAXDiagnostic(location string, args ...interface{}) *GeneratedDiagnostic {
	template := "Invalid type expression '%s' at line %d: %s"
	message := "Invalid type syntax"
	if len(args) > 0 {
		message = fmt.Sprintf(template, args...)
	}

	return &GeneratedDiagnostic{
		ID:       "INVALID_TYPE_SYNTAX",
		Severity: SeverityError,
		Category: "Type Parsing",
		Message:  message,
		Location: location,
	}
}

// NewPSCDEPRECATED_SYNTAXDiagnostic creates a new DEPRECATED_SYNTAX diagnostic
func NewPSCDEPRECATED_SYNTAXDiagnostic(location string, args ...interface{}) *GeneratedDiagnostic {
	template := "Deprecated syntax '%s' at line %d, use '%s' instead"
	message := "Deprecated syntax"
	if len(args) > 0 {
		message = fmt.Sprintf(template, args...)
	}

	return &GeneratedDiagnostic{
		ID:       "DEPRECATED_SYNTAX",
		Severity: SeverityWarning,
		Category: "Code Style",
		Message:  message,
		Location: location,
	}
}

// NewPSCPERFORMANCE_HINTDiagnostic creates a new PERFORMANCE_HINT diagnostic
func NewPSCPERFORMANCE_HINTDiagnostic(location string, args ...interface{}) *GeneratedDiagnostic {
	template := "Consider using %s instead of %s for better performance at line %d"
	message := "Performance optimization available"
	if len(args) > 0 {
		message = fmt.Sprintf(template, args...)
	}

	return &GeneratedDiagnostic{
		ID:       "PERFORMANCE_HINT",
		Severity: SeverityHint,
		Category: "Performance",
		Message:  message,
		Location: location,
	}
}

// Diagnostic formatting functions

// FormatPSCTYPE_MISMATCH formats a TYPE_MISMATCH diagnostic message
func FormatPSCTYPE_MISMATCH(args ...interface{}) string {
	template := "Variable '%s' declared as %s but assigned %s at line %d"
	return fmt.Sprintf(template, args...)
}

// FormatPSCUNDEFINED_VARIABLE formats a UNDEFINED_VARIABLE diagnostic message
func FormatPSCUNDEFINED_VARIABLE(args ...interface{}) string {
	template := "Variable '%s' used before declaration at line %d"
	return fmt.Sprintf(template, args...)
}

// FormatPSCUNUSED_VARIABLE formats a UNUSED_VARIABLE diagnostic message
func FormatPSCUNUSED_VARIABLE(args ...interface{}) string {
	template := "Variable '%s' declared but never used at line %d"
	return fmt.Sprintf(template, args...)
}

// FormatPSCVARIABLE_SHADOWING formats a VARIABLE_SHADOWING diagnostic message
func FormatPSCVARIABLE_SHADOWING(args ...interface{}) string {
	template := "Variable '%s' shadows outer scope variable declared at line %d"
	return fmt.Sprintf(template, args...)
}

// FormatPSCINVALID_TYPE_SYNTAX formats a INVALID_TYPE_SYNTAX diagnostic message
func FormatPSCINVALID_TYPE_SYNTAX(args ...interface{}) string {
	template := "Invalid type expression '%s' at line %d: %s"
	return fmt.Sprintf(template, args...)
}

// FormatPSCDEPRECATED_SYNTAX formats a DEPRECATED_SYNTAX diagnostic message
func FormatPSCDEPRECATED_SYNTAX(args ...interface{}) string {
	template := "Deprecated syntax '%s' at line %d, use '%s' instead"
	return fmt.Sprintf(template, args...)
}

// FormatPSCPERFORMANCE_HINT formats a PERFORMANCE_HINT diagnostic message
func FormatPSCPERFORMANCE_HINT(args ...interface{}) string {
	template := "Consider using %s instead of %s for better performance at line %d"
	return fmt.Sprintf(template, args...)
}
