// ABOUTME: Diagnostic message generation tool for PVM ecosystem
// ABOUTME: Generates structured diagnostic message definitions with formatting

//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"
	"text/template"
)

// DiagnosticDefinition represents a diagnostic message definition
type DiagnosticDefinition struct {
	ID          string `json:"id"`
	Component   string `json:"component"`
	Severity    string `json:"severity"`
	Category    string `json:"category"`
	Message     string `json:"message"`
	Template    string `json:"template"`
	Description string `json:"description"`
	Examples    []struct {
		Input  string `json:"input"`
		Output string `json:"output"`
	} `json:"examples"`
}

// DiagnosticConfig represents the configuration file structure
type DiagnosticConfig struct {
	Diagnostics []DiagnosticDefinition `json:"diagnostics"`
}

// Templates for code generation
const diagnosticTemplate = `// Code generated by generate_diagnostics.go; DO NOT EDIT.
// This file is generated from diagnostic definitions - edit the source config instead.

package diagnostics

import (
	"fmt"
)

// Generated diagnostic IDs for {{ .Component }}
const (
{{- range .Diagnostics }}
	{{ .Component }}{{ .ID }} = "{{ .ID }}" // {{ .Message }}
{{- end }}
)

// DiagnosticSeverity represents the severity of a diagnostic
type DiagnosticSeverity string

const (
	SeverityError   DiagnosticSeverity = "error"
	SeverityWarning DiagnosticSeverity = "warning"
	SeverityInfo    DiagnosticSeverity = "info"
	SeverityHint    DiagnosticSeverity = "hint"
)

// GeneratedDiagnostic represents a diagnostic message
type GeneratedDiagnostic struct {
	ID       string
	Severity DiagnosticSeverity
	Category string
	Message  string
	Location string
	Range    *Range
}

// Range represents a location range in source code
type Range struct {
	Start Position
	End   Position
}

// Position represents a position in source code
type Position struct {
	Line   int
	Column int
}

// Generated diagnostic constructors
{{- range .Diagnostics }}

// New{{ .Component }}{{ .ID }}Diagnostic creates a new {{ .ID }} diagnostic
func New{{ .Component }}{{ .ID }}Diagnostic(location string, args ...interface{}) *GeneratedDiagnostic {
	template := "{{ .Template }}"
	message := "{{ .Message }}"
	if len(args) > 0 {
		message = fmt.Sprintf(template, args...)
	}

	return &GeneratedDiagnostic{
		ID:       "{{ .ID }}",
		Severity: Severity{{ .Severity }},
		Category: "{{ .Category }}",
		Message:  message,
		Location: location,
	}
}
{{- end }}

// Diagnostic formatting functions
{{- range .Diagnostics }}

// Format{{ .Component }}{{ .ID }} formats a {{ .ID }} diagnostic message
func Format{{ .Component }}{{ .ID }}(args ...interface{}) string {
	template := "{{ .Template }}"
	return fmt.Sprintf(template, args...)
}
{{- end }}
`

func main() {
	if len(os.Args) < 2 {
		log.Fatal("Usage: generate_diagnostics <config-file>")
	}

	configFile := os.Args[1]

	// Read configuration file
	data, err := os.ReadFile(configFile)
	if err != nil {
		log.Fatalf("Failed to read config file: %v", err)
	}

	var config DiagnosticConfig
	if err := json.Unmarshal(data, &config); err != nil {
		log.Fatalf("Failed to parse config file: %v", err)
	}

	// Group diagnostics by component
	componentDiagnostics := make(map[string][]DiagnosticDefinition)
	for _, diagDef := range config.Diagnostics {
		componentDiagnostics[diagDef.Component] = append(componentDiagnostics[diagDef.Component], diagDef)
	}

	// Generate files for each component
	tmpl, err := template.New("diagnostic").Parse(diagnosticTemplate)
	if err != nil {
		log.Fatalf("Failed to parse template: %v", err)
	}

	for component, diagnostics := range componentDiagnostics {
		// Create output file in the same directory as the caller
		outputFile := strings.ToLower(component) + "_generated.go"

		func() {
			file, err := os.Create(outputFile)
			if err != nil {
				log.Fatalf("Failed to create output file: %v", err)
			}
			defer func() {
				if err := file.Close(); err != nil {
					log.Printf("Warning: failed to close file: %v", err)
				}
			}()

			// Generate code
			data := struct {
				Component   string
				Diagnostics []DiagnosticDefinition
			}{
				Component:   component,
				Diagnostics: diagnostics,
			}

			if err := tmpl.Execute(file, data); err != nil {
				log.Fatalf("Failed to execute template: %v", err)
			}
		}()

		fmt.Printf("Generated %s\n", outputFile)
	}
}
