// ABOUTME: Error code generation tool for PVM ecosystem
// ABOUTME: Generates structured error definitions from YAML configurations

//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"strings"
	"text/template"
)

// ErrorDefinition represents an error code definition
type ErrorDefinition struct {
	Code        string `json:"code"`
	Component   string `json:"component"`
	Category    string `json:"category"`
	Message     string `json:"message"`
	Description string `json:"description"`
	Hint        string `json:"hint"`
}

// ErrorConfig represents the configuration file structure
type ErrorConfig struct {
	Errors []ErrorDefinition `json:"errors"`
}

// Templates for code generation
const errorCodeTemplate = `// Code generated by generate_errors.go; DO NOT EDIT.
// This file is generated from error definitions - edit the source config instead.

package errors

// Generated error codes for {{ .Component }}
const (
{{- range .Errors }}
	{{ .Component }}{{ .Code }} = "{{ .Code }}" // {{ .Message }}
{{- end }}
)

// Generated error constructors
{{- range .Errors }}

// New{{ .Component }}{{ .Code }}Error creates a new {{ .Code }} error
func New{{ .Component }}{{ .Code }}Error(detail string, location string) *Error {
	return &Error{
		prefix:   "{{ .Component }}",
		category: "{{ .Category }}",
		code:     "{{ .Code }}",
		message:  "{{ .Message }}",
		detail:   detail,
		location: location,
		hint:     "{{ .Hint }}",
	}
}
{{- end }}
`

func main() {
	if len(os.Args) < 2 {
		log.Fatal("Usage: generate_errors <config-file>")
	}

	configFile := os.Args[1]

	// Read configuration file
	data, err := os.ReadFile(configFile)
	if err != nil {
		log.Fatalf("Failed to read config file: %v", err)
	}

	var config ErrorConfig
	if err := json.Unmarshal(data, &config); err != nil {
		log.Fatalf("Failed to parse config file: %v", err)
	}

	// Group errors by component
	componentErrors := make(map[string][]ErrorDefinition)
	for _, errDef := range config.Errors {
		componentErrors[errDef.Component] = append(componentErrors[errDef.Component], errDef)
	}

	// Generate files for each component
	tmpl, err := template.New("error").Parse(errorCodeTemplate)
	if err != nil {
		log.Fatalf("Failed to parse template: %v", err)
	}

	for component, errors := range componentErrors {
		// Create output file in the same directory as the caller
		outputFile := strings.ToLower(component) + "_generated.go"

		file, err := os.Create(outputFile)
		if err != nil {
			log.Fatalf("Failed to create output file: %v", err)
		}
		defer file.Close()

		// Generate code
		data := struct {
			Component string
			Errors    []ErrorDefinition
		}{
			Component: component,
			Errors:    errors,
		}

		if err := tmpl.Execute(file, data); err != nil {
			log.Fatalf("Failed to execute template: %v", err)
		}

		fmt.Printf("Generated %s\n", outputFile)
	}
}
