// ABOUTME: End-to-end tests for PVM shim functionality
// ABOUTME: Tests shim creation, execution, and rehashing

package e2e

import (
	"testing"

	"tamarou.com/pvm/test/e2e/helpers"
)

// TestShimCreation tests the creation of shims
func TestShimCreation(t *testing.T) {
	env := helpers.NewTestEnv(t)
	defer env.Cleanup()

	// Initially, no shims should exist
	helpers.AssertFileDoesNotExist(t, env.PVMShimsDir+"/perl", "perl shim should not exist initially")

	// Run rehash to create shims
	helpers.AssertPVMSucceedsOrSkipTODO(t, env, []string{"rehash"}, "Shim creation via rehash")

	// Check that shims were created
	helpers.AssertShimExists(t, env, "perl", "perl shim not created")
	helpers.AssertShimExists(t, env, "cpan", "cpan shim not created")

	// Check that shims are executable
	helpers.AssertFileExists(t, env.PVMShimsDir+"/perl", "perl shim file should exist")

	// Check shim content
	helpers.AssertFileContains(t, env.PVMShimsDir+"/perl", "Generated by PVM", "perl shim should be generated by PVM")
	helpers.AssertFileContains(t, env.PVMShimsDir+"/perl", "exec", "perl shim should contain exec command")
}

// TestShimExecutable tests that shims are executable
func TestShimExecutable(t *testing.T) {
	env := helpers.NewTestEnv(t)
	defer env.Cleanup()

	// Create shims first
	helpers.AssertPVMSucceedsOrSkipTODO(t, env, []string{"rehash"}, "Shim creation via rehash")

	// Check that perl shim exists and is executable
	perlShimPath := env.PVMShimsDir + "/perl"
	helpers.AssertFileExists(t, perlShimPath, "perl shim should exist")

	// Try to execute the shim (this will fail because no Perl is installed)
	// but we should get the expected error message from the shim
	stdout, stderr, err := env.RunCommand(perlShimPath, "--version")

	if err == nil {
		// If no error, shim worked and found a Perl to execute
		t.Logf("Shim executed successfully: %s", stdout)
	} else {
		// Should contain error message from shim or resolution system
		errorOutput := stderr + stdout
		if len(errorOutput) > 0 {
			t.Logf("Shim executed with expected error: %s", errorOutput)
		} else {
			t.Errorf("Shim execution failed silently: %v", err)
		}
	}
}

// TestShimPathPriority tests that shims take priority in PATH
func TestShimPathPriority(t *testing.T) {
	helpers.SkipTODO(t, "Shim PATH priority functionality")
}

// TestRehashCommand tests the rehash command
func TestRehashCommand(t *testing.T) {
	env := helpers.NewTestEnv(t)
	defer env.Cleanup()

	// Run the rehash command
	stdout := helpers.AssertPVMSucceedsOrSkipTODO(t, env, []string{"rehash"}, "Rehash command functionality")

	// Check that it reports success
	helpers.AssertStringContains(t, stdout, "Shim executables rebuilt successfully",
		"Rehash command output does not indicate success")

	// Check that standard shims were created
	helpers.AssertShimExists(t, env, "perl", "perl shim not created")
	helpers.AssertShimExists(t, env, "cpan", "cpan shim not created")
	helpers.AssertShimExists(t, env, "prove", "prove shim not created")
	helpers.AssertShimExists(t, env, "perldoc", "perldoc shim not created")
}

// TestShimVersionResolution tests that shims use the correct Perl version
func TestShimVersionResolution(t *testing.T) {
	helpers.SkipTODO(t, "Shim version resolution functionality")
}
