// ABOUTME: End-to-end tests for PVM shim functionality
// ABOUTME: Tests shim creation, execution, and rehashing

package e2e

import (
	"testing"

	"tamarou.com/pvm/test/e2e/helpers"
)

// TestShimCreation tests the creation of shims
func TestShimCreation(t *testing.T) {
	env := helpers.NewTestEnv(t)
	defer env.Cleanup()

	// Initially, no shims should exist
	helpers.AssertFileDoesNotExist(t, env.PVMShimsDir+"/perl", "perl shim should not exist initially")

	// Run rehash to create shims
	helpers.AssertPVMSucceedsOrSkipTODO(t, env, []string{"rehash"}, "Shim creation via rehash")

	// Check that shims were created
	helpers.AssertShimExists(t, env, "perl", "perl shim not created")
	helpers.AssertShimExists(t, env, "cpan", "cpan shim not created")

	// Check that shims are executable
	helpers.AssertFileExists(t, env.PVMShimsDir+"/perl", "perl shim file should exist")

	// Check shim content
	helpers.AssertFileContains(t, env.PVMShimsDir+"/perl", "Generated by PVM", "perl shim should be generated by PVM")
	helpers.AssertFileContains(t, env.PVMShimsDir+"/perl", "exec", "perl shim should contain exec command")
}

// TestShimExecutable tests that shims are executable
func TestShimExecutable(t *testing.T) {
	env := helpers.NewTestEnv(t)
	defer env.Cleanup()

	// Create shims first
	helpers.AssertPVMSucceedsOrSkipTODO(t, env, []string{"rehash"}, "Shim creation via rehash")

	// Check that perl shim exists and is executable
	perlShimPath := env.PVMShimsDir + "/perl"
	helpers.AssertFileExists(t, perlShimPath, "perl shim should exist")

	// Try to execute the shim (this will fail because no Perl is installed)
	// but we should get the expected error message from the shim
	stdout, stderr, err := env.RunCommand(perlShimPath, "--version")

	if err == nil {
		// If no error, shim worked and found a Perl to execute
		t.Logf("Shim executed successfully: %s", stdout)
	} else {
		// Should contain error message from shim or resolution system
		errorOutput := stderr + stdout
		if len(errorOutput) > 0 {
			t.Logf("Shim executed with expected error: %s", errorOutput)
		} else {
			t.Errorf("Shim execution failed silently: %v", err)
		}
	}
}

// TestShimPathPriority tests that shims take priority in PATH
func TestShimPathPriority(t *testing.T) {
	env := helpers.NewTestEnv(t)
	defer env.Cleanup()

	// Create shims first
	helpers.AssertPVMSucceedsOrSkipTODO(t, env, []string{"rehash"}, "Shim creation via rehash")

	// Check that perl shim exists (this also validates the shims directory exists)
	perlShimPath := env.PVMShimsDir + "/perl"
	helpers.AssertFileExists(t, perlShimPath, "perl shim should exist")

	// Check shim content to ensure it's properly generated
	helpers.AssertFileContains(t, perlShimPath, "Generated by PVM", "perl shim should be generated by PVM")
	helpers.AssertFileContains(t, perlShimPath, "exec", "perl shim should call exec")

	// Test that the shim can be executed (even if it fails due to no Perl installation)
	// The important thing is that the shim itself is found and executed
	stdout, stderr, err := env.RunCommand(perlShimPath, "--version")

	// We expect this to fail since no Perl is installed, but the shim should execute
	// and give us a meaningful error message
	if err != nil {
		errorOutput := stdout + stderr
		// Should contain either version info (if Perl found) or error from PVM
		if len(errorOutput) == 0 {
			t.Errorf("Shim executed but produced no output. This suggests PATH priority issue.")
		} else {
			t.Logf("Shim executed and produced expected output/error: %s", errorOutput)
		}
	} else {
		// If successful, shim found and executed Perl correctly
		t.Logf("Shim executed successfully, PATH priority working: %s", stdout)
	}
}

// TestRehashCommand tests the rehash command
func TestRehashCommand(t *testing.T) {
	env := helpers.NewTestEnv(t)
	defer env.Cleanup()

	// Run the rehash command
	stdout := helpers.AssertPVMSucceedsOrSkipTODO(t, env, []string{"rehash"}, "Rehash command functionality")

	// Check that it reports success
	helpers.AssertStringContains(t, stdout, "Shim executables rebuilt successfully",
		"Rehash command output does not indicate success")

	// Check that standard shims were created
	helpers.AssertShimExists(t, env, "perl", "perl shim not created")
	helpers.AssertShimExists(t, env, "cpan", "cpan shim not created")
	helpers.AssertShimExists(t, env, "prove", "prove shim not created")
	helpers.AssertShimExists(t, env, "perldoc", "perldoc shim not created")
}

// TestShimVersionResolution tests that shims use the correct Perl version
func TestShimVersionResolution(t *testing.T) {
	env := helpers.NewTestEnv(t)
	defer env.Cleanup()

	// Create shims first
	helpers.AssertPVMSucceedsOrSkipTODO(t, env, []string{"rehash"}, "Shim creation via rehash")

	// Check that perl shim exists
	perlShimPath := env.PVMShimsDir + "/perl"
	helpers.AssertFileExists(t, perlShimPath, "perl shim should exist")

	// Verify the shim calls the correct PVM exec command
	helpers.AssertFileContains(t, perlShimPath, "exec", "perl shim should call exec")

	// Test shim execution for version resolution
	// Even without Perl installed, the shim should properly delegate to PVM
	stdout, stderr, err := env.RunCommand(perlShimPath, "--version")

	if err != nil {
		// Expected behavior when no Perl is installed
		errorOutput := stdout + stderr

		// The error should come from PVM's version resolution system
		// Look for indicators that PVM's resolution system was invoked
		if len(errorOutput) > 0 {
			t.Logf("Shim version resolution working - PVM produced: %s", errorOutput)

			// Could contain messages about:
			// - No Perl versions installed
			// - Version resolution failures
			// - Configuration issues
			// The key is that PVM was invoked and handled the request
		} else {
			t.Errorf("Shim version resolution failed - no output from PVM resolution system")
		}
	} else {
		// If successful, it means a Perl was found and executed
		t.Logf("Shim version resolution successful - found and executed Perl: %s", stdout)
	}

	// Test that shim properly forwards arguments
	// Test with a simple argument that should be passed through
	stdout2, stderr2, err2 := env.RunCommand(perlShimPath, "-e", "print 'test'")

	if err2 != nil {
		// Expected when no Perl is installed, but args should be forwarded to PVM
		errorOutput2 := stdout2 + stderr2
		t.Logf("Shim argument forwarding test - PVM handled arguments: %s", errorOutput2)
	} else {
		// If successful, Perl executed the code
		helpers.AssertStringContains(t, stdout2, "test", "Shim should forward arguments correctly")
	}
}
